#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Orang: talking about people, from asking who someone is to comparing two of them.

People are the thing learners talk about most and the thing a template bank handles worst:
"友達" dropped into a slot produces the same sentence for asking who someone is, asking a
friend's job, and saying a friend is kind. Those are four different questions, so they are
four different functions here.
"""
from compose import sent, add_words

add_words({
    '何歳': ('nansai', 'berapa umur', 'how old'),
    '歳': ('sai', 'tahun (umur)', 'years old'),
    '知り合い': ('shiriai', 'kenalan', 'acquaintance'),
    '結婚しています': ('kekkon shite imasu', 'sudah menikah', 'is married'),
    '独身': ('dokushin', 'lajang', 'single'),
    '似ています': ('nite imasu', 'mirip', 'resembles'),
    '優しい': ('yasashii', 'baik hati', 'kind'),
    '面白い': ('omoshiroi', 'menarik / lucu', 'interesting / funny'),
    '若い': ('wakai', 'muda', 'young'),
    '年上': ('toshiue', 'lebih tua', 'older'),
    '年下': ('toshishita', 'lebih muda', 'younger'),
    '出身': ('shusshin', 'asal (daerah)', 'where someone is from'),
    '東京': ('toukyou', 'Tokyo', 'Tokyo'),
    'お国': ('okuni', 'negara asal (sopan)', 'home country (polite)'),
    '職場': ('shokuba', 'tempat kerja', 'workplace'),
    '部署': ('busho', 'divisi', 'department'),
    '呼びます': ('yobimasu', 'memanggil (sopan)', 'call (polite)'),
    '呼んで': ('yonde', 'memanggil (bentuk -te)', 'call (te-form)'),
    '会ったことがあります': ('atta koto ga arimasu', 'pernah bertemu', 'have met before'),
    '何年': ('nannen', 'berapa tahun', 'how many years'),
    '紹介します': ('shoukai shimasu', 'memperkenalkan (sopan)', 'introduce (polite)'),
    '紹介する': ('shoukai suru', 'memperkenalkan (biasa)', 'introduce (plain)'),
    'こちら': ('kochira', 'ini (sopan, orang)', 'this person (polite)'),
    'そう': ('sou', 'begitu', 'so / that way'),
    'かっこいい': ('kakkoii', 'keren', 'cool / good-looking'),
    '背': ('se', 'tinggi badan', 'height'),
    '人柄': ('hitogara', 'watak / kepribadian', 'character'),
    '先輩': ('senpai', 'senior', 'senior colleague'),
    '後輩': ('kouhai', 'junior', 'junior colleague'),
    'お子さん': ('okosan', 'anak (orang lain, sopan)', 'someone else\'s child (polite)'),
    'ご兄弟': ('gokyoudai', 'saudara (orang lain, sopan)', 'someone\'s siblings (polite)'),
    'いらっしゃいます': ('irasshaimasu', 'ada / hadir (hormat)', 'is present (honorific)'),
    'おります': ('orimasu', 'ada (merendah)', 'is (humble)'),
    '有名': ('yuumei', 'terkenal', 'famous'),
    '同じ': ('onaji', 'sama', 'same'),
    '違います': ('chigaimasu', 'berbeda / bukan', 'different / is not'),
    'アリ': ('ari', 'Ari (nama)', 'Ari (a name)'),
    '田中': ('tanaka', 'Tanaka (nama keluarga)', 'Tanaka (a surname)'),
    '鈴木': ('suzuki', 'Suzuki (nama keluarga)', 'Suzuki (a surname)'),
    'さん': ('san', 'Pak/Bu (sebutan sopan)', 'Mr/Ms (polite suffix)'),
    'インドネシア': ('indoneshia', 'Indonesia', 'Indonesia'),
    '働きます': ('hatarakimasu', 'bekerja (sopan)', 'work (polite)'),
    'お仕事': ('oshigoto', 'pekerjaan (sopan)', 'work (polite)'),
    'ご家族': ('gokazoku', 'keluarga (orang lain, sopan)', 'someone\'s family (polite)'),
    '三年': ('sannen', 'tiga tahun', 'three years'),
    '二十五歳': ('nijuu gosai', 'dua puluh lima tahun', 'twenty-five years old'),
    '住んでいます': ('sunde imasu', 'tinggal (sopan)', 'live (polite)'),
    'よく': ('yoku', 'sering', 'often'),
    '作って': ('tsukutte', 'membuat (bentuk -te)', 'make (te-form)'),
    'くれる': ('kureru', 'memberi (untuk saya, biasa)', 'give (to me, plain)'),
    'ぐらい': ('guirai', 'kira-kira', 'about / roughly'),
    '性格': ('seikaku', 'sifat / watak', 'personality'),
    '人違い': ('hitochigai', 'salah orang', 'mistaking one person for another'),
    '会った': ('atta', 'bertemu (biasa, lampau)', 'met (plain past)'),
    'こと': ('koto', 'hal (menominalkan kata kerja)', 'thing (nominaliser)'),
    '覚えていない': ('oboete inai', 'tidak ingat (biasa)', 'do not remember (plain)'),
    'どの': ('dono', 'yang mana', 'which'),
    '方': ('kata', 'orang (bentuk sopan)', 'person (polite)'),
    '助かっています': ('tasukatte imasu', 'terbantu (keadaan berlanjut)', 'am being helped'),
}, where='t02_orang')

SINGLE_WORDS = {
    '結婚しています': 'satu predikat (結婚する + ています), bukan frasa',
    '会ったことがあります': 'bentuk pengalaman baku; dipecah kehilangan artinya',
    'いらっしゃいます': 'bentuk hormat dari います, satu kata kerja',
    '知っています': 'satu kata kerja terinfleksi, bukan frasa',
}

FUNCTIONS = {
    'tanya_siapa': 'menanyakan siapa orang itu',
    'sebut_hubungan': 'menjelaskan hubungan dengan seseorang',
    'perkenalkan_ke_orang_lain': 'memperkenalkan seseorang kepada orang lain',
    'perkenalkan_diri_singkat': 'memperkenalkan diri dengan singkat saat kerja',
    'tanya_pekerjaan': 'menanyakan pekerjaan orang lain',
    'jawab_pekerjaan': 'menyebutkan pekerjaan sendiri',
    'tanya_asal': 'menanyakan daerah asal',
    'jawab_asal': 'menyebutkan daerah asal sendiri',
    'tanya_umur': 'menanyakan umur',
    'jawab_umur': 'menyebutkan umur',
    'tanya_keluarga': 'menanyakan keluarga',
    'cerita_keluarga': 'menceritakan keadaan keluarga',
    'tanya_kenal': 'menanyakan apakah kenal seseorang',
    'tanya_lamanya_kenal': 'menanyakan sudah berapa lama kenal',
    'puji_orang': 'memuji sifat seseorang',
    'banding_dua_orang': 'membandingkan dua orang',
    'mirip': 'mengatakan dua orang mirip',
    'salah_orang': 'mengaku salah orang',
    'ingat_wajah': 'mengatakan ingat wajahnya',
    'tanya_senior': 'menanyakan senior atau atasan di tempat kerja',
    'panggil_nama': 'meminta dipanggil dengan nama tertentu',
    'cerita_teman_kerja': 'menceritakan rekan kerja',
}

SENTENCES = [
    sent(
        key='tanya_siapa', rel='orang_asing', fn='tanya_siapa',
        words=['あの', '人', 'は', '誰', 'です', 'か', '。'],
        id_t='Orang itu siapa?', en_t='Who is that person?',
        sit='Menanyakan orang yang berdiri agak jauh', sit_en='Asking about someone standing further off',
        note='あの人は誰ですか menanyakan orang ketiga; untuk menunjuk dengan sopan, あの方はどなたですか lebih halus.',
        note_en='あの人は誰ですか asks about a third person; あの方はどなたですか is the more deferential form.',
    ),
    sent(
        key='sebut_hubungan', rel='asing', fn='sebut_hubungan',
        words=['あの', '人', 'は', '私', 'の', '友達', 'です', '。'],
        id_t='Orang itu teman saya.', en_t='That person is my friend.',
        sit='Menjelaskan hubungan dengan orang yang disebut', sit_en='Explaining how you know someone',
        note='私の友達です menempelkan kepemilikan; tanpa 私の kalimatnya terdengar seperti menyebut orang asing.',
        note_en='私の友達です marks whose friend it is; without 私の it sounds like pointing out a stranger.',
    ),
    sent(
        key='perkenalkan_ke_orang_lain', rel='asing', fn='perkenalkan_ke_orang_lain',
        words=['こちら', 'は', '同僚', 'の', 'アリ', 'さん', 'です', '。'],
        id_t='Ini rekan kerja saya, Ari.', en_t='This is my colleague, Ari.',
        sit='Memperkenalkan rekan kerja kepada orang lain', sit_en='Introducing a colleague to someone',
        note='こちら adalah cara sopan menunjuk orang; この人 akan terdengar kasar dalam perkenalan.',
        note_en='こちら is the polite way to indicate a person; この人 sounds blunt in an introduction.',
    ),
    sent(
        key='perkenalkan_diri_singkat', rel='rekan', fn='perkenalkan_diri_singkat', long=True,
        words=['今日', 'から', '同じ', '部署', 'で', '働きます', 'ので', '、', 'よろしく', 'お願いします', '。'],
        id_t='Mulai hari ini saya bekerja di divisi yang sama, mohon bantuannya.', en_t='Starting today I work in the same department, so please treat me well.',
        sit='Perkenalan diri di hari pertama kerja', sit_en='Introducing yourself on your first day',
        note='ので menyambungkan perkenalan dengan permintaan bantuan; itu yang membuatnya terdengar mulus, bukan seperti dua kalimat terpisah.',
        note_en='ので links the introduction to the request for help; that is what makes it flow instead of being two separate sentences.',
    ),
    sent(
        key='tanya_pekerjaan', rel='asing', fn='tanya_pekerjaan',
        words=['お仕事', 'は', '何', 'です', 'か', '。'],
        id_t='Pekerjaan Anda apa?', en_t='What do you do for work?',
        sit='Menanyakan pekerjaan orang yang baru dikenal', sit_en='Asking a new acquaintance about work',
        note='お di depan 仕事 menaikkan kesopanan; 仕事は何ですか tanpa お hanya pantas untuk sesama akrab.',
        note_en='The お before 仕事 raises the register; 仕事は何ですか without it only suits peers you know well.',
    ),
    sent(
        key='jawab_pekerjaan', rel='asing', fn='jawab_pekerjaan',
        words=['会社員', 'です', '。', '駅', 'の', '近く', 'の', '事務所', 'で', '働いています', '。'],
        id_t='Saya karyawan. Saya bekerja di kantor dekat stasiun.', en_t='I am a company employee. I work at an office near the station.',
        sit='Menjawab pertanyaan pekerjaan dengan sedikit keterangan', sit_en='Answering about your work with a little detail',
        note='Menambah tempat kerja setelah jawaban singkat membuat percakapan berjalan; jawaban satu kata sering mematikan obrolan.',
        note_en='Adding the workplace after the short answer keeps the conversation going; a one-word answer often ends it.',
    ),
    sent(
        key='tanya_asal', rel='asing', fn='tanya_asal',
        words=['お国', 'は', 'どちら', 'です', 'か', '。'],
        id_t='Anda berasal dari negara mana?', en_t='Where are you from?',
        sit='Menanyakan asal kepada orang asing', sit_en='Asking a foreigner where they are from',
        note='Untuk orang Jepang, お国ではなくご出身はどちらですか yang dipakai; お国 cocok untuk orang dari luar Jepang.',
        note_en='For a Japanese person you would ask ご出身はどちらですか rather than お国; お国 suits someone from abroad.',
    ),
    sent(
        key='jawab_asal', rel='asing', fn='jawab_asal',
        words=['インドネシア', 'から', '来ました', '。', '東京', 'に', '三年', '住んでいます', '。'],
        id_t='Saya datang dari Indonesia. Sudah tiga tahun tinggal di Tokyo.', en_t='I came from Indonesia. I have lived in Tokyo for three years.',
        sit='Menyebutkan asal dan lama tinggal', sit_en='Saying where you are from and how long you have stayed',
        note='住んでいます dengan 三年 berarti sudah tiga tahun dan masih berlanjut, bukan tiga tahun lalu.',
        note_en='住んでいます with 三年 means three years and still going, not three years ago.',
    ),
    sent(
        key='tanya_umur', rel='asing', fn='tanya_umur',
        words=['お子さん', 'は', '何歳', 'です', 'か', '。'],
        id_t='Anak Anda berapa umur?', en_t='How old is your child?',
        sit='Menanyakan umur anak orang lain', sit_en='Asking the age of someone\'s child',
        note='Menanyakan umur langsung kepada orang dewasa terasa kurang halus; yang lazim adalah menanyakan umur anak atau menunggu disebut sendiri.',
        note_en='Asking an adult their age directly is intrusive; asking about their child, or waiting to be told, is what people do.',
    ),
    sent(
        key='jawab_umur', rel='asing', fn='jawab_umur',
        words=['来月', 'で', '二十五歳', 'に', 'なります', '。'],
        id_t='Bulan depan saya genap dua puluh lima tahun.', en_t='I turn twenty-five next month.',
        sit='Menyebutkan umur menjelang ulang tahun', sit_en='Giving your age just before a birthday',
        note='来月で…になります menyebut umur yang akan datang, jadi tidak membohongi keadaan hari ini.',
        note_en='来月で…になります gives the age you are about to reach, so it does not misstate today.',
    ),
    sent(
        key='tanya_keluarga', rel='rekan', fn='tanya_keluarga',
        words=['ご家族', 'は', '東京', 'に', 'いらっしゃいます', 'か', '。'],
        id_t='Apakah keluarga Anda ada di Tokyo?', en_t='Is your family in Tokyo?',
        sit='Menanyakan keberadaan keluarga rekan', sit_en='Asking a colleague where their family lives',
        note='いらっしゃいます adalah bentuk hormat dari います; memakainya untuk keluarga orang lain adalah hal yang baku.',
        note_en='いらっしゃいます is the honorific form of います; using it for someone else\'s family is standard.',
    ),
    sent(
        key='cerita_keluarga', rel='teman', fn='cerita_keluarga', long=True,
        words=['母', 'は', '料理', 'が', '上手', 'だ', 'から', '、', '家', 'で', 'よく', '作って', 'くれる', '。'],
        id_t='Karena ibu saya pandai memasak, dia sering memasakkan untuk saya di rumah.', en_t='My mother cooks well, so she often cooks for me at home.',
        sit='Menceritakan kebiasaan keluarga ke teman', sit_en='Talking about family habits to a friend',
        note='作ってくれる dipakai karena ibu berbuat untuk saya; bentuk sopan 作ってもらいます akan mengubah nada cerita pribadi ini.',
        note_en='作ってくれる is used because she does it for me; the polite 作ってもらいます would change the tone of a personal story.',
    ),
    sent(
        key='tanya_kenal', rel='rekan', fn='tanya_kenal',
        words=['部長', 'の', '田中', 'さん', 'を', '知っています', 'か', '。'],
        id_t='Apakah Anda kenal Pak Tanaka, kepala bagian?', en_t='Do you know Mr Tanaka, the department head?',
        sit='Menanyakan apakah rekan mengenal seseorang', sit_en='Checking whether a colleague knows someone',
        note='知っていますか menanyakan keadaan tahu; 知りますか tidak dipakai karena tahu bukan tindakan yang sedang dilakukan.',
        note_en='知っていますか asks about a state of knowing; 知りますか is not used because knowing is not an action in progress.',
    ),
    sent(
        key='tanya_lamanya_kenal', rel='teman', fn='tanya_lamanya_kenal',
        words=['アリ', 'さん', 'と', '何年', 'ぐらい', '知り合い', '？'],
        id_t='Sudah berapa tahun kenal dengan Ari?', en_t='How many years have you known Ari?',
        sit='Menanyakan sudah berapa lama kenal', sit_en='Asking how long two people have known each other',
        note='知り合い memakai ぐらい karena lama perkenalan jarang diingat tepat.',
        note_en='知り合い takes ぐらい because people rarely remember exactly how long they have known each other.',
    ),
    sent(
        key='puji_orang', rel='teman', fn='puji_orang',
        words=['彼', 'は', 'とても', '面白い', '人', 'だ', 'よ', '。'],
        id_t='Dia orang yang sangat lucu.', en_t='He is a really funny person.',
        sit='Memuji sifat teman kepada teman lain', sit_en='Describing a friend to another friend',
        note='面白い untuk orang berarti lucu atau menarik; untuk benda berarti menarik. Konteksnya yang menentukan.',
        note_en='For a person 面白い means funny or interesting; for a thing it means interesting. Context decides.',
    ),
    sent(
        key='banding_dua_orang', rel='rekan', fn='banding_dua_orang', long=True,
        words=['妹', 'は', '私', 'より', '背', 'が', '高い', 'けど', '、', '性格', 'は', '私', 'と', '同じ', 'です', '。'],
        id_t='Adik saya lebih tinggi daripada saya, tapi sifatnya sama dengan saya.', en_t='My younger sister is taller than me, but her character is like mine.',
        sit='Membandingkan diri dengan adik', sit_en='Comparing yourself with a sibling',
        note='より menandai pembanding; けど menyeimbangkan dua sifat yang berlawanan, jadi tidak terdengar seperti mengeluh.',
        note_en='より marks the comparison and けど balances two opposing traits, so it does not sound like complaining.',
    ),
    sent(
        key='mirip', rel='asing', fn='mirip',
        words=['お子さん', 'は', 'お母さん', 'に', '似ています', 'ね', '。'],
        id_t='Anaknya mirip ibunya ya.', en_t='The child looks like the mother.',
        sit='Menyebut kemiripan anak dengan orang tuanya', sit_en='Noting a child resembles a parent',
        note='に似ています menandai pihak yang ditiru dengan に, bukan と.',
        note_en='に似ています marks the person resembled with に, not と.',
    ),
    sent(
        key='salah_orang', rel='asing', fn='salah_orang',
        words=['すみません', '、', '人違い', 'で', 'は', 'ありません', 'か', '。'],
        id_t='Permisi, bukankah Anda orang yang lain?', en_t='Excuse me, have I got the wrong person?',
        sit='Menyadari salah mengenali orang', sit_en='Realising you mistook someone',
        note='人違いでした ditutup ではありませんか supaya memastikan tanpa menuduh.',
        note_en='人違いでした closed with ではありませんか checks without accusing.',
    ),
    sent(
        key='ingat_wajah', rel='teman', fn='ingat_wajah',
        words=['どこ', 'か', 'で', '会った', 'こと', 'が', 'ある', 'けど', '、', '名前', 'は', '覚えていない', '。'],
        id_t='Sepertinya pernah bertemu di suatu tempat, tapi saya tidak ingat namanya.', en_t='I feel we have met somewhere, but I cannot remember your name.',
        sit='Mengenali wajah tanpa ingat nama', sit_en='Recognising a face but not the name',
        note='会ったことがある menyatakan pengalaman, bukan pertemuan tertentu; どこかで menandai ingatan yang kabur.',
        note_en='会ったことがある states experience rather than one specific meeting, and どこかで marks the blurred memory.',
    ),
    sent(
        key='tanya_senior', rel='rekan', fn='tanya_senior',
        words=['先輩', 'の', '鈴木', 'さん', 'は', 'どの', '方', 'です', 'か', '。'],
        id_t='Senior saya Pak Suzuki yang mana?', en_t='Which one is Mr Suzuki, my senior?',
        sit='Mencari orang di ruangan yang belum dikenal', sit_en='Looking for someone in an unfamiliar room',
        note='どの方ですか memakai 方 (bentuk sopan dari 人) karena yang ditanyakan orang yang lebih senior.',
        note_en='どの方ですか uses 方, the polite form of 人, because the person asked about is a senior.',
    ),
    sent(
        key='panggil_nama', rel='asing', fn='panggil_nama',
        words=['アリ', 'と', '呼んで', 'ください', '。'],
        id_t='Panggil saja Ari.', en_t='Please call me Ari.',
        sit='Meminta dipanggil dengan nama pendek', sit_en='Asking to be called by a short name',
        note='と呼んでください menyatakan nama yang diinginkan; pola ini juga dipakai untuk nama panggilan.',
        note_en='と呼んでください states the name you want used; the same pattern works for a nickname.',
    ),
    sent(
        key='cerita_teman_kerja', rel='rekan', fn='cerita_teman_kerja', long=True,
        words=['同僚', 'の', '田中', 'さん', 'は', '仕事', 'が', '早い', 'ので', '、', 'いつも', '助かっています', '。'],
        id_t='Rekan saya Pak Tanaka kerjanya cepat, jadi saya selalu terbantu.', en_t='My colleague Tanaka works fast, so he always helps me out.',
        sit='Menceritakan rekan kerja yang bisa diandalkan', sit_en='Talking about a reliable colleague',
        note='助かっています menyatakan keadaan yang berlanjut, bukan sekali tertolong; itu yang membuat pujiannya terdengar tulus.',
        note_en='助かっています states an ongoing condition rather than one instance, which is what makes the praise sound sincere.',
    ),
]
