#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Makanan: ordering, eating, cooking, and everything said around a table.

A restaurant is where a learner most needs a sentence ready before they need it, so the
functions here follow the meal in order: getting a recommendation, ordering food and drink,
asking what is in a dish, stating an allergy before the food arrives rather than after,
asking for a change, being asked how it tastes, praising it, asking for more, asking for the
bill, and leaving. The two functions that matter most are the least glamorous: saying what
you cannot eat, and turning down food that has already been put in front of you.
"""
from compose import sent, add_words

add_words({
    'おすすめ': ('osusume', 'rekomendasi', 'recommendation'),
    '定食': ('teishoku', 'set menu', 'set meal'),
    '日替わり': ('higawari', 'menu harian', 'daily special'),
    'お会計': ('okaikei', 'tagihan (sopan)', 'the bill (polite)'),
    'お水': ('omizu', 'air (sopan)', 'water (polite)'),
    'いただけますか': ('itadakemasu ka', 'boleh saya minta (sopan)', 'could I have (humble)'),
    'アレルギー': ('arerugii', 'alergi', 'allergy'),
    '豚肉': ('butaniku', 'daging babi', 'pork'),
    '甲殻類': ('koukakurui', 'kerang dan udang', 'shellfish'),
    '抜いて': ('nuite', 'menghilangkan (bentuk -te)', 'leave out (te-form)'),
    'もらえますか': ('moraemasu ka', 'boleh minta (dibuatkan)', 'could you (do it for me)'),
    '別々に': ('betsubetsu ni', 'terpisah', 'separately'),
    '辛い': ('karai', 'pedas', 'spicy'),
    '甘い': ('amai', 'manis', 'sweet'),
    'すっぱい': ('suppai', 'asam', 'sour'),
    '切って': ('kitte', 'memotong (bentuk -te)', 'cut (te-form)'),
    'おかわり': ('okawari', 'tambahan (nasi/lauk)', 'a refill'),
    'お腹いっぱい': ('onaka ippai', 'kenyang', 'full (stomach)'),
    '包んで': ('tsutsunde', 'membungkus (bentuk -te)', 'wrap (te-form)'),
    'おすすめしません': ('osusume shimasen', 'tidak saya sarankan', 'I do not recommend it'),
    '目玉焼き': ('medamayaki', 'telur mata sapi', 'fried egg'),
    'アレルギーがあります': ('arerugii ga arimasu', 'punya alergi', 'have an allergy'),
    '飲みません': ('nomimasen', 'tidak minum (sopan)', 'do not drink (polite)'),
    'すごく': ('sugoku', 'sangat (akrab)', 'really (casual)'),
    'だし': ('dashi', 'kaldu Jepang', 'dashi stock'),
    '味付け': ('ajitsuke', 'bumbu / cara membumbui', 'seasoning'),
    '煮て': ('nite', 'merebus/memasak dengan kuah (bentuk -te)', 'simmer (te-form)'),
    '焼き魚': ('yakizakana', 'ikan bakar', 'grilled fish'),
    '別々で': ('betsubetsu de', 'terpisah (membayar)', 'separately (paying)'),
    # verbs not yet in the shared lexicon
    'エビ': ('ebi', 'udang', 'shrimp'),
    '入れない': ('irenai', 'tidak memasukkan (biasa)', 'do not put in (plain)'),
    'きて': ('kite', 'datang (bentuk -te)', 'come (te-form)'),
    'お味': ('oaji', 'rasa (sopan)', 'taste (polite)'),
    'いかが': ('ikaga', 'bagaimana (sopan)', 'how (polite)'),
    'きいて': ('kiite', 'terasa / bekerja (bentuk -te)', 'come through (te-form)'),
    'いて': ('ite', 'ada (bentuk -te)', 'be (te-form)'),
    'ちょうど': ('choudo', 'pas / tepat', 'just right'),
    'せっかく': ('sekkaku', 'sayang sekali kalau tidak dipakai', 'kindly offered / going to the trouble'),
    'いっぱい': ('ippai', 'penuh', 'full'),
    'な': ('na', 'adalah (penghubung kata sifat-na)', 'is (na-adjective linker)'),
    '残った': ('nokotta', 'tersisa (biasa, lampau)', 'left over (plain past)'),
    '払えます': ('haraemasu', 'bisa membayar (sopan)', 'can pay (polite)'),
    'よかったら': ('yokattara', 'kalau mau / kalau berkenan', 'if you like'),
    '一緒': ('issho', 'bersama', 'together'),
    '鍋': ('nabe', 'panci', 'pot'),
    '五分': ('gofun', 'lima menit', 'five minutes'),
    'ほど': ('hodo', 'sekitar / kira-kira', 'about / approximately'),
    '取って': ('totte', 'mengambil (bentuk -te)', 'take (te-form)'),
    '味噌': ('miso', 'pasta miso', 'miso paste'),
    '溶いて': ('toite', 'melarutkan (bentuk -te)', 'dissolve (te-form)'),
    '最後': ('saigo', 'terakhir', 'last'),
    '豆腐': ('toufu', 'tahu', 'tofu'),
    '入れる': ('ireru', 'memasukkan (biasa)', 'put in (plain)'),
    '無理': ('muri', 'tidak mungkin / tidak bisa', 'impossible / cannot'),
    '作って': ('tsukutte', 'membuat (bentuk -te)', 'make (te-form)'),
    '食べられる': ('taberareru', 'bisa makan (biasa)', 'can eat (plain)'),
    'もの': ('mono', 'hal / benda (abstrak)', 'thing (abstract)'),
}, where='t03_makanan')

SINGLE_WORDS = {
    'アレルギーがあります': 'satu predikat tetap; dipecah mengubah artinya',
    'いただけますか': 'bentuk permintaan sopan sebagai satu kesatuan',
    'おすすめしません': 'satu predikat (saran negatif), bukan frasa',
    'ごちそうさまでした': 'ungkapan penutup makan, satu kesatuan',
    '食べられません': 'satu kata kerja potensial negatif, bukan frasa',
    '食べられます': 'satu kata kerja potensial, bukan frasa',
    '食べてみて': 'ajakan mencoba, satu kesatuan',
    '持ち帰ります': 'satu kata kerja majemuk, bukan frasa',
    '味噌汁': 'satu kata (sup miso), bukan frasa',
    '目玉焼き': 'satu kata (telur mata sapi), bukan frasa',
    '焼き魚': 'satu kata (ikan bakar), bukan frasa',
    '気をつけます': 'satu predikat tetap, bukan frasa',
    'お腹いっぱい': 'ungkapan kenyang sebagai satu kesatuan',
    'すごく': 'satu kata keterangan',
    'いただきます': 'ungkapan tetap sebelum makan, satu kesatuan',
}

SET_PHRASES = {
    'terima_kasih_makan': 'ごちそうさまでした sopan menurut pemakaian, tanpa predikat',
    'sebelum_makan': 'いただきます adalah ungkapan tetap sebelum makan',
}

FUNCTIONS = {
    'tanya_rekomendasi': 'menanyakan rekomendasi menu',
    'pesan_makanan': 'memesan makanan',
    'pesan_minuman': 'memesan minuman',
    'pesan_set_menu': 'memesan menu set',
    'tanya_isi': 'menanyakan isi sebuah hidangan',
    'bilang_alergi': 'memberi tahu alergi sebelum makanan datang',
    'minta_tanpa_bahan': 'meminta hidangan tanpa bahan tertentu',
    'minta_pisah': 'meminta tagihan atau porsi terpisah',
    'tanya_rasa': 'menanyakan bagaimana rasanya',
    'bilang_rasa': 'menceritakan rasa makanan',
    'puji_masakan': 'memuji masakan',
    'minta_tambahan': 'meminta tambahan nasi',
    'bilang_kenyang': 'mengatakan sudah kenyang',
    'tolak_tawaran': 'menolak tawaran makanan dengan halus',
    'minta_bungkus': 'meminta makanan dibungkus',
    'minta_tagihan': 'meminta tagihan',
    'bayar_pisah': 'meminta bayar terpisah',
    'sebelum_makan': 'mengucapkan sebelum makan',
    'terima_kasih_makan': 'mengucapkan terima kasih setelah makan',
    'undang_makan': 'mengajak makan',
    'tanya_bahan_toko': 'menanyakan letak bahan di toko',
    'langkah_masak': 'menjelaskan urutan memasak',
    'resep_sederhana': 'menjelaskan cara membuat masakan rumah',
    'bilang_kurang_suka': 'mengatakan tidak menyukai suatu bahan',
}

SENTENCES = [
    sent(
        key='tanya_rekomendasi', rel='pelayan', fn='tanya_rekomendasi',
        words=['すみません', '、', 'おすすめ', 'は', '何', 'です', 'か', '。'],
        id_t='Permisi, apa rekomendasinya?', en_t='Excuse me, what do you recommend?',
        sit='Menanyakan rekomendasi kepada pelayan', sit_en='Asking the staff what to order',
        note='おすすめは何ですか sederhana dan selalu aman; おすすめはどれですか menanyakan pilihan di antara yang terlihat.',
        note_en='おすすめは何ですか is simple and always safe; おすすめはどれですか asks which of the visible options.',
    ),
    sent(
        key='pesan_makanan', rel='pelayan', fn='pesan_makanan',
        words=['これ', 'を', '一つ', 'お願いします', '。'],
        id_t='Saya pesan ini satu.', en_t='One of these, please.',
        sit='Memesan sambil menunjuk menu', sit_en='Ordering while pointing at the menu',
        note='Menunjuk plus これ を 一つ お願いします menghindari salah ucap nama hidangan, dan tetap sopan.',
        note_en='Pointing plus これ を 一つ お願いします avoids mispronouncing a dish name and stays polite.',
    ),
    sent(
        key='pesan_minuman', rel='pelayan', fn='pesan_minuman',
        words=['お水', 'を', 'いただけますか', '。'],
        id_t='Boleh saya minta air?', en_t='Could I have some water?',
        sit='Meminta air di restoran', sit_en='Asking for water at a restaurant',
        note='いただけますか adalah bentuk paling sopan untuk meminta; ください juga benar tapi lebih langsung.',
        note_en='いただけますか is the most polite way to ask; ください is also correct but more direct.',
    ),
    sent(
        key='pesan_set_menu', rel='pelayan', fn='pesan_set_menu',
        words=['日替わり', '定食', 'を', 'お願いします', '。'],
        id_t='Saya pesan set menu harian.', en_t='The daily set meal, please.',
        sit='Memesan menu harian di restoran', sit_en='Ordering the daily special',
        note='注文します dihilangkan setelah お願いします; menambahkannya membuat kalimatnya terasa kaku.',
        note_en='注文します is dropped after お願いします; adding it makes the line stiff.',
    ),
    sent(
        key='tanya_isi', rel='pelayan', fn='tanya_isi',
        words=['この', 'スープ', 'に', '肉', 'は', '入っています', 'か', '。'],
        id_t='Apakah sup ini mengandung daging?', en_t='Does this soup contain meat?',
        sit='Menanyakan isi hidangan sebelum memesan', sit_en='Checking a dish before ordering',
        note='入っていますか menanyakan isi; kata kerja yang sama juga dipakai untuk jadwal yang sudah terisi.',
        note_en='入っていますか asks what is in it; the same verb also describes a schedule that is already taken.',
    ),
    sent(
        key='bilang_alergi', rel='pelayan', fn='bilang_alergi', long=True,
        words=['甲殻類', 'の', 'アレルギー', 'が', 'ある', 'ので', '、', 'エビ', 'は', '抜いて', 'もらえますか', '。'],
        id_t='Karena saya alergi kerang, bisakah udangnya dihilangkan?', en_t='I have a shellfish allergy, so could you leave out the shrimp?',
        sit='Memberi tahu alergi sebelum makanan datang', sit_en='Stating an allergy before the food arrives',
        note='ので menyampaikan alasan sebelum permintaan, jadi pelayan tahu ini bukan preferensi tapi bahaya.',
        note_en='ので gives the reason before the request, so staff know it is a hazard rather than a preference.',
    ),
    sent(
        key='minta_tanpa_bahan', rel='pelayan', fn='minta_tanpa_bahan',
        words=['豚肉', 'を', '入れない', 'で', '作って', 'もらえますか', '。'],
        id_t='Bisakah dibuat tanpa daging babi?', en_t='Could you make it without pork?',
        sit='Meminta hidangan tanpa bahan tertentu', sit_en='Asking for a dish without one ingredient',
        note='入れないで (tanpa ください) langsung diikuti 作って; rangkaian ini satu permintaan, bukan dua.',
        note_en='入れないで (without ください) runs straight into 作って; the chain is one request, not two.',
    ),
    sent(
        key='minta_pisah', rel='pelayan', fn='minta_pisah',
        words=['別々に', '持って', 'きて', 'ください', '。'],
        id_t='Tolong bawakan terpisah.', en_t='Please bring them separately.',
        sit='Meminta pesanan dibawa terpisah', sit_en='Asking for orders to come separately',
        note='持ってきてください adalah gabungan 持つ + て + 来る; artinya membawa ke arah pembicara.',
        note_en='持ってきてください combines 持つ with 来る, so it means bring toward the speaker.',
    ),
    sent(
        key='tanya_rasa', rel='pelayan', fn='tanya_rasa',
        words=['お味', 'は', 'いかが', 'です', 'か', '。'],
        id_t='Bagaimana rasanya?', en_t='How does it taste?',
        sit='Pelayan menanyakan rasa hidangan', sit_en='Staff checking how a dish tastes',
        note='いかが adalah bentuk sopan dari どう; pelayan memakainya ke pelanggan.',
        note_en='いかが is the polite form of どう; staff use it with customers.',
    ),
    sent(
        key='bilang_rasa', rel='pelayan', fn='bilang_rasa',
        words=['だし', 'が', 'きいて', 'いて', '、', 'とても', 'おいしい', 'です', '。'],
        id_t='Kaldunya terasa, sangat enak.', en_t='The stock really comes through, it is delicious.',
        sit='Menjawab pertanyaan rasa dengan pujian', sit_en='Answering how it tastes with praise',
        note='だしがきいている memuji kedalaman rasa; menyebut bahan yang dipuji jauh lebih meyakinkan daripada おいしい saja.',
        note_en='だしがきいている praises the depth of flavour; naming what is good is far more convincing than おいしい alone.',
    ),
    sent(
        key='puji_masakan', rel='teman', fn='puji_masakan', long=True,
        words=['味付け', 'が', 'ちょうど', 'いい', 'から', '、', '毎日', 'でも', '食べられる', '。'],
        id_t='Bumbunya pas, jadi bisa saya makan setiap hari.', en_t='The seasoning is just right, so I could eat this every day.',
        sit='Memuji masakan rumah teman', sit_en='Praising a friend\'s home cooking',
        note='毎日でも食べられる adalah pujian tidak langsung: karena enak, tidak akan bosan.',
        note_en='毎日でも食べられる is indirect praise: it is so good you would not tire of it.',
    ),
    sent(
        key='minta_tambahan', rel='pelayan', fn='minta_tambahan',
        words=['ご飯', 'の', 'おかわり', 'を', 'お願いします', '。'],
        id_t='Saya minta tambahan nasi.', en_t='Could I have a refill of rice?',
        sit='Meminta tambahan nasi di restoran', sit_en='Asking for a rice refill',
        note='おかわり khusus untuk tambahan makanan atau minuman yang sama, bukan untuk hidangan baru.',
        note_en='おかわり is only for more of the same food or drink, not for a new dish.',
    ),
    sent(
        key='bilang_kenyang', rel='teman', fn='bilang_kenyang',
        words=['もう', 'お腹いっぱい', 'だ', 'よ', '。'],
        id_t='Sudah kenyang.', en_t='I am full already.',
        sit='Menolak tambahan karena sudah kenyang', sit_en='Declining more food because you are full',
        note='もう di depan membuatnya jelas bukan penolakan sopan, tapi keadaan sebenarnya.',
        note_en='The もう in front makes it clear this is a real state rather than a polite refusal.',
    ),
    sent(
        key='tolak_tawaran', rel='tetangga', fn='tolak_tawaran', long=True,
        words=['せっかく', 'です', 'けど', '、', '今', 'お腹', 'が', 'いっぱい', 'な', 'ので', '。'],
        id_t='Sayang sekali, tapi sekarang perut saya kenyang.', en_t='That is kind of you, but I am full right now.',
        sit='Menolak makanan yang ditawarkan tetangga', sit_en='Turning down food offered by a neighbour',
        note='Kalimatnya sengaja tidak ditutup; menggantung di ので membuat penolakan terasa lebih halus daripada いりません.',
        note_en='The sentence deliberately stops at ので; trailing off is softer than a flat いりません.',
    ),
    sent(
        key='minta_bungkus', rel='pelayan', fn='minta_bungkus',
        words=['残った', '分', 'を', '包んで', 'いただけますか', '。'],
        id_t='Boleh minta sisanya dibungkus?', en_t='Could you wrap up what is left?',
        sit='Meminta sisa makanan dibungkus', sit_en='Asking to take the leftovers home',
        note='残った分 (bagian yang tersisa) lebih halus daripada langsung menyebut 残り物.',
        note_en='残った分 (the part left over) is softer than saying 残り物 outright.',
    ),
    sent(
        key='minta_tagihan', rel='pelayan', fn='minta_tagihan',
        words=['すみません', '、', 'お会計', 'を', 'お願いします', '。'],
        id_t='Permisi, saya minta tagihannya.', en_t='Excuse me, the bill please.',
        sit='Meminta tagihan setelah makan', sit_en='Asking for the bill after a meal',
        note='お会計 atau お勘定, keduanya halus; お金を払います terdengar seperti menawarkan uang di tengah ruangan.',
        note_en='お会計 and お勘定 are both fine; お金を払います sounds like waving money across the room.',
    ),
    sent(
        key='bayar_pisah', rel='pelayan', fn='bayar_pisah',
        words=['別々で', '払えます', 'か', '。'],
        id_t='Bisa bayar terpisah?', en_t='Can we pay separately?',
        sit='Menanyakan pembayaran terpisah', sit_en='Asking to split the bill',
        note='払えます adalah bentuk potensial dari 払います, jadi yang ditanyakan kemampuan, bukan izin.',
        note_en='払えます is the potential form of 払います, so the question is about ability rather than permission.',
    ),
    sent(
        key='sebelum_makan', rel='keluarga', fn='sebelum_makan',
        words=['いただきます', '。'],
        id_t='Selamat makan.', en_t='Thanks for the food.',
        sit='Sebelum mulai makan', sit_en='Before starting to eat',
        note='Diucapkan sebelum makan, termasuk di restoran dan sendirian; bukan doa, tapi terima kasih atas hidangannya.',
        note_en='Said before eating, including in restaurants and alone; it thanks the food rather than blessing it.',
    ),
    sent(
        key='terima_kasih_makan', rel='keluarga', fn='terima_kasih_makan',
        words=['ごちそうさまでした', '。'],
        id_t='Terima kasih atas makanannya.', en_t='Thank you for the meal.',
        sit='Setelah selesai makan', sit_en='After finishing a meal',
        note='ごちそうさまでした dipakai setelah selesai; kalau kita yang mentraktir, bentuk ごちそうしました jarang dipakai.',
        note_en='ごちそうさまでした is said after finishing; if you paid, ごちそうしました is rarely used.',
    ),
    sent(
        key='undang_makan', rel='rekan', fn='undang_makan',
        words=['よかったら', '、', '一緒', 'に', '昼ご飯', 'を', '食べません', 'か', '。'],
        id_t='Kalau mau, makan siang bersama?', en_t='If you like, shall we have lunch together?',
        sit='Mengajak rekan kerja makan siang', sit_en='Inviting a colleague to lunch',
        note='よかったら di depan membuat ajakan mudah ditolak; ませんか lebih halus daripada ましょう.',
        note_en='よかったら in front makes the invitation easy to decline; ませんか is softer than ましょう.',
    ),
    sent(
        key='tanya_bahan_toko', rel='petugas_toko', fn='tanya_bahan_toko',
        words=['すみません', '、', '醤油', 'は', 'どこ', 'に', 'あります', 'か', '。'],
        id_t='Permisi, kecap asin ada di mana?', en_t='Excuse me, where is the soy sauce?',
        sit='Mencari bahan di supermarket', sit_en='Looking for an ingredient in a supermarket',
        note='どこにありますか cocok untuk benda mati; どこにいますか hanya untuk orang dan hewan.',
        note_en='どこにありますか suits objects; どこにいますか is only for people and animals.',
    ),
    sent(
        key='langkah_masak', rel='rekan', fn='langkah_masak', long=True,
        words=['野菜', 'を', '切って', 'から', '、', '鍋', 'で', '五分', 'ほど', '煮て', 'ください', '。'],
        id_t='Setelah memotong sayurnya, rebus di panci sekitar lima menit.', en_t='After cutting the vegetables, simmer them in a pot for about five minutes.',
        sit='Menjelaskan urutan langkah memasak ke rekan', sit_en='Giving a colleague the order of cooking steps',
        note='てから memaksa urutannya jelas: memotong dulu, baru merebus. それから hanya menambahkan langkah berikutnya.',
        note_en='てから forces the order: cut first, simmer after. それから merely adds a next step.',
    ),
    sent(
        key='resep_sederhana', rel='teman', fn='resep_sederhana', long=True,
        words=['味噌汁', 'は', 'だし', 'を', '取って', 'から', '、', '味噌', 'を', '溶いて', '最後', 'に', '豆腐', 'を', '入れる', '。'],
        id_t='Sup miso dibuat dengan mengambil kaldu dulu, lalu melarutkan miso, terakhir memasukkan tahu.', en_t='For miso soup you make the stock first, then dissolve the miso, and add the tofu last.',
        sit='Menceritakan cara membuat sup miso', sit_en='Explaining how to make miso soup',
        note='Kalimatnya berbentuk biasa karena resep antar teman; kalau ditulis untuk pembaca, bentuknya ます.',
        note_en='The plain form suits telling a friend; a written recipe would use ます.',
    ),
    sent(
        key='bilang_kurang_suka', rel='teman', fn='bilang_kurang_suka', long=True,
        words=['私', 'は', '辛い', 'もの', 'が', '苦手', 'だ', 'から', '、', 'これ', 'は', 'ちょっと', '無理', 'だ', '。'],
        id_t='Karena saya tidak tahan makanan pedas, yang ini agak tidak bisa.', en_t='I cannot handle spicy food, so this one is a bit much for me.',
        sit='Memberi tahu teman saat makanan terlalu pedas', sit_en='Telling a friend a dish is too spicy for you',
        note='苦手だ menyatakan kelemahan diri, bukan keburukan makanan; itu sebabnya terdengar sopan walau menolaknya.',
        note_en='苦手だ names your own limitation rather than the food\'s fault, which is why refusing this way stays polite.',
    ),
]
