#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Belanja: from looking for an item to returning it the week after.

The functions follow a purchase rather than a grammar list: finding the item, checking the
price, the size, the colour and the expiry date, trying it on, deciding, paying by cash or
card, and then the part every phrasebook skips, which is what you say when the thing turns
out to be wrong: the exchange, the refund, and the guarantee. A learner who can ask the
price but not ask for a refund is only half equipped, so both are here.
"""
from compose import sent, add_words

add_words({
    'サイズ': ('saizu', 'ukuran', 'size'),
    '色': ('iro', 'warna', 'colour'),
    '別の': ('betsu no', 'yang lain', 'another'),
    '在庫': ('zaiko', 'stok', 'stock'),
    '売り切れ': ('urikire', 'habis terjual', 'sold out'),
    '割引': ('waribiki', 'diskon', 'discount'),
    'セール': ('seeru', 'obral', 'sale'),
    '試着': ('shichaku', 'mencoba pakaian', 'trying clothes on'),
    '試着室': ('shichakushitsu', 'kamar pas', 'fitting room'),
    '交換': ('koukan', 'penukaran', 'exchange'),
    '返品': ('henpin', 'pengembalian barang', 'return of goods'),
    '保証': ('hoshou', 'garansi', 'guarantee'),
    'レジ': ('reji', 'kasir', 'checkout counter'),
    '賞味期限': ('shoumikigen', 'tanggal kedaluwarsa (makanan)', 'best-before date'),
    '会員カード': ('kaiin kaado', 'kartu anggota', 'membership card'),
    'ポイント': ('pointo', 'poin', 'points'),
    '在庫があります': ('zaiko ga arimasu', 'ada stoknya', 'is in stock'),
    '試着してもいいですか': ('shichaku shite mo ii desu ka', 'boleh saya coba?', 'may I try it on'),
    '似合います': ('niaimasu', 'cocok (pada orang)', 'suits (a person)'),
    '合います': ('aimasu', 'pas / cocok (ukuran)', 'fits'),
    'きつい': ('kitsui', 'sempit / ketat', 'tight'),
    '緩い': ('yurui', 'longgar', 'loose'),
    '長い': ('nagai', 'panjang', 'long'),
    '短い': ('mijikai', 'pendek', 'short'),
    '売っています': ('utte imasu', 'sedang menjual / ada dijual', 'is on sale / sells'),
    '置いてあります': ('oite arimasu', 'tersedia (barang dipajang)', 'is placed (stock on display)'),
    '包みます': ('tsutsumimasu', 'membungkus (sopan)', 'wrap (polite)'),
    '返します': ('kaeshimasu', 'mengembalikan (sopan)', 'return (polite)'),
    '変えます': ('kaemasu', 'menukar (sopan)', 'exchange (polite)'),
    '変えてもいいですか': ('kaete mo ii desu ka', 'boleh saya tukar', 'may I exchange it'),
    'もらってもいいですか': ('moratte mo ii desu ka', 'boleh saya terima', 'may I take it'),
    '見せて': ('misete', 'menunjukkan (bentuk -te)', 'show (te-form)'),
    '見せてもらえますか': ('misete moraemasu ka', 'boleh saya lihat', 'could you show me'),
    '試しに': ('tameshi ni', 'sebagai percobaan', 'just to try'),
    '全然大丈夫': ('zenzen daijoubu', 'sama sekali tidak masalah', 'no problem at all'),
    'これで': ('kore de', 'dengan ini', 'with this'),
    'おいくら': ('oikura', 'berapa harganya (sopan)', 'how much (polite)'),
    '安くなります': ('yasuku narimasu', 'jadi lebih murah', 'becomes cheaper'),
    '使えます': ('tsukaemasu', 'bisa dipakai', 'can be used'),
    '足りません': ('tarimasen', 'tidak cukup', 'is not enough'),
    'いくつか': ('ikutsuka', 'beberapa', 'a few'),
    'ところで': ('tokoro de', 'ngomong-ngomong', 'by the way'),
    '思い出しました': ('omoidashimashita', 'baru ingat (lampau)', 'just remembered'),
    '返して': ('kaeshite', 'mengembalikan (bentuk -te)', 'return (te-form)'),
    'いかがですか': ('ikaga desu ka', 'bagaimana (sopan)', 'how about (polite)'),
    '高すぎます': ('takasugimasu', 'terlalu mahal', 'is too expensive'),
    'だった': ('datta', 'adalah (bentuk biasa, lampau)', 'was (plain past copula)'),
    'どれ': ('dore', 'yang mana', 'which one'),
    'もらえます': ('moraemasu', 'bisa minta (sopan)', 'can receive (polite)'),
    'しても': ('shite mo', 'meskipun melakukan', 'even if (te-form + mo)'),
    'なったら': ('nattara', 'kalau menjadi', 'if it becomes'),
    '高すぎる': ('takasugiru', 'terlalu mahal (biasa)', 'too expensive (plain)'),
    '見よう': ('miyou', 'mari lihat (biasa)', 'let us look (plain)'),
    '払えます': ('haraemasu', 'bisa membayar (sopan)', 'can pay (polite)'),
    'いただけますか': ('itadakemasu ka', 'boleh saya minta (sopan)', 'could I have (humble)'),
    '要りません': ('irimasen', 'tidak perlu (sopan)', 'do not need (polite)'),
    '合わなかった': ('awanakatta', 'tidak cocok (biasa, lampau)', 'did not fit (plain past)'),
    'ら': ('ra', 'kalau (kondisional)', 'if (conditional)'),
    '商品': ('shouhin', 'barang dagangan', 'goods / product'),
    '壊れて': ('kowarete', 'rusak (bentuk -te)', 'be broken (te-form)'),
    'いた': ('ita', 'ada / sedang (biasa, lampau)', 'was (plain past)'),
    '返金': ('henkin', 'pengembalian uang', 'refund'),
    'ついています': ('tsuite imasu', 'menyertai / menempel', 'comes with'),
    'あちら': ('achira', 'sebelah sana (sopan)', 'over there (polite)'),
    '三百円': ('sanbyaku en', 'tiga ratus yen', 'three hundred yen'),
    'ありがとうございました': ('arigatou gozaimashita', 'terima kasih (lampau sopan)', 'thank you (polite past)'),
    '色々': ('iroiro', 'berbagai', 'various'),
    'な': ('na', 'adalah (penghubung kata sifat-na)', 'is (na-adjective linker)'),
    '見ている': ('mite iru', 'sedang melihat (biasa)', 'am looking (plain)'),
}, where='t04_belanja')

SINGLE_WORDS = {
    '在庫があります': 'satu predikat tetap (ada stok), bukan frasa bebas',
    '試着してもいいですか': 'bentuk izin baku sebagai satu kesatuan',
    '見せてもらえますか': 'permintaan sopan sebagai satu kesatuan',
    '変えてもいいですか': 'bentuk izin baku sebagai satu kesatuan',
    'もらってもいいですか': 'bentuk izin baku sebagai satu kesatuan',
    'おいくら': 'kata tanya harga yang utuh, bukan お + いくら yang bebas',
    '安くなります': 'satu predikat (menjadi murah), bukan frasa',
    '思い出しました': 'satu kata kerja majemuk, bukan frasa',
    '売っています': 'satu kata kerja terinfleksi, bukan frasa',
    '試着室': 'satu kata majemuk (kamar pas)',
    '会員カード': 'satu kata majemuk (kartu anggota)',
    '賞味期限': 'satu kata majemuk (tanggal kedaluwarsa)',
    '全然大丈夫': 'ungkapan utuh; dipecah kehilangan nada santainya',
    'いかがですか': 'bentuk sopan dari どうですか sebagai satu kesatuan',
    '高すぎます': 'satu predikat (terlalu mahal), bukan frasa',
    'ところで': 'kata penghubung topik, satu kata',
    'ありがとうございました': 'ungkapan terima kasih lampau, satu kesatuan',
}

SET_PHRASES = {
    'kasih_rekomendasi_toko': 'いかがですか bentuk sopan tanpa predikat です',
}

FUNCTIONS = {
    'cari_barang': 'mencari barang di toko',
    'tanya_harga_sopan': 'menanyakan harga dengan sopan',
    'tanya_harga_akrab': 'menanyakan harga ke teman',
    'tanya_ukuran': 'menanyakan ukuran yang tersedia',
    'tanya_warna_lain': 'menanyakan warna lain',
    'minta_lihat': 'meminta melihat barang',
    'coba_pakaian': 'meminta mencoba pakaian',
    'tanya_pas': 'menanyakan apakah ukurannya pas',
    'tanya_stok': 'menanyakan ketersediaan stok',
    'tanya_stok_toko': 'menanyakan apakah toko menjual barang tertentu',
    'tanya_diskon': 'menanyakan diskon',
    'bilang_mahal': 'mengatakan terlalu mahal',
    'beli_barang': 'membeli barang',
    'tanya_bayar_kartu': 'menanyakan bisa bayar dengan kartu',
    'minta_struk': 'meminta struk',
    'minta_kantong': 'menanyakan perlu kantong atau tidak',
    'tanya_tukar': 'menanyakan bisa ditukar',
    'tukar_barang': 'menukar barang yang salah ukuran',
    'minta_refund': 'meminta pengembalian uang',
    'tanya_garansi': 'menanyakan garansi',
    'tanya_kadaluarsa': 'menanyakan tanggal kedaluwarsa',
    'bilang_kurang': 'mengatakan uangnya kurang',
    'bayar_di_kasir': 'menanyakan tempat membayar',
    'terima_kembalian': 'menerima uang kembalian',
    'rekomendasi_toko': 'menawarkan bantuan memilih',
    'bilang_sudah_cukup': 'mengatakan sudah cukup, tidak perlu bantuan',
}

SENTENCES = [
    sent(
        key='cari_barang', rel='petugas_toko', fn='cari_barang',
        words=['すみません', '、', '傘', 'は', 'どこ', 'に', 'あります', 'か', '。'],
        id_t='Permisi, payungnya ada di mana?', en_t='Excuse me, where are the umbrellas?',
        sit='Mencari barang di toko', sit_en='Looking for an item in a shop',
        note='Menyebut barang lalu は…ありますか adalah pola paling cepat dipahami di toko.',
        note_en='Naming the item then は…ありますか is the pattern shop staff understand fastest.',
    ),
    sent(
        key='tanya_harga_sopan', rel='petugas_toko', fn='tanya_harga_sopan',
        words=['これ', 'は', 'おいくら', 'です', 'か', '。'],
        id_t='Ini berapa harganya?', en_t='How much is this?',
        sit='Menanyakan harga kepada petugas', sit_en='Asking a shop attendant the price',
        note='おいくら adalah bentuk sopan dari いくら; これ、いくらですか juga lazim tapi lebih santai.',
        note_en='おいくら is the polite form of いくら; これ、いくらですか is also common but more casual.',
    ),
    sent(
        key='tanya_harga_akrab', rel='teman', fn='tanya_harga_akrab',
        words=['これ', '、', 'いくら', 'だった', '？'],
        id_t='Ini, tadi berapa harganya?', en_t='How much was this?',
        sit='Menanyakan harga barang yang sudah dibeli', sit_en='Asking what something cost after buying it',
        note='だった adalah bentuk lampau biasa dari だ; menanyakan harga barang yang sudah dibeli.',
        note_en='だった is the plain past of だ; this asks about something already bought.',
    ),
    sent(
        key='tanya_ukuran', rel='petugas_toko', fn='tanya_ukuran',
        words=['これ', 'の', 'サイズ', 'は', 'あと', 'どれ', 'が', 'あります', 'か', '。'],
        id_t='Ukuran lain dari ini ada yang mana saja?', en_t='What other sizes of this do you have?',
        sit='Menanyakan ukuran yang masih tersedia', sit_en='Asking which sizes are left',
        note='あとどれが残っていますか menyiratkan sebagian sudah habis, jadi tidak menuntut stok yang tidak ada.',
        note_en='あとどれが残っていますか implies some are gone, so it does not demand stock that does not exist.',
    ),
    sent(
        key='tanya_warna_lain', rel='petugas_toko', fn='tanya_warna_lain',
        words=['これ', 'の', '別の', '色', 'は', 'あります', 'か', '。'],
        id_t='Ada warna lain dari ini?', en_t='Do you have this in another colour?',
        sit='Menanyakan pilihan warna lain', sit_en='Asking about other colour options',
        note='別の色 menempel pada これ lewat の; tanpa これの, kalimatnya menanyakan warna apa pun di toko.',
        note_en='別の色 attaches to これ with の; without これの it asks about any colour in the shop.',
    ),
    sent(
        key='minta_lihat', rel='petugas_toko', fn='minta_lihat',
        words=['すみません', '、', 'それ', 'を', '見せて', 'もらえますか', '。'],
        id_t='Permisi, boleh saya lihat yang itu?', en_t='Excuse me, could you show me that one?',
        sit='Meminta melihat barang di balik kaca', sit_en='Asking to see an item behind the counter',
        note='見せてもらえますか meminta jasa orang, jadi lebih halus daripada 見せてください.',
        note_en='見せてもらえますか asks for a favour, so it is softer than 見せてください.',
    ),
    sent(
        key='coba_pakaian', rel='petugas_toko', fn='coba_pakaian',
        words=['これ', '、', '試着', 'しても', 'いい', 'です', 'か', '。'],
        id_t='Boleh saya coba ini?', en_t='May I try this on?',
        sit='Meminta mencoba pakaian di toko', sit_en='Asking to try clothes on',
        note='試着してもいいですか adalah bentuk izin; 試着室はどこですか hanya menanyakan lokasinya.',
        note_en='試着してもいいですか asks permission; 試着室はどこですか only asks where the room is.',
    ),
    sent(
        key='tanya_pas', rel='petugas_toko', fn='tanya_pas',
        words=['ちょっと', 'きつい', 'です', 'が', '、', 'もう', '一つ', '大きい', 'サイズ', 'は', 'あります', 'か', '。'],
        id_t='Agak sempit, apakah ada ukuran yang lebih besar?', en_t='It is a bit tight, do you have one size larger?',
        sit='Meminta ukuran lebih besar setelah mencoba', sit_en='Asking for a larger size after trying one on',
        note='が setelah きついです menyampaikan keluhan sebelum permintaan, jadi tidak terdengar seperti menuntut.',
        note_en='The が after きついです delivers the complaint before the request, so it does not sound demanding.',
    ),
    sent(
        key='tanya_stok', rel='petugas_toko', fn='tanya_stok',
        words=['この', '色', 'の', '在庫', 'は', 'まだ', 'あります', 'か', '。'],
        id_t='Stok warna ini masih ada?', en_t='Do you still have this colour in stock?',
        sit='Menanyakan stok sebelum memutuskan', sit_en='Checking stock before deciding',
        note='まだありますか menanyakan sisa; ありますか saja bisa dijawab "ada" walau tinggal satu.',
        note_en='まだありますか asks about what remains; ありますか alone can be answered "yes" when only one is left.',
    ),
    sent(
        key='tanya_stok_toko', rel='petugas_toko', fn='tanya_stok_toko',
        words=['この', '店', 'で', '電池', 'を', '売っています', 'か', '。'],
        id_t='Apakah toko ini menjual baterai?', en_t='Does this shop sell batteries?',
        sit='Menanyakan apakah toko menjual barang tertentu', sit_en='Checking whether a shop carries something',
        note='売っていますか menanyakan keadaan menjual; 売りますか menanyakan apakah akan dijual, dan itu pertanyaan lain.',
        note_en='売っていますか asks about the ongoing state of selling; 売りますか asks whether it will be sold, which is different.',
    ),
    sent(
        key='tanya_diskon', rel='petugas_toko', fn='tanya_diskon',
        words=['セール', 'に', 'なったら', '、', 'いくら', 'に', 'なります', 'か', '。'],
        id_t='Kalau sedang obral, jadi berapa harganya?', en_t='If it goes on sale, how much will it be?',
        sit='Menanyakan harga saat obral', sit_en='Asking what the sale price would be',
        note='たら menjadikan obral sebagai syarat, jadi pertanyaannya bersyarat dan tidak menuntut diskon sekarang.',
        note_en='たら makes the sale a condition, so the question is hypothetical and does not demand a discount now.',
    ),
    sent(
        key='bilang_mahal', rel='teman', fn='bilang_mahal',
        words=['ちょっと', '高すぎる', 'から', '、', 'もう', '少し', '安い', 'の', 'を', '見よう', '。'],
        id_t='Agak terlalu mahal, kita lihat yang lebih murah saja.', en_t='It is a bit too expensive, let us look at a cheaper one.',
        sit='Menilai harga terlalu tinggi ke teman', sit_en='Deciding something costs too much',
        note='高すぎる memakai すぎる yang berarti "terlalu"; 高いだけ akan berarti sekadar mahal.',
        note_en='高すぎる uses すぎる, meaning too much; 高いだけ would mean merely expensive.',
    ),
    sent(
        key='beli_barang', rel='petugas_toko', fn='beli_barang',
        words=['これ', 'を', 'ください', '。'],
        id_t='Saya beli yang ini.', en_t='I will take this one.',
        sit='Memutuskan membeli barang', sit_en='Deciding to buy an item',
        note='これ を ください adalah cara membeli yang paling singkat dan selalu sopan.',
        note_en='これ を ください is the shortest way to buy something and is always polite.',
    ),
    sent(
        key='tanya_bayar_kartu', rel='petugas_toko', fn='tanya_bayar_kartu',
        words=['カード', 'で', '払えます', 'か', '。'],
        id_t='Bisa bayar dengan kartu?', en_t='Can I pay by card?',
        sit='Menanyakan cara pembayaran', sit_en='Asking about payment method',
        note='で menandai alat pembayaran: カードで, 現金で. カードを払えます tidak dipakai.',
        note_en='で marks the means of payment: カードで, 現金で. カードを払えます is not used.',
    ),
    sent(
        key='minta_struk', rel='petugas_toko', fn='minta_struk',
        words=['すみません', '、', 'レシート', 'を', 'いただけますか', '。'],
        id_t='Permisi, boleh minta struknya?', en_t='Excuse me, could I have the receipt?',
        sit='Meminta struk setelah membayar', sit_en='Asking for the receipt after paying',
        note='いただけますか dipakai karena struk diberikan oleh orang lain, bukan diambil sendiri.',
        note_en='いただけますか suits this because the receipt is handed to you rather than taken.',
    ),
    sent(
        key='minta_kantong', rel='petugas_toko', fn='minta_kantong',
        words=['袋', 'は', '要りません', '。', '自分', 'の', 'を', '使います', '。'],
        id_t='Tidak perlu kantong. Saya pakai punya sendiri.', en_t='No bag needed. I will use my own.',
        sit='Menolak kantong plastik di kasir', sit_en='Declining a plastic bag at the till',
        note='要りません (tidak perlu) lebih tepat daripada いりません saja, dan terdengar netral di kasir.',
        note_en='要りません (not needed) is the right register at a till and sounds neutral.',
    ),
    sent(
        key='tanya_tukar', rel='petugas_toko', fn='tanya_tukar',
        words=['サイズ', 'が', '合わなかった', 'ら', '、', '交換', 'して', 'もらえます', 'か', '。'],
        id_t='Kalau ukurannya tidak pas, bisa ditukar?', en_t='If the size does not fit, can I exchange it?',
        sit='Menanyakan aturan penukaran sebelum membeli', sit_en='Checking the exchange policy before buying',
        note='Menanyakannya sebelum membayar jauh lebih mudah daripada sesudahnya, dan petugas menghargainya.',
        note_en='Asking before paying is far easier than after, and staff appreciate it.',
    ),
    sent(
        key='tukar_barang', rel='petugas_toko', fn='tukar_barang', long=True,
        words=['昨日', 'ここ', 'で', 'これ', 'を', '買った', 'の', 'です', 'が', '、', 'サイズ', 'が', '小さい', 'ので', '変えてもいいですか', '。'],
        id_t='Ini yang saya beli kemarin di sini, ukurannya kecil, boleh ditukar?', en_t='I bought this here yesterday and the size is too small, may I exchange it?',
        sit='Menukar barang yang salah ukuran', sit_en='Exchanging an item in the wrong size',
        note='のですが menyampaikan keadaan sebelum permintaan; ini pola baku untuk membuka keluhan di toko.',
        note_en='のですが states the situation before the request; it is the standard way to open a complaint in a shop.',
    ),
    sent(
        key='minta_refund', rel='petugas_toko', fn='minta_refund', long=True,
        words=['この', '商品', 'は', '壊れて', 'いた', 'ので', '、', '返金', 'して', 'いただけますか', '。'],
        id_t='Barang ini ternyata rusak, bisakah uangnya dikembalikan?', en_t='This item was broken, could I have a refund?',
        sit='Meminta pengembalian uang untuk barang rusak', sit_en='Asking for a refund on a faulty item',
        note='壊れていた memakai bentuk lampau karena kerusakannya sudah ada saat diterima, bukan terjadi di toko.',
        note_en='壊れていた is past because the fault was already there when you received it, not caused in the shop.',
    ),
    sent(
        key='tanya_garansi', rel='petugas_toko', fn='tanya_garansi',
        words=['これ', 'に', '保証', 'は', 'ついています', 'か', '。'],
        id_t='Apakah ini ada garansinya?', en_t='Does this come with a guarantee?',
        sit='Menanyakan garansi barang elektronik', sit_en='Asking about a guarantee on electronics',
        note='ついています (menempel, menyertai) adalah kata kerja yang dipakai untuk garansi dan aksesori.',
        note_en='ついています (comes attached) is the verb used for guarantees and accessories.',
    ),
    sent(
        key='tanya_kadaluarsa', rel='petugas_toko', fn='tanya_kadaluarsa',
        words=['この', '牛乳', 'の', '賞味期限', 'は', 'いつ', 'まで', 'です', 'か', '。'],
        id_t='Susu ini kedaluwarsa sampai kapan?', en_t='Until when is this milk good?',
        sit='Menanyakan tanggal kedaluwarsa makanan', sit_en='Checking the best-before date on food',
        note='賞味期限 adalah tanggal terbaik untuk dikonsumsi; 消費期限 adalah batas aman, dan keduanya berbeda.',
        note_en='賞味期限 is the best-before date; 消費期限 is the use-by safety limit, and they are different.',
    ),
    sent(
        key='bilang_kurang', rel='petugas_toko', fn='bilang_kurang',
        words=['すみません', '、', 'お金', 'が', '足りません', '。'],
        id_t='Permisi, uang saya kurang.', en_t='Excuse me, I do not have enough money.',
        sit='Uang kurang di depan kasir', sit_en='Not having enough money at the till',
        note='足りません (tidak cukup) untuk jumlah; ありません saja akan berarti uangnya tidak ada sama sekali.',
        note_en='足りません means not enough for the amount; ありません alone would mean there is no money at all.',
    ),
    sent(
        key='bayar_di_kasir', rel='petugas_toko', fn='bayar_di_kasir',
        words=['お会計', 'は', 'あちら', 'の', 'レジ', 'です', '。'],
        id_t='Pembayarannya di kasir sebelah sana.', en_t='Payment is at the till over there.',
        sit='Petugas menunjukkan tempat membayar', sit_en='Staff pointing out where to pay',
        note='あちら の レジ menunjuk arah yang jauh dari pembicara; そちら akan menunjuk ke arah pendengar.',
        note_en='あちら の レジ points away from the speaker; そちら would point toward the listener.',
    ),
    sent(
        key='terima_kembalian', rel='petugas_toko', fn='terima_kembalian',
        words=['お釣り', 'は', '三百円', 'です', '。', 'ありがとうございました', '。'],
        id_t='Kembaliannya tiga ratus yen. Terima kasih.', en_t='Here is three hundred yen change. Thank you.',
        sit='Kasir menyerahkan kembalian', sit_en='A cashier handing back change',
        note='ありがとうございました memakai bentuk lampau karena transaksinya sudah selesai; ini bentuk baku di kasir.',
        note_en='ありがとうございました is past because the transaction is over; this is the standard till formula.',
    ),
    sent(
        key='rekomendasi_toko', rel='petugas_toko', fn='rekomendasi_toko',
        words=['色々', 'な', '色', 'が', 'あります', 'が', '、', 'いかがですか', '。'],
        id_t='Ada berbagai warna, bagaimana?', en_t='We have several colours, how about it?',
        sit='Petugas menawarkan pilihan', sit_en='Staff offering a choice',
        note='いかがですか adalah bentuk sopan dari どうですか; petugas memakainya ke pelanggan.',
        note_en='いかがですか is the polite form of どうですか; staff use it with customers.',
    ),
    sent(
        key='bilang_sudah_cukup', rel='petugas_toko', fn='bilang_sudah_cukup',
        words=['すみません', '、', '見ている', 'だけ', 'です', 'ので', '。'],
        id_t='Permisi, saya hanya melihat-lihat.', en_t='Thanks, I am just looking.',
        sit='Menolak bantuan petugas toko', sit_en='Declining a shop assistant\'s help',
        note='Kalimatnya berhenti di ので, yang membuatnya terasa lebih halus daripada 結構です.',
        note_en='The sentence trails off at ので, which is softer than a flat 結構です.',
    ),
]
