#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Transportasi: trains, buses, taxis, and getting to the right platform on time.

The functions follow a journey rather than a grammar list, and they include the two that a
phrasebook usually omits because they only matter when something goes wrong: being told your
train does not stop here, and finding out you are on the wrong platform. Those are the
moments a learner actually needs a sentence, so they are here alongside buying a ticket.
"""
from compose import sent, add_words

add_words({
    '往復': ('oufuku', 'pulang pergi', 'round trip'),
    '片道': ('katamichi', 'sekali jalan', 'one way'),
    '自由席': ('jiyuuseki', 'kursi bebas', 'non-reserved seat'),
    '指定席': ('shiteiseki', 'kursi pesanan', 'reserved seat'),
    '券売機': ('kenbaiki', 'mesin tiket', 'ticket machine'),
    '改札口': ('kaisatsuguchi', 'gerbang tiket', 'ticket gate'),
    '急行': ('kyuukou', 'kereta ekspres', 'express train'),
    '終電': ('shuuden', 'kereta terakhir', 'last train'),
    '始発': ('shihatsu', 'kereta pertama', 'first train'),
    '満員': ('man\'in', 'penuh sesak', 'packed full'),
    '遅延': ('chien', 'keterlambatan', 'delay'),
    '運休': ('unkyuu', 'tidak beroperasi', 'service cancelled'),
    '行き先': ('ikisaki', 'tujuan', 'destination'),
    '方面': ('houmen', 'arah (jurusan)', 'direction (bound for)'),
    '番線': ('bansen', 'jalur nomor', 'platform number'),
    '何番線': ('nanbansen', 'jalur nomor berapa', 'which platform number'),
    '到着': ('touchaku', 'kedatangan', 'arrival'),
    '出発': ('shuppatsu', 'keberangkatan', 'departure'),
    '止まります': ('tomarimasu', 'berhenti (sopan)', 'stops (polite)'),
    '止まりません': ('tomarimasen', 'tidak berhenti (sopan)', 'does not stop (polite)'),
    '着きます': ('tsukimasu', 'tiba (sopan)', 'arrive (polite)'),
    '着けば': ('tsukeba', 'kalau tiba', 'if it arrives'),
    '間に合います': ('maniaimasu', 'sempat (sopan)', 'be in time (polite)'),
    '間に合いません': ('maniaimasen', 'tidak sempat (sopan)', 'will not make it (polite)'),
    '乗り遅れました': ('noriokuremashita', 'ketinggalan kereta (lampau)', 'missed the train (past)'),
    '乗り越しました': ('norikoshimashita', 'melewati stasiun tujuan', 'went past the stop'),
    '戻ります': ('modorimasu', 'kembali (sopan)', 'go back (polite)'),
    '届けます': ('todokemasu', 'mengantarkan / melaporkan (sopan)', 'deliver / report (polite)'),
    '預けます': ('azukemasu', 'menitipkan (sopan)', 'check in (polite)'),
    '座れます': ('suwaremasu', 'bisa duduk (sopan)', 'can sit (polite)'),
    '座れません': ('suwaremasen', 'tidak bisa duduk (sopan)', 'cannot sit (polite)'),
    '止めて': ('tomete', 'menghentikan (bentuk -te)', 'stop (te-form)'),
    '止まって': ('tomatte', 'berhenti (bentuk -te)', 'stop (te-form)'),
    '降ろして': ('oroshite', 'menurunkan (bentuk -te)', 'let off (te-form)'),
    '真っ直ぐ': ('massugu', 'lurus', 'straight'),
    '信号': ('shingou', 'lampu lalu lintas', 'traffic light'),
    '何分': ('nanpun', 'berapa menit', 'how many minutes'),
    'タクシー乗り場': ('takushii noriba', 'pangkalan taksi', 'taxi stand'),
    'メーター': ('meetaa', 'argo taksi', 'taxi meter'),
    '領収書': ('ryoushuusho', 'kuitansi', 'receipt'),
    'どのくらい': ('dono kurai', 'berapa lama / seberapa', 'how long / how much'),
    '使えます': ('tsukaemasu', 'bisa dipakai', 'can be used'),
    '入れて': ('irete', 'memasukkan (bentuk -te)', 'insert (te-form)'),
    'いけません': ('ikemasen', 'tidak boleh', 'must not'),
    '一枚': ('ichimai', 'satu lembar', 'one (flat object)'),
    '大阪': ('oosaka', 'Osaka', 'Osaka'),
    '京都': ('kyouto', 'Kyoto', 'Kyoto'),
    '奈良': ('nara', 'Nara', 'Nara'),
    '東京': ('toukyou', 'Tokyo', 'Tokyo'),
    '行き': ('yuki', 'jurusan (ke)', 'bound for'),
    '次の': ('tsugi no', 'berikutnya', 'the next'),
    '乗り換えれば': ('norikaereba', 'kalau ganti kereta', 'if one changes trains'),
    'かかります': ('kakarimasu', 'memerlukan (waktu/biaya)', 'takes (time/money)'),
    '乗れ': ('nore', 'bisa naik (bentuk penghubung)', 'can board (stem)'),
    'なければ': ('nakereba', 'kalau tidak', 'if not'),
    '先': ('saki', 'sebelah sana / ujung', 'beyond / ahead'),
    '二つ目': ('futatsume', 'yang kedua', 'the second one'),
    '右': ('migi', 'kanan', 'right'),
    'ぐらい': ('guirai', 'kira-kira', 'about / roughly'),
    'なぜ': ('naze', 'kenapa (netral)', 'why'),
    'ん': ('n', 'penjelas (variasi dari の)', 'explanatory の (casual)'),
    '座れない': ('suwarenai', 'tidak bisa duduk (biasa)', 'cannot sit (plain)'),
    '次': ('tsugi', 'berikutnya', 'next'),
    '反対': ('hantai', 'kebalikan / arah sebaliknya', 'opposite'),
    'しまいました': ('shimaimashita', 'terlanjur / sudah terjadi', 'ended up doing (regret)'),
    'しまった': ('shimatta', 'terlanjur (biasa, lampau)', 'ended up doing (plain past)'),
    'すれば': ('sureba', 'kalau melakukan', 'if one does'),
    '降りる': ('oriru', 'turun (dari kendaraan, biasa)', 'get off (plain)'),
    '連絡': ('renraku', 'hubungan / kontak', 'contact'),
    '北口': ('kitaguchi', 'gerbang utara', 'north exit'),
    '無くした': ('nakushita', 'menghilangkan (biasa, lampau)', 'lost (plain past)'),
    '歩いて': ('aruite', 'berjalan kaki (bentuk -te)', 'walk (te-form)'),
}, where='t05_transportasi')

SINGLE_WORDS = {
    '乗り遅れました': 'satu kata kerja majemuk terinfleksi, bukan frasa',
    '乗り越しました': 'satu kata kerja majemuk terinfleksi, bukan frasa',
    '間に合います': 'satu predikat tetap (sempat), bukan frasa',
    '間に合いません': 'satu predikat tetap (tidak sempat), bukan frasa',
    '止まりません': 'satu kata kerja negatif, bukan frasa',
    'タクシー乗り場': 'satu kata majemuk (pangkalan taksi)',
    '各駅停車': 'satu kata majemuk (kereta lokal)',
    '券売機': 'satu kata majemuk (mesin tiket)',
    '改札口': 'satu kata majemuk (gerbang tiket)',
    '領収書': 'satu kata (kuitansi)',
    '指定席': 'satu kata majemuk (kursi pesanan)',
    '自由席': 'satu kata majemuk (kursi bebas)',
    '何番線': 'kata tanya utuh (jalur berapa)',
    'どのくらい': 'kata tanya utuh (berapa lama)',
    '真っ直ぐ': 'satu kata keterangan (lurus)',
    '忘れ物': 'satu kata majemuk (barang tertinggal)',
    '座れません': 'satu kata kerja potensial negatif, bukan frasa',
}

FUNCTIONS = {
    'beli_tiket': 'membeli tiket',
    'tanya_tiket_pulang_pergi': 'menanyakan tiket pulang pergi',
    'tanya_jalur': 'menanyakan jalur keberangkatan',
    'tanya_jam_berangkat': 'menanyakan jam keberangkatan',
    'tanya_tujuan_kereta': 'menanyakan kereta ini ke mana',
    'tanya_berhenti': 'menanyakan apakah kereta berhenti di stasiun tertentu',
    'tanya_ganti_kereta': 'menanyakan di mana harus ganti kereta',
    'tanya_waktu_tempuh': 'menanyakan berapa lama perjalanan',
    'tanya_kereta_terakhir': 'menanyakan kereta terakhir',
    'tanya_kursi': 'menanyakan kursi bebas atau pesanan',
    'naik_kereta': 'menanyakan apakah ini kereta yang benar',
    'minta_turun_taksi': 'meminta berhenti di tujuan',
    'arah_taksi': 'memberi arah ke pengemudi taksi',
    'bayar_taksi': 'membayar taksi dan minta kuitansi',
    'tanya_tarif': 'menanyakan perkiraan tarif',
    'keterlambatan': 'menanyakan keterlambatan kereta',
    'kereta_penuh': 'mengeluh kereta penuh',
    'ketinggalan': 'mengatakan ketinggalan kereta',
    'salah_arah': 'menyadari salah arah',
    'lewat_stasiun': 'menyadari melewati stasiun tujuan',
    'barang_tertinggal': 'melaporkan barang tertinggal',
    'tanya_naik_bus': 'menanyakan bus yang benar',
    'bayar_bus': 'membayar di bus',
    'tanya_exit': 'menanyakan jalan keluar',
    'tanya_kartu_ic': 'menanyakan apakah kartu bisa dipakai',
    'naik_sepeda': 'mengeluh tentang sepeda',
    'kemacetan': 'mengeluh macet',
    'antar_jemput': 'menawarkan antar',
}

SENTENCES = [
    sent(
        key='beli_tiket', rel='petugas_stasiun', fn='beli_tiket',
        words=['京都', 'まで', 'の', '切符', 'を', '一枚', 'お願いします', '。'],
        id_t='Saya minta satu tiket ke Kyoto.', en_t='One ticket to Kyoto, please.',
        sit='Membeli tiket di loket', sit_en='Buying a ticket at the counter',
        note='まで menandai tujuan akhir tiket; に tidak dipakai di sini karena yang dibeli adalah tiket ke arah sana.',
        note_en='まで marks the ticket destination; に is not used here because the ticket is for travel toward it.',
    ),
    sent(
        key='tanya_tiket_pulang_pergi', rel='petugas_stasiun', fn='tanya_tiket_pulang_pergi',
        words=['往復', 'の', 'が', '安い', 'です', 'か', '。'],
        id_t='Apakah tiket pulang pergi lebih murah?', en_t='Is a round trip cheaper?',
        sit='Menanyakan tiket pulang pergi vs sekali jalan', sit_en='Comparing round trip with one way',
        note='の が…です membandingkan dua hal; 往復のが安いです berarti yang pulang pergi lebih murah.',
        note_en='の が…です compares two things; 往復のが安いです means the round trip is the cheaper one.',
    ),
    sent(
        key='tanya_jalur', rel='petugas_stasiun', fn='tanya_jalur',
        words=['大阪', '行き', 'は', '何番線', 'です', 'か', '。'],
        id_t='Kereta ke Osaka di jalur berapa?', en_t='Which platform is the Osaka train?',
        sit='Menanyakan jalur di stasiun', sit_en='Asking which platform to use',
        note='行き menempel pada tujuan dan berarti "jurusan"; 行き is dibaca yuki, bukan iki.',
        note_en='行き attaches to a destination and means bound for; it is read yuki, not iki.',
    ),
    sent(
        key='tanya_jam_berangkat', rel='petugas_stasiun', fn='tanya_jam_berangkat',
        words=['次の', '電車', 'は', '何時', 'に', '出発', 'します', 'か', '。'],
        id_t='Kereta berikutnya berangkat jam berapa?', en_t='What time does the next train leave?',
        sit='Menanyakan jam keberangkatan berikutnya', sit_en='Asking when the next departure is',
        note='出発します adalah kata kerja yang memang menyatakan kereta berangkat; 行きます juga dipakai tapi kurang tepat.',
        note_en='出発します is the verb for a departure; 行きます is used too but is less precise.',
    ),
    sent(
        key='tanya_tujuan_kereta', rel='petugas_stasiun', fn='tanya_tujuan_kereta',
        words=['この', '電車', 'は', 'どこ', 'に', '行きます', 'か', '。'],
        id_t='Kereta ini pergi ke mana?', en_t='Where does this train go?',
        sit='Menanyakan tujuan kereta yang sudah ada di peron', sit_en='Asking where a train on the platform is headed',
        note='Menanyakan tujuan kereta yang sudah datang lebih aman daripada menebak dari papannya.',
        note_en='Asking where a train that has already arrived is safer than guessing from the board.',
    ),
    sent(
        key='tanya_berhenti', rel='petugas_stasiun', fn='tanya_berhenti',
        words=['この', '電車', 'は', '奈良', 'に', '止まります', 'か', '。'],
        id_t='Apakah kereta ini berhenti di Nara?', en_t='Does this train stop at Nara?',
        sit='Memastikan kereta berhenti di stasiun tujuan', sit_en='Checking the train stops where you are going',
        note='止まりますか menanyakan perhentian; 着きますか menanyakan apakah kereta berakhir di sana, dan sering dijawab tidak.',
        note_en='止まりますか asks whether it stops; 着きますか asks whether it terminates there, which is often no.',
    ),
    sent(
        key='tanya_ganti_kereta', rel='petugas_stasiun', fn='tanya_ganti_kereta',
        words=['奈良', 'まで', 'は', 'どこ', 'で', '乗り換えれば', 'いい', 'です', 'か', '。'],
        id_t='Ke Nara, sebaiknya ganti kereta di mana?', en_t='Where should I change trains for Nara?',
        sit='Menanyakan tempat ganti kereta', sit_en='Asking where to change trains',
        note='乗り換えればいいですか adalah bentuk meminta saran: "kalau ganti di mana, hasilnya baik".',
        note_en='乗り換えればいいですか asks for advice: if I change where, will it work out.',
    ),
    sent(
        key='tanya_waktu_tempuh', rel='petugas_stasiun', fn='tanya_waktu_tempuh',
        words=['京都', 'まで', 'どのくらい', 'かかります', 'か', '。'],
        id_t='Ke Kyoto berapa lama?', en_t='How long does it take to Kyoto?',
        sit='Menanyakan lama perjalanan', sit_en='Asking how long a journey takes',
        note='どのくらいかかりますか menanyakan perkiraan; 何分ですか menanyakan angka pasti dan terdengar lebih tajam.',
        note_en='どのくらいかかりますか asks for an estimate; 何分ですか demands an exact number and sounds sharper.',
    ),
    sent(
        key='tanya_kereta_terakhir', rel='petugas_stasiun', fn='tanya_kereta_terakhir', long=True,
        words=['終電', 'は', '何時', 'です', 'か', '。', 'それ', 'に', '乗れ', 'なければ', 'タクシー', 'で', '帰ります', '。'],
        id_t='Kereta terakhir jam berapa? Kalau harus naik itu, saya pulang dengan taksi.', en_t='What time is the last train? If I have to take it, I will go home by taxi.',
        sit='Menanyakan kereta terakhir sambil menjelaskan rencana', sit_en='Asking about the last train and explaining the plan',
        note='なければ di sini berarti "kalau tidak… maka", jadi kalimat keduanya terikat pada yang pertama.',
        note_en='なければ here means if I do not, then; the second sentence depends on the first.',
    ),
    sent(
        key='tanya_kursi', rel='petugas_stasiun', fn='tanya_kursi',
        words=['この', '特急', 'は', '自由席', 'です', 'か', '、', '指定席', 'です', 'か', '。'],
        id_t='Ekspres ini kursi bebas atau kursi pesanan?', en_t='Is this express non-reserved or reserved?',
        sit='Menanyakan jenis kursi sebelum naik', sit_en='Checking the seat type before boarding',
        note='Menanyakan keduanya sekaligus dengan か…か menghindari dua kali tanya di loket.',
        note_en='Asking both with か…か avoids a second trip to the counter.',
    ),
    sent(
        key='naik_kereta', rel='petugas_stasiun', fn='naik_kereta',
        words=['すみません', '、', 'これ', 'は', '東京', '行き', 'です', 'か', '。'],
        id_t='Permisi, ini kereta ke Tokyo?', en_t='Excuse me, is this the Tokyo train?',
        sit='Memastikan kereta di peron sudah benar', sit_en='Double-checking the train at the platform',
        note='Banyak kereta berbagi peron, jadi bertanya sebelum naik lebih cepat daripada turun di stasiun yang salah.',
        note_en='Trains often share a platform, so asking before boarding beats getting off at the wrong station.',
    ),
    sent(
        key='minta_turun_taksi', rel='asing', fn='minta_turun_taksi',
        words=['あの', '交差点', 'の', '先', 'で', '止めて', 'ください', '。'],
        id_t='Tolong berhenti setelah persimpangan itu.', en_t='Please stop just past that intersection.',
        sit='Meminta taksi berhenti di titik tertentu', sit_en='Asking a taxi to stop at a specific point',
        note='の先で berarti sedikit melewati; の前で akan berhenti sebelum persimpangan, dan itu berbeda.',
        note_en='の先で means slightly past it; の前で would stop before the intersection, which is different.',
    ),
    sent(
        key='arah_taksi', rel='asing', fn='arah_taksi',
        words=['この', '道', 'を', '真っ直ぐ', '行って', '、', '二つ目', 'の', '信号', 'を', '右', 'に', '曲がって', 'ください', '。'],
        id_t='Jalan lurus di jalan ini, lalu di lampu lalu lintas kedua belok kanan.', en_t='Go straight along this road, then turn right at the second traffic light.',
        sit='Memberi arah kepada pengemudi taksi', sit_en='Giving a taxi driver directions',
        note='二つ目の信号 adalah "lampu kedua"; menghitung dengan 目 adalah cara baku menyebut urutan dalam arah.',
        note_en='二つ目の信号 is the second traffic light; counting with 目 is the standard way to give directions.',
    ),
    sent(
        key='bayar_taksi', rel='asing', fn='bayar_taksi',
        words=['ここ', 'で', '大丈夫', 'です', '。', '領収書', 'を', 'お願いします', '。'],
        id_t='Di sini cukup. Saya minta kuitansinya.', en_t='Here is fine. Could I have a receipt?',
        sit='Membayar taksi dan meminta kuitansi', sit_en='Paying a taxi and asking for a receipt',
        note='領収書 adalah kuitansi resmi untuk penggantian biaya; レシート adalah struk biasa, dan keduanya berbeda.',
        note_en='領収書 is the official receipt used for expense claims; レシート is an ordinary till slip, and they differ.',
    ),
    sent(
        key='tanya_tarif', rel='asing', fn='tanya_tarif',
        words=['駅', 'まで', 'だいたい', 'いくら', 'ぐらい', 'です', 'か', '。'],
        id_t='Ke stasiun kira-kira berapa?', en_t='About how much to the station?',
        sit='Menanyakan perkiraan tarif taksi', sit_en='Asking roughly what a taxi will cost',
        note='いくらぐらい adalah perkiraan; いくらですか menanyakan angka pasti, dan pengemudi taksi sering tidak bisa memastikannya.',
        note_en='いくらぐらい asks for an estimate; いくらですか demands an exact figure a driver often cannot give.',
    ),
    sent(
        key='keterlambatan', rel='petugas_stasiun', fn='keterlambatan',
        words=['すみません', '、', 'この', '電車', 'は', 'なぜ', '遅れて', 'いる', 'ん', 'です', 'か', '。'],
        id_t='Permisi, kenapa kereta ini terlambat?', en_t='Excuse me, why is this train delayed?',
        sit='Menanyakan sebab keterlambatan', sit_en='Asking why a train is late',
        note='んですか menambahkan nada ingin tahu; tanpa ん, pertanyaannya terdengar seperti menyalahkan petugas.',
        note_en='んですか adds a note of wanting to know; without it the question can sound like blaming the staff.',
    ),
    sent(
        key='kereta_penuh', rel='teman', fn='kereta_penuh',
        words=['朝', 'の', '電車', 'は', 'いつも', '満員', 'だ', 'から', '、', '座れない', '。'],
        id_t='Kereta pagi selalu penuh, jadi tidak bisa duduk.', en_t='The morning train is always packed, so I cannot sit.',
        sit='Mengeluh kereta pagi penuh', sit_en='Complaining that the morning train is full',
        note='から di sini menyambungkan keadaan dengan akibatnya, jadi keluhannya terasa beralasan.',
        note_en='から links the state to its consequence, so the complaint sounds reasoned.',
    ),
    sent(
        key='ketinggalan', rel='petugas_stasiun', fn='ketinggalan',
        words=['すみません', '、', '今', 'の', '電車', 'に', '乗り遅れました', '。', '次', 'は', 'いつ', 'です', 'か', '。'],
        id_t='Permisi, saya ketinggalan kereta tadi. Berikutnya jam berapa?', en_t='Excuse me, I missed that train. When is the next one?',
        sit='Ketinggalan kereta dan menanyakan yang berikutnya', sit_en='Missing a train and asking for the next',
        note='乗り遅れました (ketinggalan kereta) adalah kata kerja majemuk yang tidak bisa dipecah menjadi 乗り + 遅れ.',
        note_en='乗り遅れました is a compound verb that cannot be split into 乗り plus 遅れ.',
    ),
    sent(
        key='salah_arah', rel='petugas_stasiun', fn='salah_arah',
        words=['反対', 'の', '電車', 'に', '乗って', 'しまいました', '。', 'どう', 'すれば', 'いい', 'です', 'か', '。'],
        id_t='Saya terlanjur naik kereta arah sebaliknya. Sebaiknya bagaimana?', en_t='I got on the train going the wrong way. What should I do?',
        sit='Menyadari naik kereta arah berlawanan', sit_en='Realising you boarded the train going the other way',
        note='どうすればいいですか adalah bentuk meminta saran yang tepat ketika masalahnya sudah terjadi.',
        note_en='どうすればいいですか asks for advice and is the right form once the problem has already happened.',
    ),
    sent(
        key='lewat_stasiun', rel='petugas_stasiun', fn='lewat_stasiun',
        words=['すみません', '、', '降りる', '駅', 'を', '乗り越しました', '。'],
        id_t='Permisi, saya melewati stasiun tempat saya harus turun.', en_t='Excuse me, I went past the station I needed.',
        sit='Melewati stasiun tujuan', sit_en='Passing the station you meant to get off at',
        note='乗り越す khusus untuk melewati tempat turun; 通り過ぎる juga bisa tapi dipakai lebih luas.',
        note_en='乗り越す is specifically for passing your stop; 通り過ぎる is broader.',
    ),
    sent(
        key='barang_tertinggal', rel='petugas_stasiun', fn='barang_tertinggal', long=True,
        words=['電車', 'に', '鞄', 'を', '忘れて', 'しまった', 'の', 'です', 'が', '、', 'どちら', 'に', '連絡', 'すれば', 'いい', 'です', 'か', '。'],
        id_t='Saya meninggalkan tas di kereta, sebaiknya menghubungi ke mana?', en_t='I left my bag on the train, who should I contact?',
        sit='Melaporkan barang tertinggal di stasiun', sit_en='Reporting something left on a train',
        note='忘れてしまった confesses the mistake; 忘れました saja akan terdengar seperti melaporkan cuaca.',
        note_en='忘れてしまった owns the mistake; 忘れました alone would sound as neutral as reporting the weather.',
    ),
    sent(
        key='tanya_naik_bus', rel='orang_asing', fn='tanya_naik_bus',
        words=['この', 'バス', 'は', '駅', 'の', '前', 'を', '通ります', 'か', '。'],
        id_t='Apakah bus ini melewati depan stasiun?', en_t='Does this bus pass the station?',
        sit='Memastikan bus melewati tempat tujuan', sit_en='Checking a bus goes past your stop',
        note='通りますか menanyakan melewati, bukan berhenti; bus bisa melewati tanpa berhenti di sana.',
        note_en='通りますか asks about passing, not stopping; a bus can pass without stopping there.',
    ),
    sent(
        key='bayar_bus', rel='asing', fn='bayar_bus',
        words=['すみません', '、', '後ろ', 'から', '乗って', '、', '前', 'で', '払います', 'か', '。'],
        id_t='Permisi, naik dari belakang dan bayar di depan?', en_t='Excuse me, do I board at the back and pay at the front?',
        sit='Menanyakan cara naik dan bayar bus', sit_en='Checking how to board and pay on a bus',
        note='Cara naik berbeda antara satu daerah dan lainnya, jadi menanyakannya sekali lebih cepat daripada salah dua kali.',
        note_en='Boarding rules differ by region, so asking once beats getting it wrong twice.',
    ),
    sent(
        key='tanya_exit', rel='petugas_stasiun', fn='tanya_exit',
        words=['北口', 'の', '出口', 'は', 'どちら', 'です', 'か', '。'],
        id_t='Jalan keluar untuk gerbang utara di mana?', en_t='Which way is the north exit?',
        sit='Mencari jalan keluar di stasiun besar', sit_en='Finding an exit in a large station',
        note='Di stasiun besar, menyebut nama gerbang (北口) jauh lebih jelas daripada bertanya 出口 saja.',
        note_en='In a large station, naming the gate (北口) is far clearer than asking for 出口 alone.',
    ),
    sent(
        key='tanya_kartu_ic', rel='petugas_stasiun', fn='tanya_kartu_ic',
        words=['この', 'カード', 'は', 'バス', 'で', 'も', '使えます', 'か', '。'],
        id_t='Apakah kartu ini bisa dipakai di bus juga?', en_t='Can this card be used on buses too?',
        sit='Menanyakan apakah kartu berlaku untuk bus', sit_en='Checking whether a card works on buses',
        note='も menambahkan bus ke kereta yang sudah jelas bisa; tanpanya pertanyaannya terdengar aneh.',
        note_en='も adds buses to the trains already assumed to work; without it the question sounds odd.',
    ),
    sent(
        key='naik_sepeda', rel='teman', fn='naik_sepeda',
        words=['自転車', 'の', '鍵', 'を', '無くした', 'から', '、', '今日', 'は', '歩いて', '行く', '。'],
        id_t='Karena kunci sepeda saya hilang, hari ini saya jalan kaki.', en_t='I lost my bicycle key, so I am walking today.',
        sit='Mengeluh sepeda tidak bisa dipakai', sit_en='Explaining why you are walking today',
        note='無くした adalah bentuk biasa dari 無くしました; ke teman bentuk biasa yang wajar.',
        note_en='無くした is the plain form of 無くしました; plain form is natural with a friend.',
    ),
    sent(
        key='kemacetan', rel='asing', fn='kemacetan',
        words=['この', '時間', 'は', '道', 'が', '混んでいます', 'から', '、', '少し', '時間', 'が', 'かかります', 'よ', '。'],
        id_t='Pada jam ini jalannya ramai, jadi akan agak lama.', en_t='The roads are busy at this hour, so it will take a little longer.',
        sit='Pengemudi memberi tahu akan macet', sit_en='A driver warning that traffic is heavy',
        note='よ di akhir memberi tahu sesuatu yang belum diketahui pendengar; itulah gunanya di sini.',
        note_en='The よ at the end informs the listener of something they did not know, which is exactly its job here.',
    ),
    sent(
        key='antar_jemput', rel='rekan', fn='antar_jemput',
        words=['駅', 'まで', '車', 'で', '送ります', 'よ', '。'],
        id_t='Saya antar ke stasiun dengan mobil.', en_t='I will drive you to the station.',
        sit='Menawarkan mengantar ke stasiun', sit_en='Offering a lift to the station',
        note='送ります di sini mengantar orang, bukan mengirim barang; pelakunya menandai bedanya.',
        note_en='送ります here means to see someone off, not to send a thing; the object tells them apart.',
    ),
]
