#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Arah: asking the way, giving it, and getting lost on purpose.

Directions split into two jobs that a template cannot tell apart: asking (where is it, how do
I get there, is it far, can you draw it) and answering (go straight, turn at the second
light, cross the bridge, it is the building across from the bank). They also need the repair
moves, because the first answer is often too fast: sorry, once more, more slowly, which
landmark. All of those are separate sentences here.
"""
from compose import sent, add_words

add_words({
    'まっすぐ': ('massugu', 'lurus', 'straight'),
    '信号': ('shingou', 'lampu lalu lintas', 'traffic light'),
    '二つ目': ('futatsume', 'yang kedua', 'the second one'),
    '三つ目': ('mittsume', 'yang ketiga', 'the third one'),
    '右': ('migi', 'kanan', 'right'),
    '左': ('hidari', 'kiri', 'left'),
    '橋': ('hashi', 'jembatan', 'bridge'),
    '大通り': ('oodoori', 'jalan besar', 'main street'),
    '坂': ('saka', 'tanjakan', 'slope'),
    '建物': ('tatemono', 'bangunan', 'building'),
    '目印': ('mejirushi', 'penanda / patokan', 'a landmark'),
    '向かい': ('mukai', 'seberang', 'across the way'),
    '向こう': ('mukou', 'sebelah sana', 'the other side'),
    '正面': ('shoumen', 'tepat di depan', 'directly opposite'),
    '裏': ('ura', 'belakang (bangunan)', 'the back of'),
    '脇': ('waki', 'samping', 'beside / to the side'),
    '並び': ('narabi', 'deretan / sebelah', 'in the row next to'),
    '真ん中': ('mannaka', 'tengah', 'the middle'),
    '間': ('aida', 'antara', 'between'),
    '分かれ道': ('wakaremichi', 'persimpangan bercabang', 'a fork in the road'),
    '歩いて': ('aruite', 'berjalan kaki (bentuk -te)', 'walk (te-form)'),
    '歩く': ('aruku', 'berjalan kaki (biasa)', 'walk (plain)'),
    '通る': ('tooru', 'melewati (biasa)', 'pass through (plain)'),
    '曲がる': ('magaru', 'berbelok (biasa)', 'turn (plain)'),
    '渡る': ('wataru', 'menyeberang (biasa)', 'cross (plain)'),
    '着く': ('tsuku', 'tiba (biasa)', 'arrive (plain)'),
    '着きました': ('tsukimashita', 'tiba (lampau sopan)', 'arrived (polite past)'),
    '見えます': ('miemasu', 'terlihat (sopan)', 'is visible (polite)'),
    '見えません': ('miemasen', 'tidak terlihat (sopan)', 'is not visible (polite)'),
    '教えて': ('oshiete', 'memberi tahu (bentuk -te)', 'tell (te-form)'),
    '案内': ('annai', 'pemanduan / penunjukan jalan', 'guidance'),
    '案内します': ('annai shimasu', 'menunjukkan jalan (sopan)', 'guide (polite)'),
    '案内して': ('annai shite', 'menunjukkan jalan (bentuk -te)', 'guide (te-form)'),
    '行き方': ('ikikata', 'cara pergi / cara menuju', 'how to get somewhere'),
    '道順': ('michijun', 'urutan jalan yang dilalui', 'the route'),
    '連れて': ('tsurete', 'membawa (orang, bentuk -te)', 'take (a person) (te-form)'),
    '連れて行って': ('tsurete itte', 'mengajak pergi (permintaan)', 'take me along'),
    '低い': ('hikui', 'rendah', 'low'),
    '白い': ('shiroi', 'putih', 'white'),
    '黒い': ('kuroi', 'hitam', 'black'),
    '赤い': ('akai', 'merah', 'red'),
    '青い': ('aoi', 'biru', 'blue'),
    '角を': ('kado o', 'di sudut (dengan partikel)', 'at the corner (with particle)'),
    'ところ': ('tokoro', 'tempat / bagian', 'place'),
    '目印になります': ('mejirushi ni narimasu', 'menjadi patokan', 'serves as a landmark'),
    'もらえます': ('moraemasu', 'bisa minta (sopan)', 'can receive (polite)'),
    '駅前': ('ekimae', 'depan stasiun', 'in front of the station'),
    'もう一度': ('mou ichido', 'sekali lagi', 'once more'),
    '描いて': ('kaite', 'menggambar (bentuk -te)', 'draw (te-form)'),
    '書いて': ('kaite', 'menulis (bentuk -te)', 'write (te-form)'),
    '迷いました': ('mayoimashita', 'tersesat (lampau sopan)', 'got lost (polite past)'),
    '迷って': ('mayotte', 'tersesat (bentuk -te)', 'get lost (te-form)'),
    '近道': ('chikamichi', 'jalan pintas', 'shortcut'),
    '遠回り': ('toomawari', 'memutar jauh', 'a detour'),
    '着いたら': ('tsuitara', 'kalau sudah tiba', 'once you arrive'),
    '連絡して': ('renraku shite', 'menghubungi (bentuk -te)', 'contact (te-form)'),
    'しまいました': ('shimaimashita', 'terlanjur / sudah terjadi', 'ended up doing (regret)'),
    '行けます': ('ikemasu', 'bisa pergi (sopan)', 'can go (polite)'),
    '歩いたら': ('aruitara', 'kalau berjalan kaki', 'if one walks'),
    'どのくらい': ('dono kurai', 'berapa lama / seberapa', 'how long / how much'),
    'かかります': ('kakarimasu', 'memerlukan (waktu/biaya)', 'takes (time/money)'),
    'もらえない': ('moraenai', 'tidak bisa minta (biasa)', 'cannot get (plain)'),
    '速かった': ('hayakatta', 'cepat (biasa, lampau)', 'was fast (plain past)'),
    'つまり': ('tsumari', 'jadi / dengan kata lain', 'in other words'),
    '曲がれば': ('magareba', 'kalau berbelok', 'if one turns'),
    'ん': ('n', 'penjelas (variasi dari の)', 'explanatory の (casual)'),
    '十分': ('juppun', 'sepuluh menit', 'ten minutes'),
    'ぐらい': ('guirai', 'kira-kira', 'about / roughly'),
    '三階': ('sangai', 'lantai tiga', 'third floor'),
    '渡ったら': ('watattara', 'kalau sudah menyeberang', 'once one crosses'),
    '分かりにくい': ('wakarini kui', 'sulit dimengerti', 'hard to understand'),
    'つもり': ('tsumori', 'niat / anggapan', 'intention'),
    '全然': ('zenzen', 'sama sekali (dengan negatif)', 'not at all (with a negative)'),
    '違う': ('chigau', 'berbeda / salah (biasa)', 'different / wrong (plain)'),
    '方向': ('houkou', 'arah', 'direction'),
    'いた': ('ita', 'ada / sedang (biasa, lampau)', 'was (plain past)'),
    '逆': ('gyaku', 'kebalikan', 'the reverse'),
    'ほう': ('hou', 'yang (dalam perbandingan)', 'the one (in a comparison)'),
    '見える': ('mieru', 'terlihat (biasa)', 'is visible (plain)'),
    'ら': ('ra', 'kalau (kondisional)', 'if (conditional)'),
    'パン屋': ('pan-ya', 'toko roti', 'bakery'),
    'さん': ('san', 'Pak/Bu (sebutan sopan)', 'Mr/Ms (polite suffix)'),
    '上がったら': ('agattara', 'kalau sudah naik', 'once one goes up'),
    '助かりました': ('tasukarimashita', 'sangat terbantu (lampau sopan)', 'was a great help'),
    'こっち': ('kocchi', 'sebelah sini (akrab)', 'this way (casual)'),
}, where='t06_arah')

SINGLE_WORDS = {
    '分かれ道': 'satu kata majemuk (percabangan jalan)',
    '目印になります': 'satu predikat tetap, bukan frasa bebas',
    '連れて行って': 'permintaan utuh (ajak pergi), bukan frasa bebas',
    '案内します': 'satu kata kerja majemuk (menunjukkan jalan)',
    '行き方': 'satu kata majemuk (cara menuju)',
    '道順': 'satu kata majemuk (urutan jalan)',
    '着きました': 'satu kata kerja terinfleksi, bukan frasa',
    '分かりました': 'satu kata kerja terinfleksi, bukan frasa',
    '分かりません': 'satu kata kerja terinfleksi, bukan frasa',
    'もう一度': 'ungkapan tetap (sekali lagi)',
    '駅前': 'satu kata majemuk (depan stasiun)',
    '見えません': 'satu kata kerja negatif, bukan frasa',
}

FUNCTIONS = {
    'tanya_letak_sopan': 'menanyakan letak tempat dengan sopan',
    'tanya_letak_jalan': 'menanyakan letak saat benar-benar tersesat',
    'tanya_cara_menuju': 'menanyakan cara menuju suatu tempat',
    'tanya_jauh_dekat': 'menanyakan jauh atau dekat',
    'tanya_jalan_kaki': 'menanyakan bisa jalan kaki atau tidak',
    'tanya_waktu_jalan': 'menanyakan berapa lama di jalan',
    'minta_tunjukkan_peta': 'meminta ditunjukkan di peta',
    'minta_gambar': 'meminta digambarkan',
    'minta_antar': 'meminta diantar ke tempat tujuan',
    'ulangi_alamat': 'meminta diulang karena terlalu cepat',
    'konfirmasi_paham': 'menyatakan sudah paham',
    'jawab_lurus': 'menjawab dengan lurus',
    'jawab_belok': 'menjawab dengan berbelok di lampu',
    'jawab_seberang': 'menjawab letak di seberang',
    'jawab_antara': 'menjawab letak di antara dua bangunan',
    'jawab_patokan': 'menyebutkan patokan bangunan',
    'jawab_jalan_kaki': 'menjawab bahwa bisa jalan kaki',
    'jawab_lantai': 'menjawab letak di dalam gedung',
    'beri_arah_jalan': 'memberi arah jalan yang lebih panjang',
    'pakai_google_maps': 'menyarankan memakai peta ponsel',
    'nyasar': 'mengatakan sudah tersesat',
    'balik_arah': 'mengatakan arahnya kebalik',
    'sudah_dekat': 'mengatakan sudah hampir sampai',
    'sampai_tujuan': 'memberi tahu sudah sampai',
    'patokan_menuju_rumah': 'menjelaskan patokan menuju rumah',
    'tanya_bangunan_tinggi': 'menanyakan bangunan yang terlihat',
    'terima_kasih_arah': 'berterima kasih setelah ditunjukkan jalan',
    'tawar_jalan_pintas': 'menawarkan jalan pintas',
}

SENTENCES = [
    sent(
        key='tanya_letak_sopan', rel='orang_asing', fn='tanya_letak_sopan',
        words=['すみません', '、', '郵便局', 'は', 'どちら', 'です', 'か', '。'],
        id_t='Permisi, kantor posnya di mana?', en_t='Excuse me, which way is the post office?',
        sit='Menanyakan letak tempat kepada orang di jalan', sit_en='Asking a passer-by for a location',
        note='どちらですか adalah bentuk sopan dari どこですか, dan ke orang asing inilah yang dipakai.',
        note_en='どちらですか is the polite form of どこですか and is the one to use with a stranger.',
    ),
    sent(
        key='tanya_letak_jalan', rel='orang_asing', fn='tanya_letak_jalan',
        words=['すみません', '、', '道', 'に', '迷って', 'しまいました', '。', '駅', 'は', 'どこ', 'です', 'か', '。'],
        id_t='Permisi, saya tersesat. Stasiunnya di mana?', en_t='Excuse me, I am lost. Where is the station?',
        sit='Benar-benar tersesat dan menanyakan arah', sit_en='Genuinely lost and asking the way',
        note='Mengaku 迷ってしまいました lebih dulu membuat orang berhenti dan menjelaskan dengan sabar.',
        note_en='Admitting 迷ってしまいました first makes people stop and explain patiently.',
    ),
    sent(
        key='tanya_cara_menuju', rel='orang_asing', fn='tanya_cara_menuju',
        words=['駅', 'まで', 'の', '行き方', 'を', '教えて', 'もらえます', 'か', '。'],
        id_t='Boleh Anda tunjukkan cara ke stasiun?', en_t='Could you tell me how to get to the station?',
        sit='Meminta penjelasan cara menuju tempat', sit_en='Asking for directions in detail',
        note='行き方を教えてもらえますか meminta cara; どこですか hanya meminta letak, tanpa arah.',
        note_en='行き方を教えてもらえますか asks for the way; どこですか only asks the location, without directions.',
    ),
    sent(
        key='tanya_jauh_dekat', rel='orang_asing', fn='tanya_jauh_dekat',
        words=['ここ', 'から', '遠い', 'です', 'か', '。'],
        id_t='Dari sini jauh?', en_t='Is it far from here?',
        sit='Menanyakan jarak dari tempat berdiri', sit_en='Asking how far it is from where you stand',
        note='から menandai titik awal; tanpa ここから pertanyaannya tidak jelas diukur dari mana.',
        note_en='から marks the starting point; without ここから it is unclear what the distance is measured from.',
    ),
    sent(
        key='tanya_jalan_kaki', rel='orang_asing', fn='tanya_jalan_kaki',
        words=['歩いて', '行けます', 'か', '。'],
        id_t='Bisa jalan kaki?', en_t='Can I walk there?',
        sit='Menanyakan apakah tujuan terjangkau dengan jalan kaki', sit_en='Asking whether the destination is walkable',
        note='行けます adalah bentuk potensial dari 行きます; yang ditanyakan kemampuan, bukan izin.',
        note_en='行けます is the potential form of 行きます; it asks about possibility, not permission.',
    ),
    sent(
        key='tanya_waktu_jalan', rel='orang_asing', fn='tanya_waktu_jalan',
        words=['歩いたら', 'どのくらい', 'かかります', 'か', '。'],
        id_t='Kalau jalan kaki, berapa lama?', en_t='How long does it take on foot?',
        sit='Menanyakan lama perjalanan dengan jalan kaki', sit_en='Asking how long the walk takes',
        note='歩いたら menjadikan jalan kaki sebagai syarat; 歩くと akan terdengar seperti kebiasaan.',
        note_en='歩いたら makes walking the condition; 歩くと would sound like a habitual statement.',
    ),
    sent(
        key='minta_tunjukkan_peta', rel='orang_asing', fn='minta_tunjukkan_peta',
        words=['すみません', '、', 'この', '地図', 'で', 'どこ', 'です', 'か', '。'],
        id_t='Permisi, di peta ini yang mana?', en_t='Excuse me, where is it on this map?',
        sit='Menunjukkan peta untuk mencari tempat', sit_en='Showing a map to locate a place',
        note='Menunjuk peta sering lebih cepat daripada mendengarkan arah, terutama bila bahasanya belum lancar.',
        note_en='Pointing at a map is often faster than listening to directions, especially with limited language.',
    ),
    sent(
        key='minta_gambar', rel='orang_asing', fn='minta_gambar',
        words=['すみません', '、', 'ここ', 'から', 'の', '道順', 'を', '書いて', 'もらえます', 'か', '。'],
        id_t='Permisi, boleh dituliskan rutenya dari sini?', en_t='Excuse me, could you write down the route from here?',
        sit='Meminta rute dituliskan', sit_en='Asking for the route to be written down',
        note='書いてもらえますか meminta tulisan, bukan ucapan; ini yang paling menolong kalau arahnya panjang.',
        note_en='書いてもらえますか asks for writing rather than speech, which helps most when the route is long.',
    ),
    sent(
        key='minta_antar', rel='teman', fn='minta_antar',
        words=['悪い', 'けど', '、', '駅', 'まで', '連れて', '行って', 'もらえない', '？'],
        id_t='Maaf ya, boleh antar saya ke stasiun?', en_t='Sorry, could you take me to the station?',
        sit='Meminta diantar ke stasiun ke teman', sit_en='Asking a friend for a lift to the station',
        note='もらえない？ adalah bentuk negatif-interogatif yang membuat permintaan terasa tidak menuntut.',
        note_en='もらえない？ is the negative question form, which makes a request sound less demanding.',
    ),
    sent(
        key='ulangi_alamat', rel='orang_asing', fn='ulangi_alamat', long=True,
        words=['すみません', '、', 'ちょっと', '速かった', 'ので', '、', 'もう一度', 'ゆっくり', 'お願いします', '。'],
        id_t='Permisi, tadi agak cepat, tolong sekali lagi pelan-pelan.', en_t='Sorry, that was a bit fast, once more slowly please.',
        sit='Meminta arah diulang dengan lebih pelan', sit_en='Asking for directions to be repeated more slowly',
        note='ので menyampaikan alasannya sebelum permintaan, jadi tidak terdengar seperti menyalahkan.',
        note_en='ので gives the reason before the request, so it does not sound like a complaint.',
    ),
    sent(
        key='konfirmasi_paham', rel='orang_asing', fn='konfirmasi_paham', long=True,
        words=['分かりました', '。', 'つまり', '、', 'あの', '信号', 'を', '右', 'に', '曲がれば', 'いい', 'ん', 'です', 'ね', '。'],
        id_t='Saya mengerti. Jadi, saya belok kanan di lampu itu, begitu?', en_t='I understand. So I turn right at that traffic light, right?',
        sit='Mengulang arah untuk memastikan paham', sit_en='Repeating directions back to be sure',
        note='つまり…ばいいんですね mengulang arah sebagai pertanyaan; ini cara paling cepat menemukan salah paham.',
        note_en='つまり…ばいいんですね repeats the route as a question, which is the fastest way to catch a misunderstanding.',
    ),
    sent(
        key='jawab_lurus', rel='orang_asing', fn='jawab_lurus',
        words=['この', '道', 'を', 'まっすぐ', '行って', 'ください', '。'],
        id_t='Lurus saja di jalan ini.', en_t='Go straight along this road.',
        sit='Menunjukkan arah lurus', sit_en='Giving a straight-ahead answer',
        note='まっすぐ ditulis dengan kanji 真っ直ぐ, tapi dalam arah jalan orang lebih sering mendengarnya sebagai まっすぐ.',
        note_en='まっすぐ is written 真っ直ぐ in kanji, but on the street people hear it as まっすぐ.',
    ),
    sent(
        key='jawab_belok', rel='orang_asing', fn='jawab_belok',
        words=['二つ目', 'の', '信号', 'を', '左', 'に', '曲がって', 'ください', '。'],
        id_t='Belok kiri di lampu kedua.', en_t='Turn left at the second traffic light.',
        sit='Menunjukkan arah dengan hitungan lampu', sit_en='Directing by counting traffic lights',
        note='二つ目の信号 menghitung lampu yang dilewati; menyebut nama jalan jarang dipakai di Jepang kecuali jalan besar.',
        note_en='二つ目の信号 counts the lights you pass; street names are rarely used in Japan except on major roads.',
    ),
    sent(
        key='jawab_seberang', rel='orang_asing', fn='jawab_seberang',
        words=['銀行', 'の', '向かい', 'に', 'あります', '。'],
        id_t='Ada di seberang bank.', en_t='It is across from the bank.',
        sit='Menjelaskan letak relatif terhadap bangunan lain', sit_en='Placing a location relative to a landmark',
        note='向かい berarti tepat di seberang jalan; 向こう berarti lebih jauh dan kurang tepat posisinya.',
        note_en='向かい means directly across the road; 向こう is further away and less precise.',
    ),
    sent(
        key='jawab_antara', rel='orang_asing', fn='jawab_antara',
        words=['コンビニ', 'と', '薬局', 'の', '間', 'に', 'あります', '。'],
        id_t='Ada di antara minimarket dan apotek.', en_t='It is between the convenience store and the pharmacy.',
        sit='Menjelaskan letak di antara dua bangunan', sit_en='Placing a location between two buildings',
        note='A と B の間 menandai dua sisi; kalau hanya satu patokan yang disebut, pakai の隣 atau の並び.',
        note_en='A と B の間 needs two sides; with only one landmark, use の隣 or の並び.',
    ),
    sent(
        key='jawab_patokan', rel='orang_asing', fn='jawab_patokan',
        words=['白い', '大きい', '建物', 'が', '目印', 'に', 'なります', '。'],
        id_t='Bangunan putih besar itu jadi patokannya.', en_t='The big white building is the landmark.',
        sit='Menyebut patokan bangunan', sit_en='Naming a landmark to look for',
        note='Menyebut warna dan ukuran bersama-sama lebih mudah dikenali daripada nama bangunan yang mungkin tidak terbaca.',
        note_en='Colour and size together are easier to spot than a building name that may not be readable.',
    ),
    sent(
        key='jawab_jalan_kaki', rel='orang_asing', fn='jawab_jalan_kaki',
        words=['歩いて', '十分', 'ぐらい', 'です', 'よ', '。'],
        id_t='Sekitar sepuluh menit jalan kaki.', en_t='About ten minutes on foot.',
        note='よ di akhir memberi tahu sesuatu yang belum diketahui penanya, jadi terdengar menolong bukan menggurui.',
        note_en='The よ at the end informs the asker of something they did not know, so it sounds helpful rather than preachy.',
        sit='Menjawab jarak dengan waktu tempuh', sit_en='Answering distance with walking time',
    ),
    sent(
        key='jawab_lantai', rel='petugas_toko', fn='jawab_lantai',
        words=['三階', 'の', '受付', 'で', 'お願いします', '。'],
        id_t='Silakan di resepsionis lantai tiga.', en_t='Please go to the reception on the third floor.',
        sit='Menunjukkan letak di dalam gedung', sit_en='Directing someone inside a building',
        note='階 dihitung dengan angka Cina: 三階, 四階. Di dalam gedung, lantai jauh lebih menolong daripada arah mata angin.',
        note_en='Floors use the Chinese numerals: 三階, 四階. Inside a building a floor is more useful than a compass direction.',
    ),
    sent(
        key='beri_arah_jalan', rel='orang_asing', fn='beri_arah_jalan', long=True,
        words=['この', '大通り', 'を', 'まっすぐ', '行って', '、', '橋', 'を', '渡ったら', '右', 'です', '。'],
        id_t='Lurus di jalan besar ini, lalu setelah menyeberangi jembatan, di kanan.', en_t='Go straight along this main street, and after you cross the bridge it is on the right.',
        sit='Memberi arah panjang dengan patokan', sit_en='Giving long directions using a landmark',
        note='渡ったら (kalau sudah menyeberang) membuat urutannya jelas: jembatan dulu, belok kemudian.',
        note_en='渡ったら (once you have crossed) fixes the order: bridge first, turn after.',
    ),
    sent(
        key='pakai_google_maps', rel='orang_asing', fn='pakai_google_maps',
        words=['この', '道', 'は', '分かりにくい', 'から', '、', '地図', 'の', 'ほう', 'が', '早い', 'です', 'よ', '。'],
        id_t='Jalan ini membingungkan, jadi peta lebih cepat.', en_t='This street is confusing, so a map will be quicker.',
        sit='Menyarankan memakai peta ponsel', sit_en='Suggesting a phone map instead',
        note='ほう が早いです membandingkan dua cara; ini bentuk saran yang jujur tanpa menyinggung kemampuan pendengar.',
        note_en='ほう が早いです compares two options; it advises honestly without implying the listener cannot follow.',
    ),
    sent(
        key='nyasar', rel='teman', fn='nyasar',
        words=['駅', 'に', '着いた', 'つもり', 'だった', 'けど', '、', '全然', '違う', '方向', 'に', '歩いて', 'いた', '。'],
        id_t='Saya pikir sudah sampai stasiun, ternyata saya jalan ke arah yang sama sekali salah.', en_t='I thought I had reached the station, but I had been walking the wrong way entirely.',
        sit='Menceritakan sudah tersesat jauh', sit_en='Telling a friend you got badly lost',
        note='つもりだった menyatakan keyakinan yang ternyata salah; 思った juga bisa, tapi つもり lebih menegaskan kesalahan niat.',
        note_en='つもりだった states a belief that turned out false; 思った works too, but つもり stresses the mistaken intention.',
    ),
    sent(
        key='balik_arah', rel='teman', fn='balik_arah',
        words=['逆', 'だ', 'よ', '。', '反対', 'の', 'ホーム', 'に', '行った', 'ほう', 'が', 'いい', '。'],
        id_t='Kebalik. Sebaiknya ke peron seberang.', en_t='You are going the wrong way. Better head to the opposite platform.',
        sit='Memberi tahu arah teman yang kebalik', sit_en='Telling a friend they are going the wrong way',
        note='ほう がいい adalah bentuk saran lunak: "yang lebih baik adalah". Perintah langsung justru terasa kasar ke teman.',
        note_en='ほう がいい is soft advice: the better option is. A direct command sounds blunt even to a friend.',
    ),
    sent(
        key='sudah_dekat', rel='teman', fn='sudah_dekat',
        words=['もう', 'すぐ', 'そこ', 'だ', 'よ', '。', 'あの', '角', 'を', '曲がれば', '見える', '。'],
        id_t='Sudah dekat, di situ. Kalau belok di sudut itu kelihatan.', en_t='Almost there. Once you turn that corner you will see it.',
        sit='Menghibur teman yang hampir sampai', sit_en='Reassuring a friend who is nearly there',
        note='曲がれば見える memakai bentuk bersyarat berpasangan; ini pola arah yang menenangkan karena memberi titik akhir.',
        note_en='曲がれば見える pairs a conditional with its result, which reassures by naming the end point.',
    ),
    sent(
        key='sampai_tujuan', rel='teman', fn='sampai_tujuan',
        words=['着いた', 'ら', '連絡して', '。'],
        id_t='Kalau sudah sampai, hubungi saya.', en_t='Let me know when you arrive.',
        sit='Meminta kabar setelah tiba', sit_en='Asking to be told when someone arrives',
        note='着いたら ditulis dengan kanji, tapi bentuk kasualnya sering keluar sebagai 着いたら saja tanpa partikel tambahan.',
        note_en='着いたら uses kanji, but casually it comes out just as 着いたら with no extra particle.',
    ),
    sent(
        key='patokan_menuju_rumah', rel='teman', fn='patokan_menuju_rumah', long=True,
        words=['駅', 'の', '前', 'の', 'パン屋', 'さん', 'を', '右', 'に', '見て', '、', '坂', 'を', '上がったら', '家', 'だ', 'よ', '。'],
        id_t='Dari toko roti di depan stasiun, lihat ke kanan, naik tanjakannya, itu rumah saya.', en_t='From the bakery in front of the station, keep it on your right, go up the slope, and that is my house.',
        sit='Menjelaskan patokan menuju rumah', sit_en='Describing the way to your house',
        note='上がったら (kalau sudah naik) menutup rangkaian arah; だ よ menutupnya sebagai ajakan akrab, bukan pengumuman.',
        note_en='上がったら (once you have gone up) closes the route; だ よ closes it as a friendly statement rather than an announcement.',
    ),
    sent(
        key='tanya_bangunan_tinggi', rel='orang_asing', fn='tanya_bangunan_tinggi',
        words=['あの', '高い', '建物', 'は', '何', 'です', 'か', '。'],
        id_t='Bangunan tinggi itu apa?', en_t='What is that tall building?',
        sit='Menanyakan bangunan yang menjadi patokan', sit_en='Asking about a landmark building',
        note='Mengenal patokan bangunan membuat arah yang dijelaskan orang lain langsung bisa dipakai.',
        note_en='Knowing the landmarks makes directions someone gave you immediately usable.',
    ),
    sent(
        key='terima_kasih_arah', rel='orang_asing', fn='terima_kasih_arah',
        words=['ありがとうございます', '。', 'とても', '助かりました', '。'],
        id_t='Terima kasih. Sangat membantu.', en_t='Thank you. That was a great help.',
        sit='Berterima kasih setelah ditunjukkan jalan', sit_en='Thanking someone for directions',
        note='助かりました menyebut manfaatnya, jadi bukan sekadar sopan tapi menjelaskan kenapa berterima kasih.',
        note_en='助かりました names the benefit, so it is not just polite but explains why thanks are due.',
    ),
    sent(
        key='tawar_jalan_pintas', rel='teman', fn='tawar_jalan_pintas',
        words=['あの', '道', 'は', '遠回り', 'だ', 'から', '、', 'こっち', 'の', '近道', 'を', '行こう', '。'],
        id_t='Jalan itu memutar jauh, kita lewat jalan pintas ini saja.', en_t='That road is a long way round, let us take this shortcut.',
        sit='Menawarkan jalan pintas kepada teman', sit_en='Offering a shortcut to a friend',
        note='行こう adalah ajakan bentuk biasa; ke atasan bentuk ini harus berubah menjadi 行きましょう.',
        note_en='行こう is a plain invitation; with a superior it would have to become 行きましょう.',
    ),
]
