#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Cuaca: the most reliable small talk in Japan, and the one topic with a real social cost.

Weather talk is how Japanese conversation opens with neighbours, colleagues and strangers,
and it is also the topic where being wrong has consequences: you leave without an umbrella,
you hang washing out before a typhoon, you fail to warn a guest that the trains stop. So the
functions cover small talk (nice weather, isn't it), a real forecast (probability, temperature,
tomorrow), the seasonal markers everyone actually says (tsuyu, humidity, the first cold day),
and the practical instructions that go with them (take an umbrella, bring the washing in,
close the windows).
"""
from compose import sent, add_words

add_words({
    '晴れ': ('hare', 'cerah', 'clear weather'),
    '曇り': ('kumori', 'berawan', 'cloudy'),
    '晴れる': ('hareru', 'menjadi cerah (biasa)', 'clear up (plain)'),
    '曇る': ('kumoru', 'menjadi berawan (biasa)', 'cloud over (plain)'),
    '降る': ('furu', 'turun (hujan/salju, biasa)', 'fall (rain/snow, plain)'),
    '降っています': ('futte imasu', 'sedang turun (hujan)', 'is falling (rain)'),
    '止みました': ('yamimashita', 'berhenti (hujan, lampau)', 'stopped (rain, past)'),
    '涼しい': ('suzushii', 'sejuk', 'cool (pleasant)'),
    '暖かい': ('atatakai', 'hangat', 'warm'),
    '湿度': ('shitsudo', 'kelembapan', 'humidity'),
    '湿気': ('shikke', 'lembap / kelembapan udara', 'dampness'),
    '乾燥': ('kansou', 'kering (udara)', 'dryness'),
    '梅雨': ('tsuyu', 'musim hujan', 'rainy season'),
    '雷': ('kaminari', 'petir / guntur', 'thunder / lightning'),
    '強風': ('kyoufuu', 'angin kencang', 'strong wind'),
    '虹': ('niji', 'pelangi', 'rainbow'),
    '気温': ('kion', 'suhu udara', 'temperature'),
    '度': ('do', 'derajat', 'degrees'),
    '予報': ('yohou', 'ramalan', 'forecast'),
    '降水確率': ('kousui kakuritsu', 'peluang hujan', 'chance of rain'),
    '中止': ('chuushi', 'dibatalkan', 'cancelled'),
    '洗濯物': ('sentakumono', 'cucian', 'the washing'),
    '干して': ('hoshite', 'menjemur (bentuk -te)', 'hang out to dry (te-form)'),
    '取り込んで': ('torikonde', 'mengangkat masuk (bentuk -te)', 'bring in (te-form)'),
    '濡れて': ('nurete', 'basah (bentuk -te)', 'get wet (te-form)'),
    '閉めて': ('shimete', 'menutup (bentuk -te)', 'close (te-form)'),
    '吹く': ('fuku', 'bertiup (biasa)', 'blow (plain)'),
    '急に': ('kyuu ni', 'tiba-tiba', 'suddenly'),
    'だんだん': ('dandan', 'lama-lama / berangsur', 'gradually'),
    '上着': ('uwagi', 'jaket / baju luar', 'jacket'),
    '半袖': ('hansode', 'lengan pendek', 'short sleeves'),
    'マフラー': ('mafuraa', 'syal', 'scarf'),
    '日傘': ('higasa', 'payung matahari', 'parasol'),
    '水分': ('suibun', 'cairan / air', 'fluids'),
    '熱中症': ('necchuu shou', 'serangan panas', 'heatstroke'),
    '日焼け': ('hiyake', 'terbakar matahari', 'sunburn'),
    '眺め': ('nagame', 'pemandangan', 'the view'),
    '変わりやすい': ('kawariyasui', 'mudah berubah', 'changeable'),
    '晴れそう': ('haresou', 'kelihatannya akan cerah', 'looks like it will clear'),
    '降りそう': ('furisou', 'kelihatannya akan hujan', 'looks like rain'),
    '上がります': ('agarimasu', 'naik (sopan)', 'rises (polite)'),
    '下がります': ('sagarimasu', 'turun (sopan)', 'falls (polite)'),
    '過ごしやすい': ('sugoshii yasui', 'enak untuk dilewati (cuaca)', 'comfortable (weather)'),
    'らしい': ('rashii', 'sepertinya / khas', 'seems / typical of'),
    'らしいです': ('rashii desu', 'kabarnya / sepertinya', 'apparently'),
    'かないません': ('kanaimasen', 'tidak bisa menang / kalah', 'cannot compete with'),
    'ほう': ('hou', 'yang (dalam perbandingan)', 'the one (in a comparison)'),
    'なって': ('natte', 'menjadi (bentuk -te)', 'become (te-form)'),
    'きました': ('kimashita', 'datang (lampau sopan)', 'came (polite past)'),
    'みたい': ('mitai', 'seperti / kelihatannya', 'looks like'),
    'ぐずついた': ('guzutsuita', 'tidak stabil (cuaca)', 'unsettled (weather)'),
    '空': ('sora', 'langit', 'sky'),
    '雲': ('kumo', 'awan', 'cloud'),
    '晴れの日': ('hare no hi', 'hari cerah', 'a sunny day'),
    '毎年': ('maitoshi', 'setiap tahun', 'every year'),
    '例年': ('reinen', 'seperti tahun-tahun biasanya', 'as in an average year'),
    '続きます': ('tsuzukimasu', 'berlanjut (sopan)', 'continues (polite)'),
    '影響': ('eikyou', 'dampak / pengaruh', 'effect / impact'),
    '止まる': ('tomaru', 'berhenti (biasa)', 'stop (plain)'),
    '午後': ('gogo', 'siang/sore (PM)', 'afternoon (PM)'),
    'いった': ('itta', 'pergi (biasa, lampau)', 'went (plain past)'),
    '一日': ('ichinichi', 'sepanjang hari', 'all day'),
    '外': ('soto', 'luar', 'outside'),
    'おいて': ('oite', 'melakukan dulu (bentuk -te)', 'do in advance (te-form)'),
    '思った': ('omotta', 'menyangka (biasa, lampau)', 'thought (plain past)'),
    '一枚': ('ichimai', 'satu lembar', 'one (flat object)'),
    '取って': ('totte', 'mengambil (bentuk -te)', 'take (te-form)'),
    '暗い': ('kurai', 'gelap', 'dark'),
    'ら': ('ra', 'kalau (kondisional)', 'if (conditional)'),
    'しすぎて': ('shisugite', 'melakukan berlebihan (bentuk -te)', 'did too much (te-form)'),
    '腕': ('ude', 'lengan', 'arm'),
    'きれい': ('kirei', 'indah / bersih', 'beautiful / clean'),
    '見えた': ('mieta', 'terlihat (biasa, lampau)', 'was visible (plain past)'),
    '止まって': ('tomatte', 'berhenti (bentuk -te)', 'stop (te-form)'),
    'しよう': ('shiyou', 'ayo lakukan (biasa)', 'let us do (plain)'),
    'きませんでした': ('kimasen deshita', 'tidak datang (sopan, lampau)', 'did not come (polite past)'),
    '教えて': ('oshiete', 'memberi tahu (bentuk -te)', 'tell (te-form)'),
    'くれて': ('kurete', 'memberi untuk saya (bentuk -te)', 'do for me (te-form)'),
    'ございます': ('gozaimasu', 'bentuk sopan dari adalah/ada', 'polite copula suffix'),
    '出かけます': ('dekakemasu', 'keluar rumah (sopan)', 'go out (polite)'),
    'ずっと': ('zutto', 'jauh lebih / terus', 'much more / all along'),
    'こんな': ('konna', 'seperti ini', 'this kind of'),
    '夏': ('natsu', 'musim panas', 'summer'),
    '初めて': ('hajimete', 'pertama kali', 'for the first time'),
    '秋': ('aki', 'musim gugur', 'autumn'),
    '冬': ('fuyu', 'musim dingin', 'winter'),
    '痛く': ('itaku', 'sakit (bentuk -ku)', 'painfully (adverbial)'),
    'なりやすい': ('nariyasui', 'cenderung menjadi', 'tends to become'),
    '乾きません': ('kawakimasen', 'tidak kering (sopan)', 'does not dry (polite)'),
    '乾燥': ('kansou', 'kering (udara)', 'dryness'),
    '終わります': ('owarimasu', 'berakhir (sopan)', 'ends (polite)'),
    '近づいて': ('chikazuite', 'mendekat (bentuk -te)', 'approach (te-form)'),
    '取って': ('totte', 'mengambil (bentuk -te)', 'take (te-form)'),
    'しすぎて': ('shisugite', 'melakukan berlebihan (bentuk -te)', 'did too much (te-form)'),
    '曇って': ('kumotte', 'berawan (bentuk -te)', 'cloud over (te-form)'),
    '降って': ('futte', 'turun (bentuk -te)', 'fall (te-form)'),
    'あっ': ('a', 'oh / aduh', 'oh / ah'),
    'さっき': ('sakki', 'tadi (baru saja)', 'a moment ago'),
    'いた': ('ita', 'ada / sedang (biasa, lampau)', 'was (plain past)'),
    'どのくらい': ('dono kurai', 'berapa lama / seberapa', 'how long / how much'),
    '何度': ('nando', 'berapa derajat', 'what temperature'),
    'ぐらい': ('guirai', 'kira-kira', 'about / roughly'),
    '寒かった': ('samukatta', 'dingin (biasa, lampau)', 'was cold (plain past)'),
    '涼しく': ('suzushiku', 'sejuk (bentuk -ku)', 'coolly (adverbial)'),
    '全然': ('zenzen', 'sama sekali (dengan negatif)', 'not at all (with a negative)'),
    '強い': ('tsuyoi', 'kuat', 'strong'),
    'きた': ('kita', 'datang (biasa, lampau)', 'came (plain past)'),
    '洗濯': ('sentaku', 'mencuci (pakaian)', 'laundry'),
    '本当': ('hontou', 'benar / sungguh', 'really / true'),
    '晴れて': ('harete', 'cerah (bentuk -te)', 'clear (te-form)'),
}, where='t07_cuaca')

SINGLE_WORDS = {
    '降水確率': 'satu kata majemuk (peluang hujan)',
    '洗濯物': 'satu kata majemuk (cucian)',
    '熱中症': 'satu kata majemuk (serangan panas)',
    '取り込んで': 'satu kata kerja majemuk (mengangkat masuk)',
    '変わりやすい': 'satu kata sifat majemuk (mudah berubah)',
    '過ごしやすい': 'satu kata sifat majemuk (nyaman dilewati)',
    '晴れそう': 'satu predikat dugaan, bukan frasa bebas',
    '降りそう': 'satu predikat dugaan, bukan frasa bebas',
    'らしいです': 'satu bentuk dugaan sopan, bukan frasa bebas',
    '晴れの日': 'ungkapan tetap (hari cerah)',
    'かな': 'partikel akhir kalimat, satu kata',
    'みたい': 'bentuk dugaan, satu kata',
}

SET_PHRASES = {
    'sapa_cuaca': 'いい天気ですね adalah sapaan cuaca baku tanpa predikat です',
}

FUNCTIONS = {
    'sapa_cuaca': 'menyapa dengan membicarakan cuaca',
    'setuju_cuaca': 'menyetujui ucapan cuaca lawan bicara',
    'tanya_cuaca_besok': 'menanyakan cuaca besok',
    'bilang_cerah': 'mengatakan hari ini cerah',
    'bilang_berawan': 'mengatakan hari ini berawan',
    'bilang_hujan': 'mengatakan sedang hujan',
    'bilang_hujan_berhenti': 'mengatakan hujan sudah berhenti',
    'tanya_peluang_hujan': 'menanyakan peluang hujan',
    'tanya_suhu': 'menanyakan suhu hari ini',
    'bilang_panas': 'mengatakan cuaca panas',
    'bilang_dingin': 'mengatakan cuaca dingin',
    'bilang_sejuk': 'mengatakan cuaca sejuk dan nyaman',
    'bilang_lembap': 'mengeluh udara lembap',
    'bilang_kering': 'mengeluh udara kering',
    'bilang_angin': 'mengatakan angin kencang',
    'tanya_musim_hujan': 'menanyakan musim hujan',
    'peringatan_topan': 'memberi tahu ada topan',
    'saran_bawa_payung': 'menyarankan membawa payung',
    'saran_jemur': 'menyarankan menjemur cucian',
    'saran_angkat_cucian': 'menyarankan mengangkat cucian',
    'saran_tutup_jendela': 'menyarankan menutup jendela',
    'saran_pakaian': 'menyarankan pakaian yang sesuai cuaca',
    'saran_minum': 'mengingatkan minum agar tidak kepanasan',
    'bilang_terlihat_hujan': 'mengatakan kelihatannya akan hujan',
    'bilang_terlihat_cerah': 'mengatakan kelihatannya akan cerah',
    'bilang_cuaca_berubah': 'mengatakan cuaca mudah berubah',
    'bilang_terbakar_matahari': 'mengeluh terbakar matahari',
    'cerita_pemandangan': 'menceritakan pemandangan langit',
    'batalkan_rencana': 'membatalkan rencana karena cuaca',
    'bilang_tidak_bawa_payung': 'mengatakan lupa tidak membawa payung',
    'terima_kasih_peringatan': 'berterima kasih atas peringatan cuaca',
    'banding_hari_ini_kemarin': 'membandingkan cuaca hari ini dan kemarin',
    'bilang_pertama_kali': 'mengatakan cuaca seperti ini baru pertama kali',
}

SENTENCES = [
    sent(
        key='sapa_cuaca', rel='tetangga', fn='sapa_cuaca',
        words=['いい', '天気', 'です', 'ね', '。'],
        id_t='Cuacanya bagus ya.', en_t='Nice weather, isn\'t it.',
        sit='Menyapa tetangga dengan membicarakan cuaca', sit_en='Greeting a neighbour by talking about the weather',
        note='Ini pembuka obrolan paling umum dengan tetangga; ね di akhir meminta persetujuan, jadi bukan pernyataan kosong.',
        note_en='This is the most common opener with a neighbour; the ね asks for agreement, so it is not an empty remark.',
    ),
    sent(
        key='setuju_cuaca', rel='tetangga', fn='setuju_cuaca',
        words=['本当', 'に', 'そう', 'です', 'ね', '。', '過ごしやすい', 'です', 'ね', '。'],
        id_t='Betul sekali ya. Enak untuk beraktivitas.', en_t='It really is. Comfortable weather, isn\'t it.',
        sit='Menyetujui ucapan cuaca lawan bicara', sit_en='Agreeing with someone\'s remark about the weather',
        note='Menambah 過ごしやすいです ね setelah setuju membuat obrolannya berlanjut, bukan berhenti di satu kata.',
        note_en='Adding 過ごしやすいです ね after agreeing keeps the exchange going instead of ending on one word.',
    ),
    sent(
        key='tanya_cuaca_besok', rel='rekan', fn='tanya_cuaca_besok',
        words=['明日', 'の', '天気', 'は', 'どう', 'です', 'か', '。'],
        id_t='Cuaca besok bagaimana?', en_t='What is the weather like tomorrow?',
        sit='Menanyakan cuaca besok ke rekan', sit_en='Asking a colleague about tomorrow\'s weather',
        note='どうですか cukup untuk menanyakan keadaan; どうなりますか menanyakan perubahan dan lebih jarang dipakai untuk cuaca.',
        note_en='どうですか is enough to ask about a state; どうなりますか asks about change and is rarer for weather.',
    ),
    sent(
        key='bilang_cerah', rel='rekan', fn='bilang_cerah',
        words=['今日', 'は', '朝', 'から', '晴れて', 'います', '。'],
        id_t='Hari ini cerah sejak pagi.', en_t='It has been clear since morning.',
        sit='Melaporkan cuaca hari ini', sit_en='Reporting today\'s weather',
        note='朝から menandai sejak kapan keadaan itu berlangsung; tanpa itu kalimatnya hanya "sedang cerah".',
        note_en='朝から marks since when the state has held; without it the sentence only says it is clear right now.',
    ),
    sent(
        key='bilang_berawan', rel='rekan', fn='bilang_berawan',
        words=['空', 'が', '曇って', 'いる', 'けど', '、', '雨', 'は', 'まだ', '降って', 'いません', '。'],
        id_t='Langitnya berawan, tapi hujannya belum turun.', en_t='The sky is cloudy, but it is not raining yet.',
        sit='Menceritakan cuaca yang mendung tapi belum hujan', sit_en='Reporting a cloudy sky with no rain yet',
        note='まだ…いません berarti "belum", dan menyiratkan mungkin akan; 降りません akan berarti memang tidak turun.',
        note_en='まだ…いません means not yet and implies it may; 降りません would mean it does not rain.',
    ),
    sent(
        key='bilang_hujan', rel='rekan', fn='bilang_hujan',
        words=['あっ', '、', '雨', 'が', '降って', 'きました', 'ね', '。'],
        id_t='Oh, hujannya mulai turun ya.', en_t='Oh, it has started raining.',
        sit='Menyadari hujan baru mulai turun', sit_en='Noticing that it has just started raining',
        note='降ってきました memakai 来ます untuk perubahan yang menuju pembicara; inilah bentuk baku untuk hujan yang baru mulai.',
        note_en='降ってきました uses 来ます for change toward the speaker, which is the standard form for rain that has just begun.',
    ),
    sent(
        key='bilang_hujan_berhenti', rel='rekan', fn='bilang_hujan_berhenti',
        words=['さっき', 'まで', '降って', 'いた', 'けど', '、', 'もう', '止みました', '。'],
        id_t='Tadi masih hujan, tapi sekarang sudah berhenti.', en_t='It was raining until a moment ago, but it has stopped.',
        sit='Memberi tahu hujan sudah berhenti', sit_en='Reporting that the rain has stopped',
        note='止みました khusus untuk hujan dan salju; 止まりました dipakai untuk mesin atau orang.',
        note_en='止みました is for rain and snow; 止まりました is for machines or people.',
    ),
    sent(
        key='tanya_peluang_hujan', rel='rekan', fn='tanya_peluang_hujan',
        words=['今日', 'の', '降水確率', 'は', 'どのくらい', 'です', 'か', '。'],
        id_t='Peluang hujan hari ini berapa?', en_t='What is the chance of rain today?',
        sit='Menanyakan peluang hujan dari ramalan', sit_en='Asking the forecast chance of rain',
        note='降水確率 adalah istilah ramalan cuaca Jepang; angkanya 0 sampai 100 persen.',
        note_en='降水確率 is the Japanese forecast term for chance of rain; the figure runs from 0 to 100 percent.',
    ),
    sent(
        key='tanya_suhu', rel='rekan', fn='tanya_suhu',
        words=['今日', 'の', '気温', 'は', '何度', 'ぐらい', 'です', 'か', '。'],
        id_t='Suhu hari ini sekitar berapa derajat?', en_t='About what temperature is it today?',
        sit='Menanyakan suhu udara', sit_en='Asking the temperature',
        note='何度ぐらい adalah perkiraan; 何度ですか menanyakan angka pasti dan jarang dipakai untuk ramalan.',
        note_en='何度ぐらい asks for an approximation; 何度ですか demands an exact number and is rare for a forecast.',
    ),
    sent(
        key='bilang_panas', rel='tetangga', fn='bilang_panas',
        words=['今日', 'は', '本当', 'に', '暑い', 'です', 'ね', '。'],
        id_t='Hari ini benar-benar panas ya.', en_t='It is really hot today, isn\'t it.',
        sit='Mengeluh panas saat berpapasan', sit_en='Complaining about the heat in passing',
        note='暑い untuk cuaca, 熱い untuk benda; salah pakai adalah kekeliruan yang paling sering di kalimat cuaca.',
        note_en='暑い is for weather and 熱い for objects; mixing them is the most common slip in weather sentences.',
    ),
    sent(
        key='bilang_dingin', rel='tetangga', fn='bilang_dingin',
        words=['今朝', 'は', '寒かった', 'です', 'ね', '。'],
        id_t='Tadi pagi dingin ya.', en_t='It was cold this morning, wasn\'t it.',
        sit='Membicarakan dinginnya pagi', sit_en='Remarking on how cold the morning was',
        note='寒かった (lampau) karena membicarakan pagi yang sudah lewat; 寒いです akan berarti sekarang.',
        note_en='寒かった is past because it refers to the morning that has gone; 寒いです would mean now.',
    ),
    sent(
        key='bilang_sejuk', rel='rekan', fn='bilang_sejuk',
        words=['秋', 'に', 'なって', '、', '涼しく', 'なって', 'きました', '。'],
        id_t='Sudah masuk musim gugur, jadi mulai sejuk.', en_t='It has turned to autumn and is getting cooler.',
        sit='Menyadari musim berganti', sit_en='Noticing the season has turned',
        note='なってきました menandai perubahan bertahap yang sedang berlangsung, bukan keadaan yang tetap.',
        note_en='なってきました marks a gradual change in progress rather than a fixed state.',
    ),
    sent(
        key='bilang_lembap', rel='rekan', fn='bilang_lembap',
        words=['梅雨', 'の', '湿気', 'で', '洗濯物', 'が', '全然', '乾きません', '。'],
        id_t='Karena lembapnya musim hujan, cucian sama sekali tidak kering.', en_t='Because of the rainy-season damp, the washing will not dry at all.',
        sit='Mengeluh cucian tidak kering di musim hujan', sit_en='Complaining the washing will not dry in the rainy season',
        note='全然 dengan bentuk negatif berarti "sama sekali tidak"; pemakaian lama yang berarti "sama sekali" dengan positif dianggap tidak baku.',
        note_en='全然 with a negative means not at all; the older positive use is considered nonstandard.',
    ),
    sent(
        key='bilang_kering', rel='rekan', fn='bilang_kering',
        words=['冬', 'は', '乾燥', 'する', 'から', '、', '喉', 'が', '痛く', 'なりやすい', 'です', '。'],
        id_t='Musim dingin udaranya kering, jadi tenggorokan mudah sakit.', en_t='Winter air is dry, so sore throats come easily.',
        sit='Menceritakan dampak udara kering', sit_en='Explaining what dry air does',
        note='なりやすい menggabungkan なる dengan やすい (mudah); jadi bukan kepastian, melainkan kecenderungan.',
        note_en='なりやすい joins なる with やすい (easy), so it states a tendency rather than a certainty.',
    ),
    sent(
        key='bilang_angin', rel='rekan', fn='bilang_angin',
        words=['今日', 'は', '風', 'が', '強い', 'です', 'ね', '。', '上着', 'を', '着て', 'きた', 'ほう', 'が', 'いい', 'です', 'よ', '。'],
        id_t='Hari ini anginnya kencang ya. Sebaiknya pakai jaket.', en_t='The wind is strong today. You had better wear a jacket.',
        sit='Mengingatkan angin kencang ke rekan', sit_en='Warning a colleague about strong wind',
        note='きた ほう がいい adalah saran dari pengalaman: "yang sudah datang ke sini lebih baik dipakai".',
        note_en='きた ほう がいい is advice from experience: the one that has arrived here is better worn.',
    ),
    sent(
        key='tanya_musim_hujan', rel='tetangga', fn='tanya_musim_hujan',
        words=['梅雨', 'は', 'いつ', 'ごろ', '終わります', 'か', '。'],
        id_t='Musim hujannya kira-kira berakhir kapan?', en_t='About when does the rainy season end?',
        sit='Menanyakan akhir musim hujan', sit_en='Asking when the rainy season ends',
        note='ごろ menandai perkiraan; musim hujan tidak berakhir pada tanggal tetap, jadi ごろ lebih tepat daripada に.',
        note_en='ごろ marks an approximation; the rainy season does not end on a fixed date, so ごろ suits it better than に.',
    ),
    sent(
        key='peringatan_topan', rel='tetangga', fn='peringatan_topan', long=True,
        words=['台風', 'が', '近づいて', 'いる', 'ので', '、', '明日', 'は', '電車', 'が', '止まる', 'らしい', 'です', 'よ', '。'],
        id_t='Karena topan mendekat, kabarnya besok kereta akan berhenti.', en_t='A typhoon is approaching, so apparently the trains will stop tomorrow.',
        sit='Memberi tahu tetangga tentang topan', sit_en='Telling a neighbour about an approaching typhoon',
        note='らしいです menandai kabar dari sumber lain; でしょう akan berarti dugaan sendiri, dan itu kurang tepat untuk berita kereta.',
        note_en='らしいです marks information from elsewhere; でしょう would be your own guess, which is weaker for train news.',
    ),
    sent(
        key='saran_bawa_payung', rel='teman', fn='saran_bawa_payung',
        words=['午後', 'から', '雨', 'が', '降る', 'から', '、', '傘', 'を', '持って', 'いった', 'ほう', 'が', 'いい', 'よ', '。'],
        id_t='Karena dari siang akan hujan, sebaiknya bawa payung.', en_t='It will rain from the afternoon, so you had better take an umbrella.',
        sit='Menyarankan membawa payung ke teman', sit_en='Telling a friend to take an umbrella',
        note='持っていった ほう がいい adalah saran bentuk biasa; 持っていく ほう がいい juga benar, tapi bentuk lampaunya terdengar lebih tegas.',
        note_en='持っていった ほう がいい is plain-form advice; 持っていく ほう がいい is also correct but the past form sounds firmer.',
    ),
    sent(
        key='saran_jemur', rel='keluarga', fn='saran_jemur',
        words=['今日', 'は', '一日', '晴れ', 'の', '予定', 'だ', 'から', '、', '洗濯物', 'を', '外', 'に', '干して', '。'],
        id_t='Hari ini diperkirakan cerah sepanjang hari, jadi jemur cucian di luar.', en_t='It is meant to be sunny all day, so hang the washing outside.',
        sit='Meminta menjemur cucian karena cuaca cerah', sit_en='Asking for washing to be hung out while it is sunny',
        note='予定だ menyatakan perkiraan dari ramalan, bukan kepastian; bentuk 干して menutup sebagai permintaan akrab.',
        note_en='予定だ states what the forecast expects rather than a certainty; 干して closes it as a casual request.',
    ),
    sent(
        key='saran_angkat_cucian', rel='keluarga', fn='saran_angkat_cucian',
        words=['雨', 'が', '降りそう', 'だ', 'から', '、', '洗濯物', 'を', '取り込んで', '。'],
        id_t='Sepertinya mau hujan, angkat cuciannya.', en_t='It looks like rain, bring the washing in.',
        sit='Meminta mengangkat cucian karena akan hujan', sit_en='Asking for the washing to be brought in before rain',
        note='降りそう menggabungkan 降る dengan そう (kelihatannya); ini dugaan dari tanda yang terlihat, bukan ramalan resmi.',
        note_en='降りそう joins 降る with そう (looks like), a guess from visible signs rather than an official forecast.',
    ),
    sent(
        key='saran_tutup_jendela', rel='keluarga', fn='saran_tutup_jendela',
        words=['風', 'が', '強い', 'から', '、', '窓', 'を', '閉めて', 'おいて', '。'],
        id_t='Karena anginnya kencang, tutup jendelanya.', en_t='The wind is strong, so keep the windows closed.',
        sit='Meminta menutup jendela karena angin', sit_en='Asking for windows to be closed against the wind',
        note='閉めておいて memakai おく (melakukan dulu untuk nanti), jadi bukan sekadar "tutup sekarang".',
        note_en='閉めておいて uses おく (do in advance), so it is not merely close it now.',
    ),
    sent(
        key='saran_pakaian', rel='rekan', fn='saran_pakaian',
        words=['外', 'は', '思った', 'より', '寒い', 'から', '、', '上着', 'を', '一枚', '持って', 'いった', 'ほう', 'が', 'いい', 'です', 'よ', '。'],
        id_t='Di luar lebih dingin dari yang saya sangka, jadi sebaiknya bawa satu jaket.', en_t='It is colder outside than I expected, so take a jacket.',
        sit='Mengingatkan membawa jaket', sit_en='Reminding someone to take a jacket',
        note='思ったより adalah perbandingan dengan dugaan sendiri; ini cara menyampaikan temuan, bukan perintah.',
        note_en='思ったより compares with your own expectation, which reports a finding rather than giving an order.',
    ),
    sent(
        key='saran_minum', rel='rekan', fn='saran_minum',
        words=['今日', 'は', '暑い', 'から', '、', '水分', 'を', 'よく', '取って', 'ください', 'ね', '。'],
        id_t='Hari ini panas, jadi tolong cukup minum ya.', en_t='It is hot today, so please drink plenty of fluids.',
        sit='Mengingatkan minum saat panas', sit_en='Reminding someone to drink in the heat',
        note='水分を取る adalah cara baku menyebut minum dalam konteks kesehatan; 水を飲んでください juga benar tapi lebih sempit.',
        note_en='水分を取る is the standard health phrasing for drinking; 水を飲んでください is correct but narrower.',
    ),
    sent(
        key='bilang_terlihat_hujan', rel='teman', fn='bilang_terlihat_hujan',
        words=['空', 'が', '暗い', 'から', '、', '降りそう', 'だ', 'ね', '。'],
        id_t='Langitnya gelap, sepertinya mau hujan ya.', en_t='The sky is dark, looks like rain.',
        sit='Menebak hujan dari langit', sit_en='Guessing rain from the sky',
        note='そう menggabungkan dugaan dengan tanda yang bisa dilihat; menambahkan だから alasannya membuat tebakan itu masuk akal.',
        note_en='そう ties a guess to visible signs; giving the reason with から makes the guess reasonable.',
    ),
    sent(
        key='bilang_terlihat_cerah', rel='teman', fn='bilang_terlihat_cerah',
        words=['午後', 'は', '晴れる', 'らしい', 'よ', '。', '洗濯', 'した', 'ら', '？'],
        id_t='Katanya siang nanti cerah. Sudah mencuci?', en_t='Apparently it will clear in the afternoon. Did you do the laundry?',
        sit='Memberi tahu ramalan cerah dan mengingatkan mencuci', sit_en='Passing on a sunny forecast and asking about laundry',
        note='らしい menyampaikan kabar dari ramalan, bukan dugaan sendiri; itu sebabnya dipakai untuk berita cuaca.',
        note_en='らしい passes on forecast information rather than your own guess, which is why it suits weather news.',
    ),
    sent(
        key='bilang_cuaca_berubah', rel='tetangga', fn='bilang_cuaca_berubah',
        words=['この', 'ごろ', 'の', '天気', 'は', '変わりやすい', 'です', 'ね', '。'],
        id_t='Cuaca akhir-akhir ini mudah berubah ya.', en_t='The weather is changeable around this time, isn\'t it.',
        sit='Membicarakan cuaca yang tidak stabil', sit_en='Remarking that the weather is unsettled',
        note='このごろ berarti akhir-akhir ini; 最近も bisa, tapi このごろ lebih sering dipakai untuk cuaca dan kebiasaan.',
        note_en='このごろ means around these days; 最近 works too, but このごろ is more common for weather and habits.',
    ),
    sent(
        key='bilang_terbakar_matahari', rel='teman', fn='bilang_terbakar_matahari',
        words=['日焼け', 'しすぎて', '、', '腕', 'が', '痛い', 'よ', '。'],
        id_t='Saya terlalu lama kena matahari sampai lengan saya sakit.', en_t='I got too much sun and now my arm hurts.',
        sit='Mengeluh terbakar matahari', sit_en='Complaining about sunburn',
        note='しすぎて menggabungkan する dengan すぎる (berlebihan) dan て (sebab); jadi kalimatnya menyatakan akibat.',
        note_en='しすぎて joins する with すぎる (too much) and て (cause), so the sentence states a consequence.',
    ),
    sent(
        key='cerita_pemandangan', rel='teman', fn='cerita_pemandangan',
        words=['雨', 'の', 'あと', 'の', '空', 'は', 'とても', 'きれい', 'で', '、', '虹', 'も', '見えた', '。'],
        id_t='Langit setelah hujan sangat indah, dan pelanginya juga terlihat.', en_t='The sky after the rain was beautiful, and I could see a rainbow too.',
        sit='Menceritakan pemandangan setelah hujan', sit_en='Describing the sky after rain',
        note='で di tengah menyambungkan dua pengamatan setara; から akan berarti yang kedua disebabkan yang pertama, dan itu tidak berlaku di sini.',
        note_en='The で in the middle joins two equal observations; から would make the second caused by the first, which is not the case.',
    ),
    sent(
        key='batalkan_rencana', rel='teman', fn='batalkan_rencana', long=True,
        words=['台風', 'で', '電車', 'が', '止まって', 'いる', 'から', '、', '今日', 'の', '約束', 'は', '中止', 'に', 'しよう', '。'],
        id_t='Karena kereta berhenti akibat topan, janji hari ini kita batalkan saja.', en_t='The trains have stopped because of the typhoon, so let us cancel today.',
        sit='Membatalkan janji karena cuaca', sit_en='Cancelling plans because of the weather',
        note='で di sini menandai sebab berupa peristiwa (topan), bukan alasan pribadi; itu yang membuat pembatalannya terasa di luar kendali.',
        note_en='で here marks an event as the cause (the typhoon) rather than a personal reason, which makes the cancellation feel outside your control.',
    ),
    sent(
        key='bilang_tidak_bawa_payung', rel='rekan', fn='bilang_tidak_bawa_payung',
        words=['朝', 'は', '晴れて', 'いました', 'から', '、', '傘', 'を', '持って', 'きませんでした', '。'],
        id_t='Karena pagi tadi cerah, saya tidak membawa payung.', en_t='It was sunny this morning, so I did not bring an umbrella.',
        sit='Mengeluh tidak membawa payung', sit_en='Explaining why you have no umbrella',
        note='持ってきませんでした adalah bentuk sopan dari 持ってこなかった; 来ます di sini berarti "ke sini", bukan "datang berkunjung".',
        note_en='持ってきませんでした is the polite negative past of 持ってくる; the 来ます here means toward here, not visiting.',
    ),
    sent(
        key='terima_kasih_peringatan', rel='tetangga', fn='terima_kasih_peringatan',
        words=['教えて', 'くれて', 'ありがとう', 'ございます', '。', '傘', 'を', '持って', '出かけます', '。'],
        id_t='Terima kasih sudah memberi tahu. Saya akan keluar membawa payung.', en_t='Thank you for telling me. I will take an umbrella.',
        sit='Berterima kasih atas peringatan cuaca tetangga', sit_en='Thanking a neighbour for the weather warning',
        note='教えてくれてありがとう berterima kasih atas jasanya, bukan atas bendanya; ini bentuk yang paling sering dipakai.',
        note_en='教えてくれてありがとう thanks the person for the favour rather than the object, which is the usual form.',
    ),
    sent(
        key='banding_hari_ini_kemarin', rel='rekan', fn='banding_hari_ini_kemarin',
        words=['昨日', 'より', '今日', 'の', 'ほう', 'が', 'ずっと', '涼しい', 'です', 'ね', '。'],
        id_t='Hari ini jauh lebih sejuk daripada kemarin ya.', en_t='Today is much cooler than yesterday, isn\'t it.',
        sit='Membandingkan cuaca dua hari', sit_en='Comparing today\'s weather with yesterday\'s',
        note='A より B のほうが… membandingkan dua hal; ずっと menegaskan selisihnya besar, bukan sekadar lebih.',
        note_en='A より B のほうが… compares two things; ずっと stresses that the gap is large rather than merely more.',
    ),
    sent(
        key='bilang_pertama_kali', rel='tetangga', fn='bilang_pertama_kali',
        words=['こんな', 'に', '暑い', '夏', 'は', '初めて', 'です', '。'],
        id_t='Musim panas sepanas ini baru pertama kali saya alami.', en_t='This is the first time I have known a summer this hot.',
        sit='Membicarakan cuaca yang luar biasa', sit_en='Remarking on unusually extreme weather',
        note='こんなに…のは初めてです menyatakan pengalaman pertama; ini lebih kuat daripada 暑いですね dan sering dipakai untuk cuaca ekstrem.',
        note_en='こんなに…のは初めてです states a first experience; it is stronger than 暑いですね and common for extreme weather.',
    ),
]
