#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Kesehatan: saying what hurts, at the pharmacy and at the clinic.

This is the topic where a lack of words has the highest cost, so the functions are ordered by
what actually happens: you notice something, you describe it precisely enough for someone to
help, you buy something at the pharmacy, you decide whether to see a doctor, you make the
appointment, you answer the doctor's questions, you collect the medicine and you follow the
instructions. Describing a symptom badly is the failure mode here, so the symptom functions
separate dull from sharp pain, where it hurts, since when, and what makes it worse.
"""
from compose import sent, add_words

add_words({
    '具合': ('guai', 'kondisi (badan)', 'condition (of health)'),
    '具合が悪い': ('guai ga warui', 'kondisi badan tidak enak', 'unwell'),
    '体調': ('taichou', 'kondisi fisik', 'physical condition'),
    '症状': ('shoujou', 'gejala', 'symptom'),
    '熱があります': ('netsu ga arimasu', 'demam', 'have a fever'),
    '頭痛': ('zutsuu', 'sakit kepala', 'headache'),
    '腹痛': ('fukutsuu', 'sakit perut', 'stomach ache'),
    '痛み': ('itami', 'rasa sakit', 'pain'),
    '痛みます': ('itamimasu', 'sakit (sopan)', 'hurts (polite)'),
    'ずきずき': ('zukizuki', 'nyeri berdenyut', 'throbbing pain'),
    'ちくちく': ('chikuchiku', 'nyeri menusuk', 'prickling pain'),
    '鈍い': ('nibui', 'tumpul (nyeri)', 'dull (pain)'),
    '吐き気': ('hakike', 'mual', 'nausea'),
    'めまい': ('memai', 'pusing berputar', 'dizziness'),
    'くしゃみ': ('kushami', 'bersin', 'sneeze'),
    '鼻水': ('hanamizu', 'ingus', 'runny nose'),
    '咳': ('seki', 'batuk', 'cough'),
    '喉が痛い': ('nodo ga itai', 'sakit tenggorokan', 'sore throat'),
    '下痢': ('geri', 'diare', 'diarrhoea'),
    '食欲': ('shokuyoku', 'nafsu makan', 'appetite'),
    '寝不足': ('nebusoku', 'kurang tidur', 'lack of sleep'),
    '疲れ': ('tsukare', 'kelelahan', 'fatigue'),
    '疲れました': ('tsukaremashita', 'lelah (lampau sopan)', 'got tired (polite past)'),
    '調子': ('choushi', 'kondisi / keadaan', 'shape / condition'),
    '悪化': ('akka', 'memburuk', 'getting worse'),
    'よくなりました': ('yoku narimashita', 'membaik (lampau sopan)', 'got better (polite past)'),
    '診察': ('shinsatsu', 'pemeriksaan dokter', 'medical examination'),
    '診てもらう': ('mite morau', 'diperiksa dokter', 'be examined by a doctor'),
    '診てもらえますか': ('mite moraemasu ka', 'boleh diperiksa', 'could you examine me'),
    '予約したい': ('yoyaku shitai', 'ingin membuat janji', 'want to book'),
    '保険証': ('hokenshou', 'kartu asuransi kesehatan', 'health insurance card'),
    '処方箋': ('shohousen', 'resep dokter', 'prescription'),
    'この薬': ('kono kusuri', 'obat ini', 'this medicine'),
    '食後': ('shokugo', 'setelah makan', 'after meals'),
    '食前': ('shokuzenn', 'sebelum makan', 'before meals'),
    '一日三回': ('ichinichi sankai', 'tiga kali sehari', 'three times a day'),
    '飲み方': ('nomikata', 'cara minum', 'how to take (medicine)'),
    'アレルギー': ('arerugii', 'alergi', 'allergy'),
    '副作用': ('fukusayou', 'efek samping', 'side effect'),
    '副作用があります': ('fukusayou ga arimasu', 'ada efek samping', 'has side effects'),
    '眠くなります': ('nemuku narimasu', 'menjadi mengantuk', 'makes you sleepy'),
    '効きません': ('kikimasen', 'tidak berkhasiat (sopan)', 'does not work (polite)'),
    '市販薬': ('shihanyaku', 'obat bebas', 'over-the-counter medicine'),
    '解熱剤': ('genetsuzai', 'obat penurun panas', 'fever reducer'),
    '痛み止め': ('itamidome', 'obat pereda nyeri', 'painkiller'),
    '湿布': ('shippu', 'plester obat', 'medicated patch'),
    '包帯': ('houtai', 'perban', 'bandage'),
    '診断': ('shindan', 'diagnosis', 'diagnosis'),
    '検査': ('kensa', 'pemeriksaan (medis)', 'test / examination'),
    '血液検査': ('ketsueki kensa', 'tes darah', 'blood test'),
    '入院': ('nyuuin', 'rawat inap', 'hospitalisation'),
    '救急車': ('kyuukyuusha', 'ambulans', 'ambulance'),
    '呼んで': ('yonde', 'memanggil (bentuk -te)', 'call (te-form)'),
    '安静': ('ansei', 'istirahat', 'rest'),
    '安静に': ('ansei ni', 'dengan istirahat', 'with rest'),
    '無理をしないで': ('muri o shinai de', 'jangan memaksakan diri', 'do not overdo it'),
    '早め': ('hayame', 'lebih awal', 'early'),
    '様子': ('yousu', 'keadaan / perkembangan', 'how things are going'),
    '様子を見て': ('yousu o mite', 'lihat perkembangannya dulu', 'see how it goes'),
    '心配しすぎ': ('shinpai shisugi', 'terlalu khawatir', 'worrying too much'),
    '休んで': ('yasunde', 'istirahat (bentuk -te)', 'rest (te-form)'),
    '寝て': ('nete', 'tidur (bentuk -te)', 'sleep (te-form)'),
    '行ったほうが': ('itta hou ga', 'sebaiknya pergi', 'better to go'),
    'よかったら': ('yokattara', 'kalau mau / kalau berkenan', 'if you like'),
    '連れて行きます': ('tsurete ikimasu', 'mengantar (sopan)', 'take someone (polite)'),
    'あげます': ('agemasu', 'memberi (sopan)', 'give (polite)'),
    'もらって': ('moratte', 'menerima (bentuk -te)', 'receive (te-form)'),
    'いいですか': ('ii desu ka', 'bolehkah', 'is it all right'),
    '飲んでもいいですか': ('nonde mo ii desu ka', 'boleh diminum', 'may I take it'),
    '飲めません': ('nomemasen', 'tidak bisa minum (sopan)', 'cannot take (polite)'),
    '運転': ('unten', 'mengemudi', 'driving'),
    '運転して': ('unten shite', 'mengemudi (bentuk -te)', 'drive (te-form)'),
    'アレルギーがあります': ('arerugii ga arimasu', 'punya alergi', 'have an allergy'),
    '診られます': ('miraremasu', 'bisa diperiksa (sopan)', 'can be seen (polite)'),
    '安静にして': ('ansei ni shite', 'beristirahat (bentuk -te)', 'rest (te-form)'),
    '安静にしていました': ('ansei ni shite imashita', 'sedang beristirahat (lampau)', 'was resting'),
    '安静にしてください': ('ansei ni shite kudasai', 'tolong beristirahat', 'please rest'),
    '様子を見ます': ('yousu o mimasu', 'melihat perkembangan dulu', 'see how it goes'),
    '様子を見ましょう': ('yousu o mimashou', 'mari lihat perkembangan dulu', 'let us see how it goes'),
    '心配しないで': ('shinpai shinai de', 'jangan khawatir', 'do not worry'),
    '無理をしないでください': ('muri o shinai de kudasai', 'tolong jangan memaksakan diri', 'please do not overdo it'),
    '安静にしていてください': ('ansei ni shite ite kudasai', 'tolong tetap beristirahat', 'please keep resting'),
    '気分が悪い': ('kibun ga warui', 'perasaan tidak enak / mual', 'feeling unwell'),
    '気分が悪くなりました': ('kibun ga waruku narimashita', 'perasaan jadi tidak enak', 'started feeling unwell'),
    '食欲がありません': ('shokuyoku ga arimasen', 'tidak ada nafsu makan', 'have no appetite'),
    '眠れません': ('nemuremasen', 'tidak bisa tidur (sopan)', 'cannot sleep (polite)'),
    '眠れませんでした': ('nemuremasen deshita', 'tidak bisa tidur (lampau sopan)', 'could not sleep'),
    'いつからですか': ('itsu kara desu ka', 'sejak kapan', 'since when'),
    'どのあたり': ('dono atari', 'bagian mana', 'which part'),
    'どれくらい': ('dore kurai', 'seberapa lama / seberapa', 'how long / how much'),
    'よくなりましたか': ('yoku narimashita ka', 'sudah membaik?', 'has it got better'),
    '熱を測って': ('netsu o hakatte', 'mengukur suhu (bentuk -te)', 'take the temperature (te-form)'),
    '測ります': ('hakarimasu', 'mengukur (sopan)', 'measure (polite)'),
    '安静が必要です': ('ansei ga hitsuyou desu', 'perlu istirahat', 'rest is necessary'),
    '必要': ('hitsuyou', 'perlu / kebutuhan', 'necessary'),
    '安心': ('anshin', 'lega / tenang', 'relief'),
    '安心しました': ('anshin shimashita', 'merasa lega (lampau)', 'felt relieved'),
    '説明します': ('setsumei shimasu', 'menjelaskan (sopan)', 'explain (polite)'),
    '説明して': ('setsumei shite', 'menjelaskan (bentuk -te)', 'explain (te-form)'),
    '書きます': ('kakimasu', 'menulis (sopan)', 'write (polite)'),
    '出します': ('dashimasu', 'mengeluarkan (sopan)', 'hand in (polite)'),
    '渡します': ('watashimasu', 'menyerahkan (sopan)', 'hand over (polite)'),
    '受け取って': ('uketotte', 'menerima (bentuk -te)', 'receive (te-form)'),
    'お待ちください': ('omachi kudasai', 'tolong tunggu (sopan)', 'please wait (very polite)'),
    '呼びます': ('yobimasu', 'memanggil (sopan)', 'call (polite)'),
    '診療時間': ('shinryou jikan', 'jam praktik', 'consultation hours'),
    '何時まで': ('nanji made', 'sampai jam berapa', 'until what time'),
    '予約なし': ('yoyaku nashi', 'tanpa janji', 'without an appointment'),
    '予約なしでも': ('yoyaku nashi demo', 'meski tanpa janji', 'even without an appointment'),
    '二日': ('futsuka', 'dua hari', 'two days'),
    '効く': ('kiku', 'berkhasiat (biasa)', 'works (plain)'),
    'もの': ('mono', 'hal / benda (abstrak)', 'thing (abstract)'),
    '飲ませる': ('nomiseru', 'membuat minum (kausatif)', 'make someone drink (causative)'),
    '授乳中': ('junyuuchuu', 'sedang menyusui', 'breastfeeding'),
    '飲んでも': ('nonde mo', 'meskipun diminum', 'even if one takes it'),
    '効かない': ('kikanai', 'tidak berkhasiat (biasa)', 'does not work (plain)'),
    '別': ('betsu', 'lain / terpisah', 'another'),
    '処方': ('shohou', 'peresepan', 'prescription (act)'),
    'もらえます': ('moraemasu', 'bisa minta (sopan)', 'can receive (polite)'),
    '午後': ('gogo', 'siang/sore (PM)', 'afternoon (PM)'),
    '診て': ('mite', 'memeriksa (bentuk -te)', 'examine (te-form)'),
    '初めて': ('hajimete', 'pertama kali', 'for the first time'),
    'あって': ('atte', 'ada (bentuk -te)', 'there is (te-form)'),
    '出て': ('dete', 'keluar / muncul (bentuk -te)', 'come out (te-form)'),
    'きました': ('kimashita', 'datang (lampau sopan)', 'came (polite past)'),
    'おととい': ('ototoi', 'dua hari lalu', 'the day before yesterday'),
    '押される': ('osareru', 'ditekan (pasif)', 'be pressed (passive)'),
    '原因': ('gen-in', 'penyebab', 'cause'),
    '休んだ': ('yasunda', 'istirahat (biasa, lampau)', 'rested (plain past)'),
    'ほう': ('hou', 'yang (dalam perbandingan)', 'the one (in a comparison)'),
    '出す': ('dasu', 'mengeluarkan (biasa)', 'hand in (plain)'),
    '診断書': ('shindansho', 'surat keterangan dokter', 'medical certificate'),
    '書いて': ('kaite', 'menulis (bentuk -te)', 'write (te-form)'),
    'いただけます': ('itadakemasu', 'bisa menerima (sopan)', 'can receive (humble)'),
    '治ります': ('naorimasu', 'sembuh (sopan)', 'gets better (polite)'),
    '同じ': ('onaji', 'sama', 'same'),
    'しないで': ('shinai de', 'jangan melakukan', 'do not do'),
    'ほとんど': ('hotondo', 'hampir', 'almost'),
    'あまり': ('amari', 'tidak begitu (dengan negatif)', 'not very (with a negative)'),
    '効いて': ('kiite', 'berkhasiat (bentuk -te)', 'work (te-form)'),
    'いない': ('inai', 'tidak ada (biasa)', 'is not (plain)'),
    'みたい': ('mitai', 'seperti / kelihatannya', 'looks like'),
    'どのくらい': ('dono kurai', 'berapa lama / seberapa', 'how long / how much'),
    'よく': ('yoku', 'sering', 'often'),
    '連れて': ('tsurete', 'membawa (orang, bentuk -te)', 'take (a person) (te-form)'),
    '早めに': ('hayame ni', 'lebih awal', 'a little early'),
    'もらえますか': ('moraemasu ka', 'boleh minta (dibuatkan)', 'could you (do it for me)'),
    '続いて': ('tsuzuite', 'berlanjut (bentuk -te)', 'continue (te-form)'),
    'まま': ('mama', 'tetap dalam keadaan', 'as it is'),
    'いれば': ('ireba', 'kalau ada', 'if it is'),
    '全然': ('zenzen', 'sama sekali (dengan negatif)', 'not at all (with a negative)'),
    'よかった': ('yokatta', 'syukurlah / bagus (lampau)', 'thank goodness (past)'),
    '三十八度': ('sanjuppachi do', 'tiga puluh delapan derajat', 'thirty-eight degrees'),
    'ぐらい': ('guirai', 'kira-kira', 'about / roughly'),
    '右側': ('migigawa', 'sebelah kanan', 'the right side'),
    '痛く': ('itaku', 'sakit (bentuk -ku)', 'painfully (adverbial)'),
    'て': ('te', 'dan (penghubung bentuk -te)', 'and (te-form linker)'),
    '昨夜': ('sakuya', 'tadi malam', 'last night'),
    '飲み込む': ('nomikomu', 'menelan (biasa)', 'swallow (plain)'),
    'とき': ('toki', 'saat / ketika', 'when'),
    '特に': ('toku ni', 'terutama', 'especially'),
    '三日前': ('mikka mae', 'tiga hari lalu', 'three days ago'),
    '止まりません': ('tomarimasen', 'tidak berhenti (sopan)', 'does not stop (polite)'),
    '悪く': ('waruku', 'buruk (bentuk -ku)', 'badly (adverbial)'),
    '立った': ('tatta', 'berdiri (biasa, lampau)', 'stood (plain past)'),
    '一週間': ('isshuukan', 'satu minggu', 'one week'),
})

SINGLE_WORDS = {
    '具合が悪い': 'ungkapan tetap untuk kondisi badan, bukan frasa bebas',
    '熱があります': 'satu predikat tetap (demam), bukan frasa bebas',
    '喉が痛い': 'ungkapan tetap (sakit tenggorokan), bukan frasa bebas',
    '気分が悪い': 'ungkapan tetap (perasaan tidak enak), bukan frasa bebas',
    '食欲がありません': 'ungkapan tetap (tidak nafsu makan), bukan frasa bebas',
    'アレルギーがあります': 'satu predikat tetap, bukan frasa bebas',
    '診てもらえますか': 'permintaan sopan sebagai satu kesatuan',
    '安静が必要です': 'satu predikat tetap (perlu istirahat), bukan frasa bebas',
    '無理をしないでください': 'permintaan utuh (jangan memaksakan diri)',
    '安静にしてください': 'permintaan utuh (beristirahatlah)',
    '安静にしていてください': 'permintaan utuh (tetap beristirahat)',
    '安静にしていました': 'satu predikat (sedang beristirahat)',
    '安静にして': 'ungkapan tetap (beristirahatlah)',
    '心配しないで': 'ungkapan tetap (jangan khawatir)',
    '運転して': 'satu kata kerja majemuk, bukan frasa',
    '食前': 'satu kata (sebelum makan)',
    '食後': 'satu kata (setelah makan)',
    '副作用': 'satu kata majemuk (efek samping)',
    '血液検査': 'satu kata majemuk (tes darah)',
    '保険証': 'satu kata majemuk (kartu asuransi)',
    '市販薬': 'satu kata majemuk (obat bebas)',
    '解熱剤': 'satu kata majemuk (obat penurun panas)',
    '痛み止め': 'satu kata majemuk (obat pereda nyeri)',
    '救急車': 'satu kata majemuk (ambulans)',
    '一日三回': 'ungkapan tetap (tiga kali sehari)',
    '寝不足': 'satu kata majemuk (kurang tidur)',
    'めまい': 'satu kata (pusing)',
    '眠れませんでした': 'satu kata kerja potensial negatif terinfleksi, bukan frasa',
    'くしゃみ': 'satu kata (bersin)',
    '鼻水': 'satu kata (ingus)',
    'お大事に': 'ungkapan tetap (semoga lekas sembuh)',
    'お待ちください': 'permintaan sopan sebagai satu kesatuan',
    '予約なしでも': 'ungkapan tetap (meski tanpa janji)',
    'よくなりました': 'satu predikat (menjadi membaik)',
    '気をつけて': 'ungkapan tetap (jaga diri)',
}

SET_PHRASES = {
    'terima_kasih_obat': 'お大事に adalah ungkapan tetap tanpa predikat です',
}

FUNCTIONS = {
    'bilang_tidak_enak_badan': 'mengatakan badan tidak enak',
    'bilang_demam': 'mengatakan sedang demam',
    'bilang_sakit_kepala': 'mengatakan sakit kepala',
    'jelaskan_nyeri': 'menjelaskan jenis nyeri',
    'bilang_sakit_tenggorokan': 'mengatakan sakit tenggorokan',
    'bilang_batuk': 'mengatakan batuk',
    'bilang_mual': 'mengatakan mual',
    'bilang_pusing': 'mengatakan pusing',
    'bilang_tidak_bisa_tidur': 'mengatakan tidak bisa tidur',
    'bilang_tidak_nafsu_makan': 'mengatakan tidak ada nafsu makan',
    'sejak_kapan': 'menjelaskan sejak kapan sakit',
    'beli_obat': 'membeli obat di apotek',
    'tanya_obat_batuk': 'menanyakan obat batuk',
    'tanya_efek_samping': 'menanyakan efek samping obat',
    'tanya_boleh_minum': 'menanyakan apakah obat boleh diminum',
    'tanya_cara_minum': 'menanyakan cara minum obat',
    'minta_resep': 'meminta resep',
    'buat_janji': 'membuat janji dengan dokter',
    'tanya_jam_praktik': 'menanyakan jam praktik klinik',
    'daftar_klinik': 'mendaftar di klinik',
    'jelaskan_gejala_dokter': 'menjelaskan gejala kepada dokter',
    'jawab_sejak_kapan': 'menjawab pertanyaan sejak kapan',
    'jawab_dimana_sakit': 'menjawab di mana sakitnya',
    'tanya_penyebab': 'menanyakan penyebab sakit',
    'tanya_istirahat': 'menanyakan apakah perlu istirahat',
    'minta_keterangan': 'meminta surat keterangan sakit',
    'tanya_sembuh': 'menanyakan apakah akan sembuh',
    'dengar_diagnosis': 'menerima penjelasan diagnosis',
    'tanya_tes': 'menanyakan apakah perlu tes',
    'tanya_obat_anak': 'menanyakan obat untuk anak',
    'ingatkan_istirahat': 'mengingatkan orang lain untuk istirahat',
    'tawarkan_antar': 'menawarkan mengantar ke klinik',
    'tanya_kabar_sakit': 'menanyakan kabar orang yang sakit',
    'bilang_sudah_membaik': 'mengatakan sudah membaik',
    'bilang_belum_membaik': 'mengatakan belum membaik',
    'pesan_jangan_memaksa': 'memesan agar tidak memaksakan diri',
    'sarankan_ke_dokter': 'menyarankan pergi ke dokter',
    'tanya_apakah_serius': 'menanyakan apakah keadaannya serius',
    'bilang_obat_tidak_berkhasiat': 'mengatakan obat tidak berkhasiat',
    'syukuri_sembuh': 'bersyukur sudah sembuh',
}

SENTENCES = [
    sent(
        key='bilang_tidak_enak_badan', rel='rekan', fn='bilang_tidak_enak_badan',
        words=['すみません', '、', '今日', 'は', '具合', 'が', '悪い', 'ので', '、', '早め', 'に', '帰ります', '。'],
        id_t='Maaf, hari ini badan saya tidak enak, jadi saya pulang lebih awal.', en_t='Sorry, I am unwell today, so I will leave early.',
        sit='Memberi tahu rekan kerja bahwa badan tidak enak', sit_en='Telling a colleague you are unwell',
        note='具合が悪い adalah cara paling umum mengatakan badan tidak enak tanpa menyebut penyakit tertentu.',
        note_en='具合が悪い is the most common way to say you are unwell without naming an illness.',
    ),
    sent(
        key='bilang_demam', rel='rekan', fn='bilang_demam',
        words=['今朝', 'から', '熱', 'が', 'あります', '。', '三十八度', 'ぐらい', 'です', '。'],
        id_t='Sejak pagi saya demam. Sekitar tiga puluh delapan derajat.', en_t='I have had a fever since this morning. About thirty-eight degrees.',
        sit='Melaporkan demam dengan angkanya', sit_en='Reporting a fever with the figure',
        note='Menyebut angkanya penting di Jepang: 三十七度 masih dianggap ringan, 三十八度 ke atas sudah alasan kuat untuk tidak masuk.',
        note_en='The number matters in Japan: 三十七度 counts as mild, while 三十八度 and up is a real reason to stay home.',
    ),
    sent(
        key='bilang_sakit_kepala', rel='rekan', fn='bilang_sakit_kepala',
        words=['朝', 'から', '頭', 'が', '痛い', 'です', '。'],
        id_t='Sejak pagi kepala saya sakit.', en_t='I have had a headache since this morning.',
        sit='Mengeluh sakit kepala ke rekan', sit_en='Mentioning a headache to a colleague',
        note='頭が痛い adalah bentuk yang lazim; 頭痛がします juga benar tapi terdengar lebih formal.',
        note_en='頭が痛い is the usual phrasing; 頭痛がします is also correct but sounds more formal.',
    ),
    sent(
        key='jelaskan_nyeri', rel='dokter', fn='jelaskan_nyeri', long=True,
        words=['お腹', 'の', '右側', 'が', 'ずきずき', '痛い', 'ので', '、', '昨夜', 'は', '眠れませんでした', '。'],
        id_t='Perut sebelah kanan saya nyeri berdenyut, sehingga tadi malam tidak bisa tidur.', en_t='The right side of my stomach is throbbing, so I could not sleep last night.',
        sit='Menjelaskan jenis dan letak nyeri kepada dokter', sit_en='Describing the type and place of pain to a doctor',
        note='ので menyambungkan nyeri dengan akibatnya (tidak bisa tidur), jadi dokter melihat kaitannya; ずきずき adalah nyeri berdenyut.',
        note_en='ので links the pain to its consequence (no sleep), so the doctor sees the connection; ずきずき is throbbing pain.',
    ),
    sent(
        key='bilang_sakit_tenggorokan', rel='dokter', fn='bilang_sakit_tenggorokan',
        words=['喉', 'が', '痛い', 'です', '。', '飲み込む', 'とき', 'に', '特に', '痛みます', '。'],
        id_t='Tenggorokan saya sakit. Terutama saat menelan.', en_t='My throat hurts. Especially when I swallow.',
        sit='Menjelaskan sakit tenggorokan', sit_en='Describing a sore throat',
        note='飲み込むときに特に痛い adalah keterangan yang menolong dokter mempersempit kemungkinan, bukan sekadar keluhan.',
        note_en='Pain specifically when swallowing helps a doctor narrow things down rather than just complaining.',
    ),
    sent(
        key='bilang_batuk', rel='dokter', fn='bilang_batuk',
        words=['三日前', 'から', '咳', 'が', '止まりません', '。'],
        id_t='Sejak tiga hari lalu batuk saya tidak berhenti.', en_t='I have had a cough for three days.',
        sit='Menjelaskan batuk yang lama', sit_en='Describing a persistent cough',
        note='咳が止まりません (batuk tidak berhenti) menyampaikan lamanya tanpa harus menyebut berapa kali.',
        note_en='咳が止まりません says the cough will not stop, which conveys duration without counting episodes.',
    ),
    sent(
        key='bilang_mual', rel='dokter', fn='bilang_mual',
        words=['気分', 'が', '悪く', 'て', '、', '吐き気', 'も', 'します', '。'],
        id_t='Perasaan saya tidak enak, dan mual juga.', en_t='I feel unwell and also nauseous.',
        sit='Mengeluh mual kepada dokter', sit_en='Reporting nausea to a doctor',
        note='吐き気がします memakai します karena gejalanya datang sendiri, bukan tindakan yang dilakukan.',
        note_en='吐き気がします uses します because the symptom comes on its own rather than being an action.',
    ),
    sent(
        key='bilang_pusing', rel='dokter', fn='bilang_pusing',
        words=['立った', 'とき', 'に', 'めまい', 'が', 'します', '。'],
        id_t='Saya pusing saat berdiri.', en_t='I get dizzy when I stand up.',
        sit='Menjelaskan pusing saat berdiri', sit_en='Describing dizziness on standing',
        note='めまいがします adalah bentuk lazim untuk pusing berputar; くらくらします untuk rasa mau pingsan.',
        note_en='めまいがします is usual for spinning dizziness; くらくらします is for feeling faint.',
    ),
    sent(
        key='bilang_tidak_bisa_tidur', rel='dokter', fn='bilang_tidak_bisa_tidur',
        words=['この', '一週間', '、', 'よく', '眠れません', '。'],
        id_t='Seminggu ini saya tidak bisa tidur dengan cukup.', en_t='I have not been able to sleep properly for a week.',
        sit='Mengeluh sulit tidur', sit_en='Complaining about poor sleep',
        note='眠れません adalah bentuk potensial negatif: bukan "tidak tidur", tapi "tidak bisa tidur"; あまり menegaskan kurangnya.',
        note_en='眠れません is the negative potential: not I do not sleep, but I cannot sleep; あまり stresses the lack.',
    ),
    sent(
        key='bilang_tidak_nafsu_makan', rel='dokter', fn='bilang_tidak_nafsu_makan',
        words=['二日', '前', 'から', '食欲', 'が', 'ありません', '。'],
        id_t='Sejak dua hari lalu tidak ada nafsu makan.', en_t='I have had no appetite for two days.',
        sit='Mengeluh tidak nafsu makan', sit_en='Reporting no appetite',
        note='食欲がない menyebut hilangnya nafsu makan; 食べたくない hanya berarti tidak ingin makan saat itu.',
        note_en='食欲がない names a loss of appetite; 食べたくない only means not wanting to eat right now.',
    ),
    sent(
        key='sejak_kapan', rel='dokter', fn='sejak_kapan',
        words=['症状', 'は', 'いつ', 'から', 'です', 'か', '。'],
        id_t='Gejalanya sejak kapan?', en_t='Since when have you had the symptoms?',
        sit='Dokter menanyakan awal gejala', sit_en='A doctor asking when symptoms began',
        note='いつからですか adalah pertanyaan pertama hampir setiap pemeriksaan; jawabannya menentukan arah diagnosis.',
        note_en='いつからですか is the first question in almost every examination and shapes the diagnosis.',
    ),
    sent(
        key='beli_obat', rel='apoteker', fn='beli_obat',
        words=['すみません', '、', '市販薬', 'で', '咳', 'に', '効く', 'もの', 'は', 'あります', 'か', '。'],
        id_t='Permisi, apakah ada obat bebas yang berkhasiat untuk batuk?', en_t='Excuse me, is there an over-the-counter medicine that works for a cough?',
        sit='Membeli obat batuk di apotek', sit_en='Buying cough medicine at a pharmacy',
        note='市販薬 adalah obat tanpa resep; 効くもの means something that works, jadi meminta khasiat bukan merek.',
        note_en='市販薬 is medicine without a prescription; 効くもの asks for something that works rather than a brand.',
    ),
    sent(
        key='tanya_obat_batuk', rel='apoteker', fn='tanya_obat_batuk',
        words=['子供', 'に', '飲ませる', 'の', 'です', 'が', '、', '大丈夫', 'です', 'か', '。'],
        id_t='Ini untuk diberikan kepada anak, apakah aman?', en_t='This is for a child, is it all right?',
        sit='Menanyakan keamanan obat untuk anak', sit_en='Asking whether medicine is safe for a child',
        note='飲ませる adalah bentuk kausatif dari 飲む: membuat orang lain minum, jadi tepat untuk obat anak.',
        note_en='飲ませる is the causative of 飲む, to make someone drink, which is right for a child\'s medicine.',
    ),
    sent(
        key='tanya_efek_samping', rel='apoteker', fn='tanya_efek_samping',
        words=['この', '薬', 'に', '副作用', 'は', 'あります', 'か', '。'],
        id_t='Apakah obat ini punya efek samping?', en_t='Does this medicine have side effects?',
        sit='Menanyakan efek samping obat', sit_en='Asking about side effects',
        note='副作用 adalah istilah baku untuk efek samping obat; menanyakannya di apotek adalah hal biasa.',
        note_en='副作用 is the standard term for a side effect; asking at the pharmacy is routine.',
    ),
    sent(
        key='tanya_boleh_minum', rel='apoteker', fn='tanya_boleh_minum',
        words=['まだ', '授乳中', 'です', 'が', '、', '飲んでも', 'いい', 'です', 'か', '。'],
        id_t='Saya masih menyusui, apakah boleh diminum?', en_t='I am still breastfeeding, may I take it?',
        sit='Menanyakan apakah obat aman saat menyusui', sit_en='Checking whether medicine is safe while breastfeeding',
        note='Menanyakan hal ini sebelum membeli jauh lebih aman daripada membacanya sendiri di kemasan.',
        note_en='Asking before buying is far safer than reading the package on your own.',
    ),
    sent(
        key='tanya_cara_minum', rel='apoteker', fn='tanya_cara_minum',
        words=['この', '薬', 'は', '食後', 'に', '飲みます', 'か', '。'],
        id_t='Apakah obat ini diminum setelah makan?', en_t='Is this medicine taken after meals?',
        sit='Menanyakan waktu minum obat', sit_en='Asking when to take the medicine',
        note='食後 berarti setelah makan, 食前 sebelum makan; keduanya berbeda dan salah satu bisa membuat obat kurang bekerja.',
        note_en='食後 is after meals and 食前 before; they differ, and picking the wrong one can blunt the effect.',
    ),
    sent(
        key='minta_resep', rel='dokter', fn='minta_resep',
        words=['この', '薬', 'が', '効かない', 'ので', '、', '別', 'の', 'を', '処方', 'して', 'もらえます', 'か', '。'],
        id_t='Obat ini tidak berkhasiat, bisakah diresepkan yang lain?', en_t='This medicine is not working, could you prescribe another one?',
        sit='Meminta obat lain karena yang sekarang tidak bekerja', sit_en='Asking for a different prescription because this one is not working',
        note='効かない menyatakan hasil, bukan keluhan tentang dokter; itu sebabnya kalimat ini tetap sopan.',
        note_en='効かない reports a result rather than criticising the doctor, which is what keeps it polite.',
    ),
    sent(
        key='buat_janji', rel='petugas_toko', fn='buat_janji',
        words=['すみません', '、', '今日', 'の', '午後', 'に', '診て', 'もらえます', 'か', '。'],
        id_t='Permisi, bisakah diperiksa sore ini?', en_t='Excuse me, could I be seen this afternoon?',
        sit='Membuat janji pemeriksaan hari ini', sit_en='Booking a same-day appointment',
        note='診てもらえますか meminta jasa diperiksa; 見てもらえますか untuk benda, bukan badan.',
        note_en='診てもらえますか asks to be examined; 見てもらえますか is for objects, not for your body.',
    ),
    sent(
        key='tanya_jam_praktik', rel='petugas_toko', fn='tanya_jam_praktik',
        words=['診療時間', 'は', '何時', 'まで', 'です', 'か', '。'],
        id_t='Jam praktiknya sampai jam berapa?', en_t='Until what time are you open?',
        sit='Menanyakan jam praktik klinik', sit_en='Asking a clinic\'s hours',
        note='診療時間 adalah jam praktik dokter; 営業時間 dipakai untuk toko, bukan klinik.',
        note_en='診療時間 is a clinic\'s consulting hours; 営業時間 is for shops, not clinics.',
    ),
    sent(
        key='daftar_klinik', rel='petugas_toko', fn='daftar_klinik',
        words=['初めて', 'です', '。', '保険証', 'を', '出します', '。'],
        id_t='Ini pertama kali saya ke sini. Saya serahkan kartu asuransi.', en_t='This is my first visit. Here is my insurance card.',
        sit='Mendaftar di klinik untuk pertama kali', sit_en='Registering at a clinic for the first time',
        note='Di Jepang, 初めてです pada kunjungan pertama memicu formulir tambahan; menyebutkannya menghemat waktu.',
        note_en='In Japan, 初めてです on a first visit triggers extra paperwork, so saying it saves time.',
    ),
    sent(
        key='jelaskan_gejala_dokter', rel='dokter', fn='jelaskan_gejala_dokter', long=True,
        words=['三日前', 'から', '熱', 'が', 'あって', '、', '昨日', 'から', '咳', 'も', '出て', 'きました', '。'],
        id_t='Sejak tiga hari lalu demam, dan sejak kemarin batuknya juga muncul.', en_t='I have had a fever for three days, and since yesterday a cough has started too.',
        sit='Menjelaskan urutan gejala kepada dokter', sit_en='Describing the sequence of symptoms to a doctor',
        note='あって…も出てきました menyusun gejala menurut waktu, yang jauh lebih berguna daripada menyebut semuanya sekaligus.',
        note_en='あって…も出てきました orders the symptoms in time, which is far more useful than listing them at once.',
    ),
    sent(
        key='jawab_sejak_kapan', rel='dokter', fn='jawab_sejak_kapan',
        words=['おととい', 'の', '夜', 'から', 'です', '。'],
        id_t='Sejak malam dua hari lalu.', en_t='Since the night before last.',
        sit='Menjawab sejak kapan sakit', sit_en='Answering when the symptoms began',
        note='おととい adalah dua hari lalu; kemarin adalah 昨日, dan keduanya sering tertukar saat panik.',
        note_en='おととい is the day before yesterday and 昨日 is yesterday; the two get mixed up under stress.',
    ),
    sent(
        key='jawab_dimana_sakit', rel='dokter', fn='jawab_dimana_sakit',
        words=['ここ', 'です', '。', '押される', 'と', '痛い', 'です', '。'],
        id_t='Di sini. Kalau ditekan sakit.', en_t='Here. It hurts when pressed.',
        sit='Menjawab di mana yang sakit', sit_en='Pointing out where it hurts',
        note='押されると痛い adalah keterangan yang langsung mengarah ke peradangan; menunjuk sambil mengatakannya paling cepat.',
        note_en='押されると痛い points straight at inflammation; pointing while saying it is fastest.',
    ),
    sent(
        key='tanya_penyebab', rel='dokter', fn='tanya_penyebab',
        words=['原因', 'は', '何', 'です', 'か', '。'],
        id_t='Penyebabnya apa?', en_t='What is the cause?',
        sit='Menanyakan penyebab penyakit', sit_en='Asking what caused the illness',
        note='原因 adalah penyebab; 理由 adalah alasan. Untuk penyakit, 原因 yang dipakai.',
        note_en='原因 is a cause and 理由 is a reason; for illness, 原因 is the word used.',
    ),
    sent(
        key='tanya_istirahat', rel='dokter', fn='tanya_istirahat',
        words=['仕事', 'を', '休んだ', 'ほう', 'が', 'いい', 'です', 'か', '。'],
        id_t='Sebaiknya saya tidak masuk kerja?', en_t='Should I take time off work?',
        sit='Menanyakan apakah perlu berhenti bekerja sementara', sit_en='Asking whether to take time off work',
        note='休んだ ほう がいい adalah saran bentuk lampau; dokter memakainya untuk memberi anjuran yang tegas.',
        note_en='休んだ ほう がいい is past-form advice; doctors use it for a firm recommendation.',
    ),
    sent(
        key='minta_keterangan', rel='dokter', fn='minta_keterangan',
        words=['会社', 'に', '出す', '診断書', 'を', '書いて', 'いただけます', 'か', '。'],
        id_t='Bisakah dituliskan surat keterangan dokter untuk kantor?', en_t='Could you write a doctor\'s note for my workplace?',
        sit='Meminta surat keterangan sakit', sit_en='Asking for a sick note',
        note='診断書 adalah surat keterangan dokter; kantor Jepang biasanya memintanya kalau absen lebih dari beberapa hari.',
        note_en='診断書 is a doctor\'s note; Japanese workplaces usually ask for one if you are absent more than a few days.',
    ),
    sent(
        key='tanya_sembuh', rel='dokter', fn='tanya_sembuh',
        words=['どのくらい', 'で', '治ります', 'か', '。'],
        id_t='Berapa lama sampai sembuh?', en_t='How long until it gets better?',
        sit='Menanyakan perkiraan waktu sembuh', sit_en='Asking how long recovery will take',
        note='どのくらいで治りますか menanyakan lama sampai pulih; いつ治りますか menanyakan tanggal dan lebih menuntut kepastian.',
        note_en='どのくらいで治りますか asks roughly how long; いつ治りますか asks for a date and demands more certainty.',
    ),
    sent(
        key='dengar_diagnosis', rel='dokter', fn='dengar_diagnosis',
        words=['分かりました', '。', '説明', 'を', 'お願いします', '。'],
        id_t='Baik. Tolong jelaskannya.', en_t='Understood. Please explain.',
        sit='Meminta penjelasan diagnosis', sit_en='Asking for the diagnosis to be explained',
        note='説明をお願いします adalah cara meminta penjelasan yang tenang, tanpa menuntut jawaban tertentu.',
        note_en='説明をお願いします calmly asks for an explanation without demanding a particular answer.',
    ),
    sent(
        key='tanya_tes', rel='dokter', fn='tanya_tes',
        words=['血液検査', 'は', '必要', 'です', 'か', '。'],
        id_t='Apakah perlu tes darah?', en_t='Do I need a blood test?',
        sit='Menanyakan apakah perlu pemeriksaan tambahan', sit_en='Asking whether a test is needed',
        note='必要ですか menanyakan keperluan, jadi tidak terdengar seperti menolak pemeriksaan.',
        note_en='必要ですか asks whether it is necessary, so it does not sound like refusing the test.',
    ),
    sent(
        key='tanya_obat_anak', rel='dokter', fn='tanya_obat_anak',
        words=['子供', 'が', '同じ', '症状', 'です', 'が', '、', '同じ', '薬', 'で', 'いい', 'です', 'か', '。'],
        id_t='Anak saya gejalanya sama, boleh obat yang sama?', en_t='My child has the same symptoms, is the same medicine all right?',
        sit='Menanyakan apakah obat orang dewasa aman untuk anak', sit_en='Checking whether an adult medicine suits a child',
        note='Dosis anak berbeda dari orang dewasa, jadi pertanyaan ini tidak berlebihan meski gejalanya sama.',
        note_en='Children\'s doses differ from adults\', so this question is not excessive even when symptoms match.',
    ),
    sent(
        key='ingatkan_istirahat', rel='rekan', fn='ingatkan_istirahat',
        words=['無理', 'を', 'しないで', '、', '今日', 'は', '早く', '寝て', 'ください', '。'],
        id_t='Jangan memaksakan diri, malam ini tidurlah lebih awal.', en_t='Do not overdo it, get to bed early tonight.',
        sit='Mengingatkan rekan yang sakit untuk istirahat', sit_en='Telling an unwell colleague to rest',
        note='無理をしないで adalah ungkapan perhatian yang baku; がんばって justru bertolak belakang maksudnya.',
        note_en='無理をしないで is the standard phrase of concern; がんばって would mean the opposite.',
    ),
    sent(
        key='tawarkan_antar', rel='rekan', fn='tawarkan_antar',
        words=['よかったら', '、', '病院', 'まで', '車', 'で', '連れて', '行きます', 'よ', '。'],
        id_t='Kalau mau, saya antar ke rumah sakit dengan mobil.', en_t='If you like, I will drive you to the hospital.',
        sit='Menawarkan mengantar ke rumah sakit', sit_en='Offering a lift to the hospital',
        note='よかったら membuat tawaran mudah ditolak; menawarkan antar adalah hal biasa antar rekan di Jepang.',
        note_en='よかったら makes the offer easy to decline; giving a lift is a normal favour between colleagues in Japan.',
    ),
    sent(
        key='tanya_kabar_sakit', rel='rekan', fn='tanya_kabar_sakit',
        words=['具合', 'は', 'どう', 'です', 'か', '。', 'もう', 'よくなりました', 'か', '。'],
        id_t='Bagaimana kondisi Anda? Sudah membaik?', en_t='How are you feeling? Any better?',
        sit='Menanyakan kabar rekan yang sakit', sit_en='Checking on a colleague who was ill',
        note='具合はどうですか menanyakan badan, bukan kehidupan secara umum; itu yang tepat untuk orang sakit.',
        note_en='具合はどうですか asks about the body rather than life in general, which is right for someone who was ill.',
    ),
    sent(
        key='bilang_sudah_membaik', rel='rekan', fn='bilang_sudah_membaik',
        words=['おかげさまで', '、', 'もう', 'ほとんど', '治りました', '。'],
        id_t='Berkat Anda, sudah hampir sembuh.', en_t='Thanks to you, I am almost better.',
        sit='Menjawab bahwa sudah membaik', sit_en='Reporting that you are better',
        note='ほとんど治りました berarti hampir sembuh, jadi tidak berlebihan; 完全に治りました jarang dan terdengar kaku.',
        note_en='ほとんど治りました means almost recovered, so it does not overstate; 完全に治りました is rare and stiff.',
    ),
    sent(
        key='bilang_belum_membaik', rel='rekan', fn='bilang_belum_membaik',
        words=['まだ', 'あまり', 'よく', 'ありません', '。', '薬', 'も', '効いて', 'いない', 'みたい', 'です', '。'],
        id_t='Belum begitu membaik. Obatnya juga sepertinya tidak bekerja.', en_t='Not much better yet. The medicine does not seem to be working either.',
        sit='Mengabari bahwa belum membaik', sit_en='Reporting that you are not better yet',
        note='あまり…ありません adalah bentuk "tidak begitu"; よくありません saja akan terdengar terlalu keras.',
        note_en='あまり…ありません is the not very form; よくありません alone would sound too blunt.',
    ),
    sent(
        key='pesan_jangan_memaksa', rel='rekan', fn='pesan_jangan_memaksa', long=True,
        words=['熱', 'が', 'ある', 'なら', '、', '無理', 'を', 'しないで', '、', '今日', 'は', 'ゆっくり', '休んで', 'ください', '。'],
        id_t='Kalau demam, jangan memaksakan diri, hari ini istirahatlah dengan tenang.', en_t='If you have a fever, do not push yourself, just rest today.',
        sit='Memesan rekan yang demam agar istirahat', sit_en='Telling a feverish colleague to rest',
        note='なら menjadikan demam sebagai syarat, jadi nasihatnya bersyarat dan tidak terdengar seperti perintah.',
        note_en='なら makes the fever a condition, so the advice is conditional rather than an order.',
    ),
    sent(
        key='sarankan_ke_dokter', rel='teman', fn='sarankan_ke_dokter', long=True,
        words=['一週間', 'も', '続いて', 'いる', 'なら', '、', '一度', '病院', 'に', '行った', 'ほう', 'が', 'いい', 'よ', '。'],
        id_t='Kalau sudah seminggu, sebaiknya sekali periksa ke rumah sakit.', en_t='If it has lasted a week, you should see a doctor.',
        note='一週間も続いている なら menyebut lamanya sebagai alasan; も di sini menekankan bahwa itu sudah lama.',
        note_en='一週間も続いている なら gives the duration as the reason; the も stresses that it is a long time.',
        sit='Menyarankan ke dokter untuk keluhan yang lama', sit_en='Suggesting a doctor for a lasting complaint',
    ),
    sent(
        key='tanya_apakah_serius', rel='dokter', fn='tanya_apakah_serius',
        words=['この', 'まま', '様子', 'を', '見て', 'いれば', '大丈夫', 'です', 'か', '。'],
        id_t='Kalau begini terus, apakah tidak apa-apa?', en_t='If it stays like this, is that all right?',
        sit='Menanyakan apakah keadaannya perlu dikhawatirkan', sit_en='Asking whether the situation is serious',
        note='様子を見る (melihat perkembangan) adalah saran medis yang lazim; menanyakannya menunjukkan Anda mengerti.',
        note_en='様子を見る (see how it goes) is a common medical suggestion, and asking about it shows you understood.',
    ),
    sent(
        key='bilang_obat_tidak_berkhasiat', rel='dokter', fn='bilang_obat_tidak_berkhasiat',
        words=['この', '薬', 'を', '飲んで', 'います', 'が', '、', '全然', '効きません', '。'],
        id_t='Saya sudah minum obat ini, tapi sama sekali tidak berkhasiat.', en_t='I have been taking this medicine, but it does not work at all.',
        sit='Melaporkan obat yang tidak bekerja', sit_en='Reporting medicine that is not working',
        note='飲んでいます adalah bentuk berlanjut: sudah dan masih diminum. 飲みました hanya berarti pernah diminum.',
        note_en='飲んでいます is the ongoing form: still being taken. 飲みました would only mean it was taken once.',
    ),
    sent(
        key='syukuri_sembuh', rel='teman', fn='syukuri_sembuh',
        words=['よかった', '。', '心配', 'した', 'よ', '。'],
        id_t='Syukurlah. Saya khawatir.', en_t='I am glad. I was worried.',
        sit='Menyampaikan kelegaan setelah teman sembuh', sit_en='Expressing relief that a friend recovered',
        note='よかった di sini berarti "syukurlah", bukan "bagus"; nada lega itu ditentukan konteks kalimat sebelumnya.',
        note_en='よかった here means thank goodness rather than good; the tone of relief comes from the context.',
    ),
]
