#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Kantor: the working day, from arriving to asking for leave.

The functions follow the working day rather than a grammar list, and they separate the two
registers that a workplace actually uses in different directions: speaking UP to a superior
and speaking ACROSS to a colleague are different sentences, and the request forms differ
again when you are asking for time off. Asking for leave politely, and being told a report
has a mistake, are the two situations people most want pre-written sentences for, so both are
given their own functions rather than folded into anything else.
"""
from compose import sent, add_words

add_words({
    '出社': ('shussha', 'masuk kerja', 'coming to the office'),
    '退社': ('taisha', 'pulang kerja', 'leaving the office'),
    '在宅': ('zaitaku', 'bekerja dari rumah', 'working from home'),
    '打ち合わせ': ('uchiawase', 'rapat koordinasi', 'a short working meeting'),
    '資料': ('shiryou', 'materi / dokumen', 'materials / documents'),
    '報告': ('houkoku', 'laporan', 'report'),
    '確認': ('kakunin', 'konfirmasi', 'confirmation'),
    '締め切り': ('shimekiri', 'tenggat', 'deadline'),
    '期限': ('kigen', 'batas waktu', 'time limit'),
    '進捗': ('shinchoku', 'kemajuan', 'progress'),
    '担当': ('tantou', 'penanggung jawab', 'person in charge'),
    '上司': ('joushi', 'atasan', 'superior'),
    '課長': ('kachou', 'kepala seksi', 'section chief'),
    '先輩': ('senpai', 'senior', 'senior colleague'),
    '後輩': ('kouhai', 'junior', 'junior colleague'),
    'お世話になっております': ('osewa ni natte orimasu', 'terima kasih atas bantuannya (sopan)', 'thank you for your continued support'),
    '承知しました': ('shouchi shimashita', 'baik, saya mengerti (sopan)', 'understood (very polite)'),
    '確認します': ('kakunin shimasu', 'saya akan konfirmasi', 'I will check'),
    '確認して': ('kakunin shite', 'konfirmasi (bentuk -te)', 'check (te-form)'),
    '確認いたします': ('kakunin itashimasu', 'saya akan konfirmasi (merendah)', 'I will check (humble)'),
    '添付': ('tenpu', 'lampiran', 'attachment'),
    '添付しました': ('tenpu shimashita', 'melampirkan (lampau sopan)', 'attached (polite past)'),
    '共有': ('kyouyuu', 'berbagi (informasi)', 'sharing'),
    '共有します': ('kyouyuu shimasu', 'membagikan (sopan)', 'share (polite)'),
    '締め切りに間に合います': ('shimekiri ni maniaimasu', 'sempat sebelum tenggat', 'make the deadline'),
    '間に合いません': ('maniaimasen', 'tidak sempat (sopan)', 'will not make it (polite)'),
    '任せて': ('makasete', 'serahkan pada saya (bentuk -te)', 'leave it to me (te-form)'),
    '任せてください': ('makasete kudasai', 'tolong serahkan pada saya', 'please leave it to me'),
    '直します': ('naoshimasu', 'memperbaiki (sopan)', 'fix (polite)'),
    '直して': ('naoshite', 'memperbaiki (bentuk -te)', 'fix (te-form)'),
    '直しました': ('naoshimashita', 'memperbaiki (lampau sopan)', 'fixed (polite past)'),
    '間違い': ('machigai', 'kesalahan', 'mistake'),
    '訂正': ('teisei', 'koreksi', 'correction'),
    '指摘': ('shiteki', 'menunjukkan / menunjuk', 'pointing out'),
    '助かります': ('tasukarimasu', 'sangat menolong (sopan)', 'that helps (polite)'),
    '遅れそうです': ('okure sou desu', 'sepertinya akan terlambat', 'looks like I will be late'),
    '休ませて': ('yasumasete', 'membiarkan saya istirahat (-te)', 'let me rest (te-form)'),
    '休ませてください': ('yasumasete kudasai', 'izinkan saya istirahat', 'please let me take leave'),
    '有給': ('yuukyuu', 'cuti berbayar', 'paid leave'),
    '有給休暇': ('yuukyuu kyuuka', 'cuti berbayar (lengkap)', 'paid leave (full term)'),
    '取ります': ('torimasu', 'mengambil (sopan)', 'take (polite)'),
    '取りたい': ('toritai', 'ingin mengambil', 'want to take'),
    '構いません': ('kamaimasen', 'tidak masalah (sopan)', 'that is fine (polite)'),
    '申し訳ありません': ('moushiwake arimasen', 'mohon maaf (sopan)', 'I am very sorry (polite)'),
    '申し訳ございません': ('moushiwake gozaimasen', 'mohon maaf (paling sopan)', 'I am very sorry (most polite)'),
    'いかがでしょうか': ('ikaga deshou ka', 'bagaimana menurut Anda (sopan)', 'would that be all right (polite)'),
    '予定が入っています': ('yotei ga haitte imasu', 'sudah ada jadwal', 'already have plans'),
    '対応': ('taiou', 'penanganan', 'handling'),
    '対応します': ('taiou shimasu', 'menangani (sopan)', 'handle (polite)'),
    '対応して': ('taiou shite', 'menangani (bentuk -te)', 'handle (te-form)'),
    '対応いたします': ('taiou itashimasu', 'menangani (merendah)', 'handle (humble)'),
    '代わり': ('kawari', 'gantinya / pengganti', 'instead / substitute'),
    '代わりに': ('kawari ni', 'sebagai gantinya', 'instead'),
    '引き継ぎ': ('hikitsugi', 'serah terima pekerjaan', 'handover'),
    '引き継ぎます': ('hikitsugimasu', 'meneruskan pekerjaan (sopan)', 'take over (polite)'),
    '引き継いで': ('hikitsui de', 'meneruskan (bentuk -te)', 'take over (te-form)'),
    '伺います': ('ukagaimasu', 'bertanya / berkunjung (merendah)', 'ask / visit (humble)'),
    '伺って': ('ukagatte', 'bertanya (bentuk -te)', 'ask (te-form)'),
    '拝見': ('haiken', 'melihat (merendah)', 'look at (humble)'),
    '拝見しました': ('haiken shimashita', 'sudah saya lihat (merendah)', 'I have looked (humble past)'),
    'いたします': ('itashimasu', 'melakukan (merendah)', 'do (humble)'),
    'いただけますか': ('itadakemasu ka', 'boleh saya minta (sopan)', 'could I have (humble)'),
    'させていただきます': ('sasete itadakimasu', 'izinkan saya melakukan (merendah)', 'please let me do (humble)'),
    '欠席': ('kesseki', 'tidak hadir', 'absence'),
    '出張します': ('shucchou shimasu', 'pergi dinas (sopan)', 'go on a business trip (polite)'),
    '先に': ('saki ni', 'lebih dulu', 'beforehand / first'),
    '終わりました': ('owarimashita', 'berakhir (lampau)', 'ended (polite past)'),
    '始めましょう': ('hajimemashou', 'mari mulai', 'let us begin'),
    'ましょうか': ('mashou ka', 'apakah saya lakukan', 'shall I'),
    'ですか': ('desu ka', 'adalah? (tanya sopan)', 'is it? (polite question)'),
    '午前': ('gozen', 'pagi (AM)', 'morning (AM)'),
    '午後': ('gogo', 'siang/sore (PM)', 'afternoon (PM)'),
    '二時': ('niji', 'jam dua', 'two o\'clock'),
    '十時': ('juuji', 'jam sepuluh', 'ten o\'clock'),
    '分かりにくい': ('wakarini kui', 'sulit dimengerti', 'hard to understand'),
    'もう一度': ('mou ichido', 'sekali lagi', 'once more'),
    '教えて': ('oshiete', 'memberi tahu (bentuk -te)', 'tell (te-form)'),
    '教えていただけますか': ('oshiete itadakemasu ka', 'boleh diberi tahu (sangat sopan)', 'could you tell me (very polite)'),
    '質問': ('shitsumon', 'pertanyaan', 'question'),
    '質問があります': ('shitsumon ga arimasu', 'ada pertanyaan', 'have a question'),
    '問題': ('mondai', 'masalah', 'problem'),
    '問題ありません': ('mondai arimasen', 'tidak ada masalah', 'no problem'),
    '次回': ('jikai', 'pertemuan berikutnya', 'next time'),
    '資料を送ります': ('shiryou o okurimasu', 'mengirim materi (sopan)', 'send the materials (polite)'),
    '折り返し': ('orikaeshi', 'balasan (panggilan)', 'a return call'),
    '折り返しお電話します': ('orikaeshi odenwa shimasu', 'saya akan menelepon balik', 'I will call back'),
    '伝言': ('dengon', 'pesan', 'message'),
    '伝言をお願いします': ('dengon o onegai shimasu', 'tolong sampaikan pesan', 'please pass on a message'),
    '席を外しています': ('seki o hazushite imasu', 'sedang tidak di tempat', 'is away from the desk'),
    '外出中': ('gaishutsuchuu', 'sedang keluar', 'out of the office'),
    '席にいます': ('seki ni imasu', 'ada di tempat duduk', 'is at the desk'),
    'よろしいでしょうか': ('yoroshii deshou ka', 'apakah tidak masalah (sopan)', 'would that be all right (polite)'),
    'お時間': ('ojikan', 'waktu (sopan)', 'time (polite)'),
    'お時間をいただけますか': ('ojikan o itadakemasu ka', 'boleh minta waktunya', 'could I have some of your time'),
    '少しだけ': ('sukoshi dake', 'hanya sebentar', 'just a little'),
    'お疲れ様でした': ('otsukaresama deshita', 'terima kasih atas kerja kerasnya (lampau)', 'thanks for your hard work (past)'),
    '金曜日': ('kinyoubi', 'Jumat', 'Friday'),
    '通院': ('tsuuin', 'kontrol ke dokter', 'hospital visits'),
    '変えて': ('kaete', 'menukar / mengubah (bentuk -te)', 'change (te-form)'),
    'もらえます': ('moraemasu', 'bisa minta (sopan)', 'can receive (polite)'),
    '月曜': ('getsuyoubi', 'Senin', 'Monday'),
    '設定したい': ('settei shitai', 'ingin mengatur', 'want to set up'),
    '八割': ('hachiwari', 'delapan puluh persen', 'eighty per cent'),
    'かかって': ('kakatte', 'memerlukan (bentuk -te)', 'take (te-form)'),
    '二日': ('futsuka', 'dua hari', 'two days'),
    '延ばして': ('nobashite', 'memundurkan (bentuk -te)', 'extend (te-form)'),
    'もらう': ('morau', 'menerima (biasa)', 'receive (plain)'),
    'ご指摘': ('goshiteki', 'koreksi / penunjukan (sopan)', 'pointing out (polite)'),
    '何か': ('nanika', 'sesuatu', 'something'),
    'ありましたら': ('arimashitara', 'kalau ada (sopan)', 'if there is (polite)'),
    'お手数ですが': ('otesuu desu ga', 'mohon maaf merepotkan', 'sorry to trouble you'),
    '内容': ('naiyou', 'isi / konten', 'contents'),
    'ご確認ください': ('gokakunin kudasai', 'mohon diperiksa (sopan)', 'please check (polite)'),
    '送った': ('okutta', 'mengirim (biasa, lampau)', 'sent (plain past)'),
    'ご覧になりました': ('goran ni narimashita', 'melihat (hormat, lampau)', 'looked at (honorific past)'),
    '決まりましたか': ('kimarimashita ka', 'sudah ditetapkan?', 'has it been decided?'),
    '入っています': ('haitte imasu', 'sudah terisi (ada acara)', 'is already taken (has a plan)'),
    '出られません': ('deraremasen', 'tidak bisa hadir (sopan)', 'cannot attend (polite)'),
    '田中': ('tanaka', 'Tanaka (nama keluarga)', 'Tanaka (a surname)'),
    'さん': ('san', 'Pak/Bu (sebutan sopan)', 'Mr/Ms (polite suffix)'),
    '出席': ('shusseki', 'kehadiran', 'attendance'),
    'いらっしゃいます': ('irasshaimasu', 'ada / hadir (hormat)', 'is present (honorific)'),
    'お電話': ('odenwa', 'telepon (sopan)', 'telephone (polite)'),
    'いただきたい': ('itadakitai', 'ingin menerima (merendah)', 'would like to receive (humble)'),
    'ご': ('go', 'awalan sopan', 'polite prefix'),
    '依頼': ('irai', 'permintaan (kerja)', 'request'),
    '先ほど': ('sakihodo', 'tadi (sopan)', 'a little while ago (polite)'),
    'まま': ('mama', 'tetap dalam keadaan', 'as it is'),
    '優先順位': ('yuusen jun-i', 'urutan prioritas', 'priority order'),
    'させて': ('sasete', 'membiarkan melakukan (kausatif -te)', 'let me do (causative te-form)'),
    '手': ('te', 'tangan', 'hand'),
    '離せなくて': ('hanasenakute', 'tidak bisa dilepas (bentuk -te)', 'cannot let go (te-form)'),
    'お受けできません': ('ouke dekimasen', 'tidak bisa menerima (sopan)', 'cannot accept (polite)'),
    '同時': ('douji', 'bersamaan', 'at the same time'),
    'すれば': ('sureba', 'kalau melakukan', 'if one does'),
    'いいでしょうか': ('ii deshou ka', 'apakah boleh (sopan)', 'would that be all right (polite)'),
    'いっぱい': ('ippai', 'penuh', 'full'),
    'くれて': ('kurete', 'memberi untuk saya (bentuk -te)', 'do for me (te-form)'),
    '本当': ('hontou', 'benar / sungguh', 'really / true'),
    'あれば': ('areba', 'kalau ada', 'if there is'),
    '戻られたら': ('modoraretara', 'kalau sudah kembali (hormat)', 'once you return (honorific)'),
    'お世話になります': ('osewa ni narimasu', 'terima kasih atas bantuannya (sopan)', 'thank you for your support (polite)'),
    'アリ': ('ari', 'Ari (nama)', 'Ari (a name)'),
    'よろしく': ('yoroshiku', 'mohon bantuannya (pembuka)', 'please treat me well'),
    '部分': ('bubun', 'bagian', 'part'),
    'ほど': ('hodo', 'sekitar / kira-kira', 'about / approximately'),
    '先': ('saki', 'sebelah sana / ujung', 'beyond / ahead'),
    '部署': ('busho', 'divisi', 'department'),
    'よく': ('yoku', 'sering', 'often'),
    '残業します': ('zangyou shimasu', 'lembur (sopan)', 'work overtime (polite)'),
    '普段': ('fusan', 'biasanya', 'usually'),
    'やっています': ('yatte imasu', 'sedang melakukan (sopan)', 'am doing (polite)'),
    '終わらせる': ('owaraseru', 'menyelesaikan (biasa)', 'finish (plain)'),
    'ために': ('tame ni', 'untuk / demi', 'in order to'),
    'お先に': ('osaki ni', 'lebih dulu (pamit)', 'before you (taking leave)'),
    'ご都合': ('gotsugou', 'kesediaan waktu (sopan)', 'availability (polite)'),
    'いかがですか': ('ikaga desu ka', 'bagaimana (sopan)', 'how about (polite)'),
    'お願いできますか': ('onegai dekimasu ka', 'bisakah diminta (sopan)', 'could I ask you (polite)'),
    'ご確認': ('gokakunin', 'pemeriksaan (sopan)', 'checking (polite)'),
    '終わらせます': ('owarasemasu', 'menyelesaikan (sopan)', 'finish (polite)'),
    '連絡': ('renraku', 'hubungan / kontak', 'contact'),
    '助かりました': ('tasukarimashita', 'sangat terbantu (lampau sopan)', 'was a great help'),
    '上がります': ('agarimasu', 'naik (sopan)', 'rises (polite)'),
    '無理です': ('muri desu', 'tidak bisa (sopan)', 'cannot (polite)'),
    '難しいです': ('muzukashii desu', 'sulit (sopan)', 'difficult (polite)'),
    '参加します': ('sanka shimasu', 'ikut serta (sopan)', 'take part (polite)'),
    '終わらせて': ('owarasete', 'menyelesaikan (bentuk -te)', 'finish (te-form)'),
})

SINGLE_WORDS = {
    'お疲れ様です': 'sapaan kerja baku, satu kesatuan',
    'お世話になっております': 'sapaan kerja baku lewat telepon/surel',
    'よろしくお願いします': 'ungkapan penutup permintaan, satu kesatuan',
    '承知しました': 'bentuk persetujuan sopan, satu kesatuan',
    'かしこまりました': 'bentuk persetujuan paling sopan, satu kesatuan',
    '確認いたします': 'bentuk merendah dari 確認します',
    '対応いたします': 'bentuk merendah dari 対応します',
    'いたします': 'bentuk merendah dari します',
    'させていただきます': 'bentuk izin merendah, satu kesatuan',
    '申し訳ありません': 'permintaan maaf sopan, satu kesatuan',
    '申し訳ございません': 'permintaan maaf paling sopan, satu kesatuan',
    '休ませてください': 'permintaan izin cuti, satu kesatuan',
    'お先に': 'ungkapan pamit, satu kesatuan',
    'いかがでしょうか': 'bentuk sopan dari どうですか',
    'よろしいでしょうか': 'bentuk sopan dari いいですか',
    '折り返しお電話します': 'ungkapan telepon baku, satu kesatuan',
    '伝言をお願いします': 'ungkapan telepon baku, satu kesatuan',
    '席を外しています': 'ungkapan kantor baku (sedang tidak di tempat)',
    '外出中': 'satu kata majemuk (sedang keluar)',
    '手伝いましょうか': 'tawaran bantuan, satu kesatuan',
    '任せてください': 'ungkapan menerima tugas, satu kesatuan',
    '教えていただけますか': 'permintaan sopan sebagai satu kesatuan',
    'お時間をいただけますか': 'permintaan waktu secara sopan',
    '質問があります': 'ungkapan tetap (ada pertanyaan)',
    'お願いできますか': 'permintaan sopan sebagai satu kesatuan',
    'ご覧になりました': 'bentuk hormat dari 見ました',
    'お受けできません': 'bentuk sopan penolakan (tidak bisa menerima)',
    'お世話になります': 'sapaan kerja baku, satu kesatuan',
    '問題ありません': 'ungkapan tetap (tidak ada masalah)',
    '有給休暇': 'satu kata majemuk (cuti berbayar)',
    '打ち合わせ': 'satu kata (rapat koordinasi)',
    '引き継ぎ': 'satu kata (serah terima)',
    '引き継ぎます': 'satu kata kerja majemuk, bukan frasa',
    '拝見しました': 'bentuk merendah dari 見ました',
    '伝言': 'satu kata (pesan)',
    '折り返し': 'satu kata (balasan panggilan)',
    '残業': 'satu kata (kerja lembur)',
    '締め切り': 'satu kata (tenggat)',
    '在宅': 'satu kata (bekerja dari rumah)',
    '出社': 'satu kata (masuk kerja)',
    '退社': 'satu kata (pulang kerja)',
}

SET_PHRASES = {
    'sapa_pagi_kantor': 'お疲れ様です adalah sapaan kantor baku tanpa predikat',
}

FUNCTIONS = {
    'sapa_pagi_kantor': 'menyapa rekan di kantor',
    'pamit_pulang_kerja': 'berpamit pulang lebih dulu',
    'lapor_masuk': 'melaporkan sudah masuk kerja',
    'lapor_telat': 'memberi tahu akan terlambat',
    'minta_izin_cuti': 'meminta izin cuti',
    'ajukan_cuti_berbayar': 'mengajukan cuti berbayar',
    'atur_waktu_rapat': 'mengatur waktu rapat',
    'ubah_jadwal_rapat': 'mengubah jadwal rapat',
    'ajak_rapat': 'mengajak rapat',
    'minta_waktu_bicara': 'meminta waktu bicara sebentar',
    'lapor_kemajuan': 'melaporkan kemajuan pekerjaan',
    'minta_perpanjangan': 'meminta perpanjangan tenggat',
    'serahkan_tugas': 'menyerahkan tugas',
    'tawarkan_bantuan': 'menawarkan bantuan ke rekan',
    'terima_koreksi': 'menerima koreksi atas kesalahan',
    'tanya_masalah': 'menanyakan apakah ada masalah',
    'minta_konfirmasi': 'meminta konfirmasi',
    'kirim_materi': 'mengirim materi rapat',
    'tanya_sudah_lihat': 'menanyakan apakah materi sudah dilihat',
    'tanya_jadwal': 'menanyakan jadwal',
    'hadir_tidak_rapat': 'mengatakan tidak bisa hadir rapat',
    'minta_wakil_rapat': 'meminta orang lain mewakili rapat',
    'tanya_ada_di_tempat': 'menanyakan apakah orang ada di tempat',
    'tinggalkan_pesan': 'meninggalkan pesan lewat telepon',
    'lapor_selesai': 'melaporkan pekerjaan sudah selesai',
    'paham_instruksi': 'menyatakan mengerti instruksi',
    'tanya_ulang_instruksi': 'meminta instruksi diulang',
    'komplain_tidak_sempat': 'mengatakan tidak akan sempat',
    'tolak_permintaan': 'menolak permintaan dengan sopan',
    'tanya_prioritas': 'menanyakan mana yang harus didahulukan',
    'bilang_sibuk': 'mengatakan sedang sibuk',
    'bilang_luang': 'mengatakan sedang ada waktu',
    'syukuri_bantuan': 'berterima kasih atas bantuan rekan',
    'bilang_bisa_dihubungi': 'mengatakan bisa dihubungi',
    'minta_dihubungi_kembali': 'meminta dihubungi kembali',
    'perkenalkan_diri_kantor': 'memperkenalkan diri di kantor',
    'bilang_belum_paham': 'mengatakan belum paham',
    'tanya_cara_kerja': 'menanyakan cara kerja di kantor',
    'lapor_kerja_lembur': 'melaporkan akan lembur',
}

SENTENCES = [
    sent(
        key='sapa_pagi_kantor', rel='rekan', fn='sapa_pagi_kantor',
        words=['お疲れ様です', '。'],
        id_t='Selamat pagi (sapaan kantor).', en_t='Good morning (office greeting).',
        sit='Menyapa rekan kerja saat masuk kantor', sit_en='Greeting a colleague on arriving at work',
        note='Di kantor Jepang, お疲れ様です dipakai sepanjang hari termasuk pagi; おはようございます juga dipakai tapi lebih untuk kantor yang santai.',
        note_en='In a Japanese office お疲れ様です works all day including the morning; おはようございます is used too but suits a more casual office.',
    ),
    sent(
        key='pamit_pulang_kerja', rel='rekan', fn='pamit_pulang_kerja',
        words=['お先に', '失礼します', '。', 'お疲れ様でした', '。'],
        id_t='Permisi saya pulang duluan. Terima kasih atas kerja kerasnya.', en_t='Excuse me for leaving first. Thank you for your hard work.',
        sit='Pulang lebih dulu dari kantor', sit_en='Leaving the office before everyone else',
        note='Dua kalimat ini dipasangkan saat pulang lebih dulu; hanya mengucapkan salah satunya terdengar tidak lengkap.',
        note_en='These two come as a pair when leaving early; saying only one of them sounds incomplete.',
    ),
    sent(
        key='lapor_masuk', rel='atasan', fn='lapor_masuk',
        words=['おはようございます', '。', '今日', 'は', '在宅', 'で', '失礼します', '。'],
        id_t='Selamat pagi. Hari ini saya bekerja dari rumah.', en_t='Good morning. I will be working from home today.',
        sit='Memberi tahu atasan bekerja dari rumah', sit_en='Telling a superior you are working from home',
        note='在宅で失礼します adalah bentuk baku untuk memberi tahu bekerja dari rumah; 在宅します terdengar kurang lazim.',
        note_en='在宅で失礼します is the standard way to announce working from home; 在宅します sounds unusual.',
    ),
    sent(
        key='lapor_telat', rel='atasan', fn='lapor_telat',
        words=['おはようございます', '。', '電車', 'が', '遅れて', 'いる', 'ので', '、', '少し', '遅れそうです', '。'],
        id_t='Selamat pagi. Keretanya terlambat, jadi sepertinya saya akan telat sedikit.', en_t='Good morning. The train is delayed, so I may be a little late.',
        sit='Memberi tahu atasan akan terlambat', sit_en='Telling a superior you will be late',
        note='Mengabari lebih awal jauh lebih penting daripada alasannya; 遅れそうです menyatakan perkiraan, bukan kepastian.',
        note_en='Warning early matters far more than the reason does; 遅れそうです states an estimate rather than a certainty.',
    ),
    sent(
        key='minta_izin_cuti', rel='atasan', fn='minta_izin_cuti', long=True,
        words=['来週', 'の', '金曜日', 'に', '通院', 'が', 'ある', 'ので', '、', '休ませて', 'ください', '。'],
        id_t='Jumat depan saya ada kontrol ke dokter, jadi izinkan saya tidak masuk.', en_t='I have a hospital appointment next Friday, so please let me take the day off.',
        sit='Meminta izin cuti karena urusan pribadi', sit_en='Asking for a day off for a personal matter',
        note='休ませてください adalah bentuk minta izin; 休みます adalah pemberitahuan, dan ke atasan itu berbeda nada.',
        note_en='休ませてください asks permission; 休みます is an announcement, which lands differently with a superior.',
    ),
    sent(
        key='ajukan_cuti_berbayar', rel='atasan', fn='ajukan_cuti_berbayar',
        words=['有給休暇', 'を', '取りたい', 'の', 'です', 'が', '、', 'ご都合', 'は', 'いかがですか', '。'],
        id_t='Saya ingin mengambil cuti berbayar, kapan waktu yang baik?', en_t='I would like to take paid leave, when would suit you?',
        sit='Mengajukan cuti berbayar', sit_en='Requesting paid leave',
        note='ご都合はいかがですか menyerahkan pilihan tanggal ke atasan, jadi permintaannya tidak terasa seperti pemberitahuan.',
        note_en='ご都合はいかがですか hands the date choice to the superior, so the request does not read as an announcement.',
    ),
    sent(
        key='atur_waktu_rapat', rel='rekan', fn='atur_waktu_rapat',
        words=['明日', 'の', '午後', '二時', 'から', '、', '打ち合わせ', 'を', 'お願いできますか', '。'],
        id_t='Bisa rapat koordinasi besok jam dua siang?', en_t='Could we have a working meeting tomorrow at two?',
        sit='Mengatur waktu rapat dengan rekan', sit_en='Setting a meeting time with a colleague',
        note='お願いできますか adalah bentuk permintaan yang halus; できますか saja menanyakan kemampuan dan terdengar lebih kasar.',
        note_en='お願いできますか is a soft request; できますか alone asks about ability and sounds blunter.',
    ),
    sent(
        key='ubah_jadwal_rapat', rel='rekan', fn='ubah_jadwal_rapat',
        words=['申し訳ありません', '、', '明日', 'の', '打ち合わせ', 'を', '来週', 'に', '変えて', 'もらえます', 'か', '。'],
        id_t='Mohon maaf, bisakah rapat koordinasi besok dipindah ke minggu depan?', en_t='I am sorry, could the meeting tomorrow be moved to next week?',
        sit='Meminta memindahkan jadwal rapat', sit_en='Asking to move a meeting',
        note='申し訳ありません dibuka lebih dulu karena ini merepotkan orang lain; memindahkan jadwal adalah permintaan, bukan pemberitahuan.',
        note_en='申し訳ありません opens it because this inconveniences someone; moving a meeting is a request, not an announcement.',
    ),
    sent(
        key='ajak_rapat', rel='atasan', fn='ajak_rapat',
        words=['来週', 'の', '月曜', 'に', '会議', 'を', '設定したい', 'の', 'です', 'が', '、', 'よろしいでしょうか', '。'],
        id_t='Saya ingin mengatur rapat untuk Senin depan, apakah tidak masalah?', en_t='I would like to set up a meeting for next Monday, would that be all right?',
        sit='Meminta persetujuan jadwal rapat kepada atasan', sit_en='Asking a superior to approve a meeting time',
        note='よろしいでしょうか adalah bentuk paling sopan dari いいですか, dan inilah bentuk yang dipakai ke atasan.',
        note_en='よろしいでしょうか is the politest form of いいですか, and this is the one used with a superior.',
    ),
    sent(
        key='minta_waktu_bicara', rel='atasan', fn='minta_waktu_bicara',
        words=['お時間', 'を', 'いただけますか', '。', '少しだけ', '相談', 'が', 'あります', '。'],
        id_t='Boleh minta waktunya? Ada sedikit yang ingin saya konsultasikan.', en_t='Could I have a moment? There is something small I would like to discuss.',
        sit='Meminta waktu atasan untuk konsultasi', sit_en='Asking a superior for a moment to consult',
        note='少しだけ (hanya sebentar) menurunkan beban permintaan; tanpa itu, meminta waktu atasan terdengar berat.',
        note_en='少しだけ (just a little) lowers the weight of the request; without it, asking for a superior\'s time sounds heavy.',
    ),
    sent(
        key='lapor_kemajuan', rel='atasan', fn='lapor_kemajuan',
        words=['資料', 'は', '八割', 'ほど', 'できました', '。', '明日', 'の', '午前', 'に', '送ります', '。'],
        id_t='Materinya sudah sekitar delapan puluh persen. Besok pagi saya kirim.', en_t='The materials are about eighty per cent done. I will send them tomorrow morning.',
        sit='Melaporkan kemajuan pekerjaan', sit_en='Reporting progress on a task',
        note='Menyebut persentase dan waktu kirim membuat laporan bisa dipercaya; hanya 順調です tidak memberi atasan apa pun untuk dipegang.',
        note_en='Giving a percentage and a send time makes the report trustworthy; 順調です alone gives a superior nothing to plan around.',
    ),
    sent(
        key='minta_perpanjangan', rel='atasan', fn='minta_perpanjangan', long=True,
        words=['確認', 'に', '時間', 'が', 'かかって', 'いる', 'ので', '、', '締め切り', 'を', '二日', '延ばして', 'いただけますか', '。'],
        id_t='Karena pengecekan butuh waktu, bisakah tenggatnya dimundurkan dua hari?', en_t='Checking is taking time, so could the deadline be moved back two days?',
        sit='Meminta perpanjangan tenggat', sit_en='Asking for a deadline extension',
        note='Menjelaskan sebabnya sebelum meminta, lalu menyebut jumlah hari yang pasti; permintaan tanpa angka lebih sulit dikabulkan.',
        note_en='The reason comes before the request, and the number of days is specific; a request without a figure is harder to grant.',
    ),
    sent(
        key='serahkan_tugas', rel='rekan', fn='serahkan_tugas',
        words=['明日', 'は', '休み', 'を', 'もらう', 'ので', '、', 'この', '仕事', 'を', 'お願いできますか', '。'],
        id_t='Besok saya ambil cuti, bisakah pekerjaan ini Anda tangani?', en_t='I am taking tomorrow off, could you handle this work?',
        sit='Menyerahkan pekerjaan sebelum cuti', sit_en='Handing over work before a day off',
        note='Menyerahkan tugas jauh sebelum hari cuti adalah kebiasaan kerja di Jepang; menyerahkannya mendadak dianggap merepotkan.',
        note_en='Handing over well before the day off is the workplace norm in Japan; doing it at the last minute is seen as a burden.',
    ),
    sent(
        key='tawarkan_bantuan', rel='rekan', fn='tawarkan_bantuan',
        words=['その', '資料', '、', '手伝いましょうか', '。', '今', 'は', '少し', '空いています', '。'],
        id_t='Materi itu, mau saya bantu? Sekarang saya agak luang.', en_t='Shall I help with those materials? I have a little time now.',
        sit='Menawarkan bantuan ke rekan', sit_en='Offering help to a colleague',
        note='手伝いましょうか menawarkan tanpa menekan; 手伝います akan berarti sudah memutuskan untuk membantu.',
        note_en='手伝いましょうか offers without pressing; 手伝います would mean you have already decided to help.',
    ),
    sent(
        key='terima_koreksi', rel='atasan', fn='terima_koreksi',
        words=['ご指摘', 'ありがとうございます', '。', 'すぐ', '直します', '。'],
        id_t='Terima kasih atas koreksinya. Saya perbaiki segera.', en_t='Thank you for pointing that out. I will fix it right away.',
        sit='Menerima koreksi atas kesalahan kerja', sit_en='Accepting a correction at work',
        note='ご指摘ありがとうございます adalah bentuk baku saat menerima koreksi; menyanggah lebih dulu dianggap tidak profesional.',
        note_en='ご指摘ありがとうございます is the standard reply to a correction; arguing first is seen as unprofessional.',
    ),
    sent(
        key='tanya_masalah', rel='rekan', fn='tanya_masalah',
        words=['何か', '問題', 'が', 'ありましたら', '、', 'すぐ', '教えて', 'ください', '。'],
        id_t='Kalau ada masalah, tolong segera beri tahu.', en_t='If there is any problem, let me know right away.',
        sit='Meminta rekan melaporkan masalah', sit_en='Asking a colleague to report problems',
        note='問題があったら memakai たら untuk syarat; ini cara meminta laporan tanpa menuduh ada masalah sekarang.',
        note_en='問題があったら uses たら for the condition, which asks for a report without implying a problem exists now.',
    ),
    sent(
        key='minta_konfirmasi', rel='rekan', fn='minta_konfirmasi',
        words=['お手数ですが', '、', '内容', 'を', '確認', 'して', 'いただけますか', '。'],
        id_t='Mohon maaf merepotkan, bisakah isinya dikonfirmasi?', en_t='Sorry to trouble you, could you check the contents?',
        sit='Meminta rekan mengonfirmasi isi pekerjaan', sit_en='Asking a colleague to confirm something',
        note='お手数ですが adalah pembuka baku untuk permintaan yang merepotkan orang lain.',
        note_en='お手数ですが is the standard opener for a request that troubles someone.',
    ),
    sent(
        key='kirim_materi', rel='rekan', fn='kirim_materi',
        words=['会議', 'の', '資料', 'を', '添付', 'しました', '。', 'ご確認', 'ください', '。'],
        id_t='Materi rapatnya sudah saya lampirkan. Mohon diperiksa.', en_t='I have attached the meeting materials. Please check them.',
        sit='Mengirim materi rapat', sit_en='Sending meeting materials',
        note='Go 確認ください adalah bentuk permintaan tertulis yang lazim di surel, padahal di ucapan jarang dipakai.',
        note_en='ご確認ください is the usual written request in email, though it is rare in speech.',
    ),
    sent(
        key='tanya_sudah_lihat', rel='rekan', fn='tanya_sudah_lihat',
        words=['昨日', '送った', '資料', 'は', 'もう', 'ご覧になりました', 'か', '。'],
        id_t='Materi yang saya kirim kemarin sudah Anda lihat?', en_t='Have you looked at the materials I sent yesterday?',
        sit='Menanyakan apakah materi sudah dibaca', sit_en='Checking whether materials have been read',
        note='ご覧になりましたか adalah bentuk hormat dari 見ましたか; untuk atasan bentuk ini yang dipakai, bukan 見ましたか.',
        note_en='ご覧になりましたか is the honorific form of 見ましたか; with a superior this is the form, not 見ましたか.',
    ),
    sent(
        key='tanya_jadwal', rel='rekan', fn='tanya_jadwal',
        words=['来週', 'の', '予定', 'は', 'もう', '決まりましたか', '。'],
        id_t='Jadwal minggu depan sudah ditentukan?', en_t='Has next week\'s schedule been decided yet?',
        sit='Menanyakan jadwal minggu depan', sit_en='Asking about next week\'s schedule',
        note='決まりましたか menanyakan apakah sudah ditetapkan; 決めましたか menanyakan apakah orangnya sudah memutuskan, dan itu berbeda.',
        note_en='決まりましたか asks whether it has been settled; 決めましたか asks whether the person decided, which is different.',
    ),
    sent(
        key='hadir_tidak_rapat', rel='atasan', fn='hadir_tidak_rapat',
        words=['申し訳ありません', '、', 'その', '時間', 'は', '予定', 'が', '入っています', 'ので', '、', '出られません', '。'],
        id_t='Mohon maaf, waktu itu sudah ada jadwal lain, jadi saya tidak bisa hadir.', en_t='I am sorry, I already have something then, so I cannot attend.',
        sit='Memberi tahu tidak bisa hadir rapat', sit_en='Saying you cannot attend a meeting',
        note='予定が入っています adalah alasan standar yang tidak menyebut detail pribadi, dan itu memang tujuannya.',
        note_en='予定が入っています is the standard reason that avoids personal detail, which is precisely its purpose.',
    ),
    sent(
        key='minta_wakil_rapat', rel='atasan', fn='minta_wakil_rapat',
        words=['私', 'の', '代わり', 'に', '田中', 'さん', 'が', '出席', 'して', 'も', 'よろしいでしょうか', '。'],
        id_t='Apakah Pak Tanaka boleh hadir mewakili saya?', en_t='Would it be all right for Tanaka to attend in my place?',
        sit='Meminta orang lain mewakili rapat', sit_en='Asking for someone to attend in your place',
        note='代わりに menandai penggantinya; meminta izin lebih dulu adalah hal yang sopan meski yang hadir bukan Anda.',
        note_en='代わりに marks the substitute; asking permission first is polite even though the attendee is not you.',
    ),
    sent(
        key='tanya_ada_di_tempat', rel='rekan', fn='tanya_ada_di_tempat',
        words=['すみません', '、', '部長', 'は', 'いらっしゃいます', 'か', '。'],
        id_t='Permisi, apakah kepala bagian ada?', en_t='Excuse me, is the department head in?',
        sit='Menanyakan apakah atasan ada di tempat', sit_en='Asking whether a superior is in',
        note='いらっしゃいます adalah bentuk hormat dari います; untuk atasan bentuk ini yang wajib, bukan いますか.',
        note_en='いらっしゃいます is the honorific form of います; for a superior this is required, not いますか.',
    ),
    sent(
        key='tinggalkan_pesan', rel='rekan', fn='tinggalkan_pesan',
        words=['伝言', 'を', 'お願いします', '。', '折り返し', 'お電話', 'を', 'いただきたい', 'の', 'です', 'が', '。'],
        id_t='Tolong sampaikan pesan. Saya ingin beliau menelepon balik.', en_t='Could you pass on a message? I would like a call back.',
        sit='Meninggalkan pesan lewat telepon', sit_en='Leaving a message by phone',
        note='いただきたいのですが adalah bentuk permintaan yang sangat halus, dan inilah yang dipakai lewat telepon kantor.',
        note_en='いただきたいのですが is a very soft request and is the form used on an office phone.',
    ),
    sent(
        key='lapor_selesai', rel='atasan', fn='lapor_selesai',
        words=['ご', '依頼', 'の', '資料', 'は', '先ほど', '送りました', '。', 'ご確認ください', '。'],
        id_t='Materi yang Anda minta tadi sudah saya kirim. Mohon diperiksa.', en_t='I sent the materials you asked for a little while ago. Please check them.',
        sit='Melaporkan pekerjaan sudah selesai', sit_en='Reporting that work is done',
        note='先ほど (tadi) lebih sopan daripada さっき di surel kerja, meskipun artinya sama.',
        note_en='先ほど (a little while ago) is more polite than さっき in work email, though the meaning is the same.',
    ),
    sent(
        key='paham_instruksi', rel='atasan', fn='paham_instruksi',
        words=['承知しました', '。', '締め切り', 'まで', 'に', '終わらせます', '。'],
        id_t='Baik, saya mengerti. Saya selesaikan sebelum tenggat.', en_t='Understood. I will finish it before the deadline.',
        sit='Menyatakan mengerti instruksi', sit_en='Confirming you understood an instruction',
        note='Mengulang tenggat setelah 承知しました membuktikan Anda mendengar detailnya, bukan hanya menyetujui.',
        note_en='Repeating the deadline after 承知しました shows you heard the detail rather than merely agreeing.',
    ),
    sent(
        key='tanya_ulang_instruksi', rel='atasan', fn='tanya_ulang_instruksi',
        words=['申し訳ありません', '、', 'もう一度', '教えて', 'いただけますか', '。'],
        id_t='Mohon maaf, bisakah dijelaskan sekali lagi?', en_t='I am sorry, could you explain once more?',
        sit='Meminta instruksi diulang', sit_en='Asking for an instruction to be repeated',
        note='Menanyakan ulang jauh lebih baik daripada mengerjakan hal yang salah; yang membuatnya sopan adalah 申し訳ありません di depan.',
        note_en='Asking again beats doing the wrong task; what makes it polite is the 申し訳ありません in front.',
    ),
    sent(
        key='komplain_tidak_sempat', rel='atasan', fn='komplain_tidak_sempat',
        words=['この', 'まま', 'です', 'と', '、', '締め切り', 'に', '間に合いません', '。', '優先順位', 'を', '相談', 'させて', 'ください', '。'],
        id_t='Kalau begini terus, saya tidak akan sempat dengan tenggat. Izinkan saya berdiskusi soal prioritas.', en_t='At this rate I will not make the deadline. Let me discuss the priorities with you.',
        sit='Melaporkan tidak akan sempat sebelum tenggat', sit_en='Reporting that a deadline will be missed',
        note='Mengabari lebih awal dan sekaligus mengusulkan cara menyelesaikannya jauh lebih dihargai daripada diam lalu gagal.',
        note_en='Warning early and proposing a way through is far better received than staying silent and failing.',
    ),
    sent(
        key='tolak_permintaan', rel='atasan', fn='tolak_permintaan',
        words=['申し訳ありません', '、', '今週', 'は', '手', 'が', '離せなくて', '、', 'お受けできません', '。'],
        id_t='Mohon maaf, minggu ini saya tidak bisa melepas pekerjaan, jadi tidak bisa menerima.', en_t='I am sorry, I cannot step away from my work this week, so I cannot take it on.',
        sit='Menolak permintaan tambahan dengan sopan', sit_en='Declining extra work politely',
        note='Menolak disertai alasannya jauh lebih diterima daripada menolak tanpa sebab; お受けできません lebih halus daripada できません.',
        note_en='A refusal with a reason is far better received than one without; お受けできません is softer than できません.',
    ),
    sent(
        key='tanya_prioritas', rel='atasan', fn='tanya_prioritas',
        words=['二つ', '同時', 'に', 'は', 'できません', 'ので', '、', 'どちら', 'を', '先', 'に', 'すれば', 'いいでしょうか', '。'],
        id_t='Saya tidak bisa mengerjakan dua sekaligus, mana yang sebaiknya didahulukan?', en_t='I cannot do both at once, which should I do first?',
        sit='Menanyakan prioritas saat dua tugas bertabrakan', sit_en='Asking which task comes first',
        note='Menanyakan prioritas memindahkan keputusan ke atasan, yang memang tempatnya; mengerjakan keduanya setengah jalan justru lebih buruk.',
        note_en='Asking moves the decision to the superior, which is where it belongs; half-finishing both is worse.',
    ),
    sent(
        key='bilang_sibuk', rel='rekan', fn='bilang_sibuk',
        words=['すみません', '、', '今', 'は', '手', 'が', 'いっぱい', 'です', '。', '午後', 'なら', '大丈夫', 'です', '。'],
        id_t='Maaf, sekarang saya sedang penuh. Kalau sore saya bisa.', en_t='Sorry, I am tied up right now. This afternoon would work.',
        sit='Mengatakan sedang sibuk tapi menawarkan waktu lain', sit_en='Saying you are busy while offering another time',
        note='Menolak sekarang tapi menyebut waktu lain membuatnya tidak terasa seperti penolakan.',
        note_en='Declining now while naming another time keeps it from reading as a refusal.',
    ),
    sent(
        key='bilang_luang', rel='rekan', fn='bilang_luang',
        words=['今', 'は', '大丈夫', 'です', '。', '何', 'です', 'か', '。'],
        id_t='Sekarang saya bisa. Ada apa?', en_t='I am free now. What is it?',
        sit='Menyatakan sedang ada waktu', sit_en='Saying you are free now',
        note='何ですか setelah 大丈夫です menanyakan keperluannya; tanpa itu, kalimatnya menggantung.',
        note_en='何ですか after 大丈夫です asks what is needed; without it the sentence hangs.',
    ),
    sent(
        key='syukuri_bantuan', rel='rekan', fn='syukuri_bantuan',
        words=['手伝って', 'くれて', '本当', 'に', '助かりました', '。'],
        id_t='Terima kasih sudah membantu, sangat menolong.', en_t='Thank you for helping, that really saved me.',
        sit='Berterima kasih atas bantuan rekan', sit_en='Thanking a colleague for help',
        note='助かりました menyebut manfaatnya secara konkret, jadi terima kasihnya tidak terasa kosong.',
        note_en='助かりました names the concrete benefit, so the thanks do not ring hollow.',
    ),
    sent(
        key='bilang_bisa_dihubungi', rel='atasan', fn='bilang_bisa_dihubungi',
        words=['何か', 'あれば', '、', '携帯', 'に', '連絡', 'して', 'ください', '。'],
        id_t='Kalau ada apa-apa, hubungi ponsel saya.', en_t='If anything comes up, contact my mobile.',
        sit='Memberi tahu cara menghubungi saat keluar', sit_en='Saying how to reach you while out',
        note='何かあれば adalah bentuk bersyarat yang lunak; ini cara memberi kesiapan tanpa mengundang masalah.',
        note_en='何かあれば is a soft conditional, a way of offering availability without inviting trouble.',
    ),
    sent(
        key='minta_dihubungi_kembali', rel='rekan', fn='minta_dihubungi_kembali',
        words=['お手数ですが', '、', '戻られたら', '折り返し', 'お電話', 'を', 'いただけますか', '。'],
        id_t='Mohon maaf merepotkan, kalau sudah kembali bisakah menelepon balik?', en_t='Sorry to trouble you, could they call back once they return?',
        sit='Meminta ditelepon balik setelah orang kembali', sit_en='Asking for a call back once someone returns',
        note='戻られたら memakai bentuk hormat untuk orang lain, jadi sopan meski bicara ke rekan sekantor.',
        note_en='戻られたら uses the honorific form for the other person, so it stays polite even speaking to a colleague.',
    ),
    sent(
        key='perkenalkan_diri_kantor', rel='rekan', fn='perkenalkan_diri_kantor', long=True,
        words=['今日', 'から', 'この', '部署', 'で', 'お世話になります', '。', 'アリ', 'です', '。', 'よろしく', 'お願いします', '。'],
        id_t='Mulai hari ini saya bekerja di divisi ini. Saya Ari. Mohon bantuannya.', en_t='Starting today I am in this department. I am Ari. Please treat me well.',
        sit='Memperkenalkan diri di departemen baru', sit_en='Introducing yourself to a new department',
        note='お世話になります menyatakan akan merepotkan ke depannya, dan itulah pembuka perkenalan kerja yang baku.',
        note_en='お世話になります acknowledges you will be a burden going forward, which is the standard work introduction opener.',
    ),
    sent(
        key='bilang_belum_paham', rel='atasan', fn='bilang_belum_paham',
        words=['すみません', '、', 'その', '部分', 'が', 'まだ', 'よく', '分からない', 'の', 'です', 'が', '。'],
        id_t='Maaf, bagian itu saya masih belum begitu paham.', en_t='Sorry, I still do not quite understand that part.',
        note='Kalimatnya berhenti di が, yang membuatnya terasa sebagai pembuka permintaan penjelasan, bukan pengakuan telak.',
        note_en='The sentence trails off at が, which makes it an opener for asking rather than a flat admission.',
        sit='Mengakui belum paham instruksi', sit_en='Admitting you do not yet understand an instruction',
    ),
    sent(
        key='tanya_cara_kerja', rel='rekan', fn='tanya_cara_kerja',
        words=['この', '仕事', 'は', '普段', 'どう', 'やっています', 'か', '。'],
        id_t='Pekerjaan ini biasanya dikerjakan bagaimana?', en_t='How is this work usually done here?',
        sit='Menanyakan cara kerja yang berlaku di kantor', sit_en='Asking how things are usually done',
        note='普段 (biasanya) membuatnya menanyakan kebiasaan kantor, bukan cara yang menurut Anda benar; itu yang membuatnya aman.',
        note_en='普段 (usually) makes it a question about office habit rather than your view of the right way, which keeps it safe.',
    ),
    sent(
        key='lapor_kerja_lembur', rel='atasan', fn='lapor_kerja_lembur',
        words=['今日', 'は', 'この', '分', 'を', '終わらせる', 'ために', '残業します', '。'],
        id_t='Hari ini saya lembur supaya bagian ini selesai.', en_t='I will work overtime today to finish this part.',
        sit='Memberi tahu akan lembur', sit_en='Telling a superior you will work overtime',
        note='Menyebut alasan lemburnya jauh lebih baik daripada hanya bilang 残業します; di banyak kantor lembur perlu dilaporkan lebih dulu.',
        note_en='Giving the reason is far better than a bare 残業します; in many offices overtime must be reported in advance.',
    ),
]
